<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of YodelTrackingStatus
 *
 * @author kiran.iftikhar
 */
class EcomTrackingStatus {
    
    public function __construct() {
        
    }
    
    public static $ecom_status_code = array(        
        "001" => "Soft data Uploaded",
        "013" => "Pickup Registered",
        "1210" => "Pickup Unassigned",
        "1220" => "Pickup Assigned",
        "1230" => "Out for Pickup",
        "1260" => "Excess Shipment Pickedup",
        "1310" => "Pickup Failed due to Misroute",
        "1320" => "Pickup Failed, Shipment picked up by other Courier",
        "1330" => "Pickup Cancelled By Customer",
        "1340" => "Pickup Failed, Shipment Not Handed Over",
        "1350" => "Pickup Failed, Shipment Not Ready",
        "1360" => "Pickup Failed, Premise Closed",
        "1370" => "Pickup Failed, Vendor Shifted",
        "1380" => "Pickup Failed, Road Blocked/Premise Inaccessible",
        "1390" => "Picked Failed, Pickup attempted Late",
        "1400" => "Pickup Request Received After Cut-Off",
        "1410" => "Pickup Rescheduled for Next Day",
        "1420" => "Pickup Failed,Barcode Not Readable",
        "1430" => "Pickup Reassigned to Another Employee",
        "0011" => "Field pickup via Laptop",
        "014" => "Out For Pickup",
        "310" => "Soft Data uploaded - Shipment not picked up",
        "326" => "Shipment Cancelled after Max unsuccessful pickup attempts",
        "334" => "Improper packaging - no branded tape and packaging",
        "002" => "In-Scan at Ecom Facility",
        "127" => "Shipment arrived at Ecom Facility�",
        "003" => "Bagging Completed 003",
        "003" => "Bagging Completed 003",
        "004" => "Assigned to Run Code 004",
        "005" => "Shipment at Delivery Centre 005",
        "006" => "Outscan 006 ( Out for Delivery )",
        "100" => "Delay in Delivery Expected",
        "101" => "Shipment Detained At Origin/PPC",
        "203" => "Re-attempt and Return",
        "205" => "Redirection on same Air Waybill",
        "240" => "Shipment hold at origin / processing center",
        "301" => "Shipment Detained/Seized by Regulatory Authority",
        "303" => "Shipment In Transit",
        "304" => "Network Delay",
        "305" => "Shipment offloaded by airlines",
        "306" => "Flight Cancelled",
        "307" => "Held - Regulatory Paperwork Required",
        "308" => "Held for Octroi / Taxes",
        "309" => "Missed Connection",
        "230" => "Misrouted due to ECOM's Fault",
        "325" => "Poor packaging",
        "200" => "Shipment forcibly taken by customer",
        "201" => "Awaiting Consignee's Response for Delivery",
        "202" => "Correction Of Wrong POD Details",
        "206" => "Return to Origin on Same Air Waybill",
        "207" => "Shipment misroute - delay in delivery expected",
        "208" => "Contact Customer Service",
        "209" => "Consignee Refusing to Pay COD Amount",
        "210" => "Shipment attempted - Customer refused to accept",
        "211" => "RTO Shipment HAL as per Customer's Request",
        "212" => "Consignee Out Of Station",
        "213" => "Scheduled for Next Day Delivery",
        "214" => "Need Department Name/ Extension Number",
        "215" => "Shipment cannot be attempted - Disturbance/Natural Disaster/Strike",
        "216" => "Late Arrival/Scheduled for Next Working Day",
        "217" => "Delivery Area Not Accessible",
        "218" => "Consignee Shifted from the Given Address",
        "219" => "Consignee Not Available",
        "220" => "No Such Consignee At Given Address",
        "221" => "Seller / FC refused to accept return shipment",
        "222" => "Address Incorrect",
        "223" => "Shipment attempted - wrong address",
        "224" => "Address Unlocatable",
        "225" => "Shipment Manifested - Not Received by Destination",
        "226" => "Holiday/Weekly off - Delivery on Next Working Day",
        "227" => "Shipment attempted - Residence/Office closed",
        "228" => "Out of Delivery Area",
        "229" => "Shipment hold at delivery center",
        "231" => "Shipment attempted - Customer not available",
        "232" => "Customer requested delivery on another address",
        "233" => "COD DENOMINATION NOT ACCEPTED",
        "234" => "Address pincode mismatch",
        "235" => "Bulk order by consignee",
        "236" => "Shipment hold at delivery center",
        "237" => "Contact Customer Service",
        "238" => "Contact Customer Service",
        "331" => "Consignee requested for future delivery ",
        "332" => "SHIPMENT UNDER INVESTIGATION",
        "333" => "Shipment Lost",
        "666" => "SDL - Special delivery location",
        "888" => "Shipment Destroyed/Abandoned",
        "218" => "Consignee Shifted from the Given Address",
        "219" => "Consignee Not Available",
        "220" => "No Such Consignee At Given Address",
        "1224" => "Delivery Attempt To Be Made",
        "1225" => "Delivery Attempt Not To Be Made",
        "999" => "Delivered",
        "204" => "Shipment Delivered/Consignee Complains of Damage",
        "777" => "RTS - Return To Shipper",
        "77" => "RTO Lock - State comes just before RTS",
        "80" => "RTO Lock Revoked - Incase customer change mind and ready to accept the Shipmet than we revoke the lock.",
        "82" => "OFD Lock - to restrict delivery/OFD",
        "83" => "OFD Lock Revoked - Shipment allowed for OFD",
        "999" => "Delivered",

    );
 
    public static $consignment_status_code = array(
        "001" => Consignment::STATUS_LABEL_CREATED,
        "013" => Consignment::STATUS_INTRANSIT,
        "1210" => Consignment::STATUS_INTRANSIT,
        "1220" => Consignment::STATUS_INTRANSIT,
        "1230" => Consignment::STATUS_INTRANSIT,
        "1260" => Consignment::STATUS_INTRANSIT,
        "1310" => Consignment::STATUS_PROBLEM,
        "1320" => Consignment::STATUS_PROBLEM,
        "1330" => Consignment::STATUS_CANCELLED,
        "1340" => Consignment::STATUS_PROBLEM,
        "1350" => Consignment::STATUS_PROBLEM,
        "1360" => Consignment::STATUS_PROBLEM,
        "1370" => Consignment::STATUS_PROBLEM,
        "1380" => Consignment::STATUS_PROBLEM,
        "1390" => Consignment::STATUS_PROBLEM,
        "1400" => Consignment::STATUS_INTRANSIT,
        "1410" => Consignment::STATUS_INTRANSIT,
        "1420" => Consignment::STATUS_PROBLEM,
        "1430" => Consignment::STATUS_INTRANSIT,
        "0011" => Consignment::STATUS_INTRANSIT,
        "014" => Consignment::STATUS_INTRANSIT,
        "310" => Consignment::STATUS_RECEIVED,
        "326" => Consignment::STATUS_CANCELLED,
        "334" => Consignment::STATUS_PROBLEM,
        "002" => Consignment::STATUS_INTRANSIT,
        "127" => Consignment::STATUS_INTRANSIT,
        "003" => Consignment::STATUS_INTRANSIT,
        "003" => Consignment::STATUS_INTRANSIT,
        "004" => Consignment::STATUS_INTRANSIT,
        "005" => Consignment::STATUS_INTRANSIT,
        "006" => Consignment::STATUS_INTRANSIT,
        "100" => Consignment::STATUS_INTRANSIT,
        "101" => Consignment::STATUS_HOLD,
        "203" => Consignment::STATUS_RETURNED,
        "205" => Consignment::STATUS_INTRANSIT,
        "240" => Consignment::STATUS_HOLD,
        "301" => Consignment::STATUS_HOLD,
        "303" => Consignment::STATUS_INTRANSIT,
        "304" => Consignment::STATUS_INTRANSIT,
        "305" => Consignment::STATUS_INTRANSIT,
        "306" => Consignment::STATUS_INTRANSIT,
        "307" => Consignment::STATUS_HOLD,
        "308" => Consignment::STATUS_HOLD,
        "309" => Consignment::STATUS_PROBLEM,
        "230" => Consignment::STATUS_PROBLEM,
        "325" => Consignment::STATUS_PROBLEM,
        "200" => Consignment::STATUS_INTRANSIT,
        "201" => Consignment::STATUS_INTRANSIT,
        "202" => Consignment::STATUS_INTRANSIT,
        "206" => Consignment::STATUS_RETURNED,
        "207" => Consignment::STATUS_PROBLEM,
        "208" => Consignment::STATUS_INTRANSIT,
        "209" => Consignment::STATUS_PROBLEM,
        "210" => Consignment::STATUS_PROBLEM,
        "211" => Consignment::STATUS_INTRANSIT,
        "212" => Consignment::STATUS_INTRANSIT,
        "213" => Consignment::STATUS_INTRANSIT,
        "214" => Consignment::STATUS_INTRANSIT,
        "215" => Consignment::STATUS_PROBLEM,
        "216" => Consignment::STATUS_INTRANSIT,
        "217" => Consignment::STATUS_PROBLEM,
        "218" => Consignment::STATUS_PROBLEM,
        "219" => Consignment::STATUS_PROBLEM,
        "220" => Consignment::STATUS_PROBLEM,
        "221" => Consignment::STATUS_PROBLEM,
        "222" => Consignment::STATUS_PROBLEM,
        "223" => Consignment::STATUS_PROBLEM,
        "224" => Consignment::STATUS_PROBLEM,
        "225" => Consignment::STATUS_INTRANSIT,
        "226" => Consignment::STATUS_INTRANSIT,
        "227" => Consignment::STATUS_INTRANSIT,
        "228" => Consignment::STATUS_INTRANSIT,
        "229" => Consignment::STATUS_HOLD,
        "231" => Consignment::STATUS_INTRANSIT,
        "232" => Consignment::STATUS_INTRANSIT,
        "233" => Consignment::STATUS_PROBLEM,
        "234" => Consignment::STATUS_PROBLEM,
        "235" => Consignment::STATUS_INTRANSIT,
        "236" => Consignment::STATUS_HOLD,
        "237" => Consignment::STATUS_INTRANSIT,
        "238" => Consignment::STATUS_INTRANSIT,
        "331" => Consignment::STATUS_INTRANSIT,
        "332" => Consignment::STATUS_INTRANSIT,
        "333" => Consignment::STATUS_PROBLEM,
        "666" => Consignment::STATUS_INTRANSIT,
        "888" => Consignment::STATUS_CANCELLED,
        "218" => Consignment::STATUS_PROBLEM,
        "219" => Consignment::STATUS_PROBLEM,
        "220" => Consignment::STATUS_PROBLEM,
        "1224" => Consignment::STATUS_INTRANSIT,
        "1225" => Consignment::STATUS_INTRANSIT,
        "999" => Consignment::STATUS_DELIVERED,
        "204" => Consignment::STATUS_AWATING_CLAIM,
        "777" => Consignment::STATUS_RETURNED,
        "77" => Consignment::STATUS_RETURNED,
        "80" => Consignment::STATUS_RETURNED,
        "82" => Consignment::STATUS_INTRANSIT,
        "83" => Consignment::STATUS_INTRANSIT,
        
    );

    public static $oneworld_ecom = array(
        "001" => 144,
        "013" => 137,
        "1210" => 137,
        "1220" => 137,
        "1230" => 137,
        "1260" => 133,
        "1310" => 131,
        "1320" => 131,
        "1330" => 115,
        "1340" => 131,
        "1350" => 131,
        "1360" => 131,
        "1370" => 131,
        "1380" => 131,
        "1390" => 131,
        "1400" => 137,
        "1410" => 137,
        "1420" => 115,
        "1430" => 137,
        "0011" => 137,
        "014" => 137,
        "310" => 144,
        "326" => 131,
        "334" => 115,
        "002" => 137,
        "127" => 146,
        "003" => 137,
        "003" => 137,
        "004" => 137,
        "005" => 137,
        "006" => 111,
        "100" => 120,
        "101" => 136,
        "203" => 138,
        "205" => 137,
        "240" => 136,
        "301" => 136,
        "303" => 137,
        "304" => 120,
        "305" => 151,
        "306" => 115,
        "307" => 128,
        "308" => 128,
        "309" => 115,
        "230" => 150,
        "325" => 115,
        "200" => 137,
        "201" => 113,
        "202" => 137,
        "206" => 138,
        "207" => 150,
        "208" => 137,
        "209" => 115,
        "210" => 115,
        "211" => 137,
        "212" => 116,
        "213" => 137,
        "214" => 112,
        "215" => 115,
        "216" => 137,
        "217" => 115,
        "218" => 112,
        "219" => 116,
        "220" => 116,
        "221" => 115,
        "222" => 112,
        "223" => 112,
        "224" => 112,
        "225" => 137,
        "226" => 137,
        "227" => 116,
        "228" => 111,
        "229" => 136,
        "231" => 116,
        "232" => 137,
        "233" => 115,
        "234" => 112,
        "235" => 137,
        "236" => 136,
        "237" => 137,
        "238" => 137,
        "331" => 137,
        "332" => 137,
        "333" => 157,
        "666" => 137,
        "888" => 152,
        "218" => 112,
        "219" => 116,
        "220" => 112,
        "1224" => 123,
        "1225" => 137,
        "999" => 121,
        "204" => 118,
        "777" => 138,
        "77" => 137,
        "80" => 137,
        "82" => 115,
        "83" => 111,
        "999" => 121,
    );
    public static function getOweStatusCode($ecomStatus){
        $ecomTrackingStatus = self::$oneworld_ecom;
        return isset($ecomTrackingStatus[$ecomStatus]) ? $ecomTrackingStatus[$ecomStatus] : 0;
    }
    public static function getConsignmentStatus($ecomStatus){
        $consignmentStatusCodes = Tracking::$oneworld_consignment_code_mapping;
        return isset($consignmentStatusCodes[$ecomStatus]) ? $consignmentStatusCodes[$ecomStatus] : 0;
    }
}
