<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of YodelTrackingStatus
 *
 * @author kiran.iftikhar
 */
class VivaTrackingStatus {
    
    public function __construct() {
        
    }
    
    public static $viva_status_code = array( 
        "00" => "Delivered",
        "01" => "Unable to locate the address - please advise telephone no.",
        "02" => "Illegible address - please advise full details",
        "03" => "Incorrect address - please revert new details",
        "04" => "Company not known at the address",
        "05" => "Shipment refused",
        "06" => "Contact person not known at the address",
        "07" => "Delivery not completed",
        "08" => "Not in / closed on delivery - will re-attempt tomorrow",
        "09" => "Not in / closed on delivery - calling card left",
        "10" => "Business closed (holiday)",
        "11" => "Business closed (strike)",
        "12" => "Future Delivery Requested",
        "13" => "Consignee moved - new address located",
        "14" => "Consignee moved - please provide new info.",
        "15" => "Shipment held for pick-up",
        "16" => "Shipment destined for area not currently serviced  ",
        "17" => "Shipment received",
        "18" => "Shipment manifested",
        "19" => "Bags arrived at destination",
        "20" => "Onfwd to Cnee (local transp) - Cnee will collect locally",
        "21" => "Onforwarded to Agent station - delivery in outer location",
        "22" => "Onforwarded by post - delivery in outer location",
        "23" => "Out for delivery",
        "24" => "Onfwd to subcontractor - POD will not be Available",
        "25" => "Pick-up executed",
        "26" => "Handed over to ( Agent of) Customer of Shipment Picked-up",
        "27" => "Pickup attempted   ",
        "28" => "Pickup not attempted",
        "30" => "Held in Customs - pending clearance",
        "31" => "Held in Customs - undergoing clearance",
        "32" => "Held in Customs - value misdeclared",
        "33" => "Held in Customs - missing invoice copies",
        "34" => "Held in Customs - missing original invoice",
        "35" => "Held in Customs - invoice shows no value",
        "36" => "Held in Customs - invoice shows no currency",
        "37" => "Held in Customs - awaiting info from Consignee",
        "38" => "Held in Customs - wrong address",
        "39" => "Held in Customs - nobody in/closed",
        "40" => "Cleared awaiting payments of duties and taxes by Cnee",
        "41" => "Cnee refuses to pay duties /taxes -please advise",
        "42" => "Given to customs broker",
        "43" => "Given to consignee's Custom Broker (POD equivalent)",
        "44" => "SHIPMENT ON HOLD - Value misdeclared",
        "45" => "SHIPMENT ON HOLD - Missing Invoice Copies",
        "46" => "SHIPMENT ON HOLD - Missing Original Invoice",
        "47" => "SHIPMENT ON HOLD - Invoice Shows no Value", 
        "48" => "SHIPMENT ON HOLD - Invoice Shows no Currency",
        "49" => "SHIPMENT ON HOLD - AT STATION",
        "50" => "Missorted package sent back to export station",
        "51" => "Rerouted to correct station directly",
        "52" => "Manifested but not arrived (missing) at import station",
        "53" => "Missorted package received",
        "54" => "Package arrived unmanifested",
        "55" => "Shipment improperly packed - delay while re-packing",
        "56" => "Shipment damaged on arrival - attempting delivery",
        "57" => "Damaged received- pls advise",
        "58" => "Multiple package shipment - not all pieces arrived",
        "59" => "MISROUTE",
        "60" => "Flight delay - aircraft technical problems",
        "66" => "Delayed:offloaded by carrier",
        "67" => "DELAYED due to special case:",
        "68" => "delayed: shipment received after cut-off time",
        "70" => "Shipment returned to sender as agreed with export station",
        "71" => "Shipment destroyed upon shippers request",
        "79" => "Shipment CONFISCATED by Customs",
        "80" => "Confirmed lost shipment",
        "81" => "COD info for Customer",
        "82" => "COD info for Agent",
        "83" => "Accounting info for Customer",
        "84" => "Accounting info for Agent",
        "85" => "New information provided by shipper", 
        "86" => "New documents provided by shipper",       
        "87" => "New information provided by agent",
        "88" => "Important communication to Shipper",
        "90" => "Hard Copy request",       
        "91" => "1st POD request",       
        "92" => "2nd POD request",      
        "93" => "3rd(+) POD request",
        "94" => "Client Claims non-delivery",       
        "95" => "Claim closed",
        "97" => "Miscellaneous for Agent", 
        "98" => "Miscellaneous for Customer",
        "C2" => " - CANNOT CONTACT RECIPIENT"

        );

    public static $consignment_status_code = array(
        "00" => Consignment::STATUS_DELIVERED,
        "01" => Consignment::STATUS_PROBLEM,
        "02" => Consignment::STATUS_PROBLEM,
        "03" => Consignment::STATUS_PROBLEM,
        "04" => Consignment::STATUS_PROBLEM,
        "05" => Consignment::STATUS_PROBLEM,
        "06" => Consignment::STATUS_PROBLEM,
        "07" => Consignment::STATUS_PARTIAL_DELIVERED,
        "08" => Consignment::STATUS_INTRANSIT,
        "09" => Consignment::STATUS_INTRANSIT,
        "10" => Consignment::STATUS_INTRANSIT,
        "11" => Consignment::STATUS_INTRANSIT,
        "12" => Consignment::STATUS_INTRANSIT,
        "13" => Consignment::STATUS_INTRANSIT,
        "14" => Consignment::STATUS_INTRANSIT,
        "15" => Consignment::STATUS_HOLD,
        "16" => Consignment::STATUS_INVALID,
        "17" => Consignment::STATUS_RECEIVED,
        "18" => Consignment::STATUS_DISPATCHED,
        "19" => Consignment::STATUS_RECEIVED,
        "20" => Consignment::STATUS_INTRANSIT,
        "21" => Consignment::STATUS_DELIVERED,
        "22" => Consignment::STATUS_DELIVERED,
        "23" => Consignment::STATUS_INTRANSIT,
        "24" => Consignment::STATUS_INTRANSIT,
        "25" => Consignment::STATUS_INTRANSIT,
        "26" => Consignment::STATUS_INTRANSIT,
        "27" => Consignment::STATUS_INTRANSIT,
        "28" => Consignment::STATUS_INTRANSIT,
        "30" => Consignment::STATUS_HOLD,
        "31" => Consignment::STATUS_HOLD,
        "32" => Consignment::STATUS_HOLD,
        "33" => Consignment::STATUS_HOLD,
        "34" => Consignment::STATUS_HOLD,
        "35" => Consignment::STATUS_HOLD,
        "36" => Consignment::STATUS_HOLD,
        "37" => Consignment::STATUS_HOLD,
        "38" => Consignment::STATUS_HOLD,
        "39" => Consignment::STATUS_HOLD,
        "40" => Consignment::STATUS_INTRANSIT,
        "41" => Consignment::STATUS_PROBLEM,
        "42" => Consignment::STATUS_INTRANSIT,
        "43" => Consignment::STATUS_INTRANSIT,
        "44" => Consignment::STATUS_HOLD,
        "45" => Consignment::STATUS_HOLD,
        "46" => Consignment::STATUS_HOLD,
        "47" => Consignment::STATUS_HOLD,
        "48" => Consignment::STATUS_HOLD,
        "49" => Consignment::STATUS_HOLD,
        "50" => Consignment::STATUS_PROBLEM,
        "51" => Consignment::STATUS_INTRANSIT,
        "52" => Consignment::STATUS_INTRANSIT,
        "53" => Consignment::STATUS_PROBLEM,
        "54" => Consignment::STATUS_INTRANSIT,
        "55" => Consignment::STATUS_INTRANSIT,
        "56" => Consignment::STATUS_INTRANSIT,
        "57" => Consignment::STATUS_PROBLEM,
        "58" => Consignment::STATUS_INTRANSIT,
        "59" => Consignment::STATUS_PROBLEM,
        "60" => Consignment::STATUS_INTRANSIT,
        "66" => Consignment::STATUS_INTRANSIT,
        "67" => Consignment::STATUS_INTRANSIT,
        "68" => Consignment::STATUS_INTRANSIT,
        "70" => Consignment::STATUS_RETURNED,
        "71" => Consignment::STATUS_CANCELLED,
        "79" => Consignment::STATUS_PROBLEM,
        "80" => Consignment::STATUS_PROBLEM,
        "81" => Consignment::STATUS_INTRANSIT,
        "82" => Consignment::STATUS_INTRANSIT,
        "83" => Consignment::STATUS_INTRANSIT,
        "84" => Consignment::STATUS_INTRANSIT,
        "85" => Consignment::STATUS_INTRANSIT, 
        "86" => Consignment::STATUS_INTRANSIT,     
        "87" => Consignment::STATUS_INTRANSIT,
        "88" => Consignment::STATUS_INTRANSIT,
        "90" => Consignment::STATUS_INTRANSIT,       
        "91" => Consignment::STATUS_INTRANSIT,       
        "92" => Consignment::STATUS_INTRANSIT,      
        "93" => Consignment::STATUS_INTRANSIT,
        "94" => Consignment::STATUS_AWATING_CLAIM,       
        "95" => Consignment::STATUS_CLOSE,
        "97" => Consignment::STATUS_INTRANSIT, 
        "98" => Consignment::STATUS_INTRANSIT,
        "C2" => Consignment::STATUS_PROBLEM
        
        );

    public static $oneworld_viva = array(
        "00" => 121,
        "01" => 112,
        "02" => 112,
        "03" => 112,
        "04" => 112,
        "05" => 115,
        "06" => 115,
        "07" => 123,
        "08" => 123,
        "09" => 123,
        "10" => 137,
        "11" => 137,
        "12" => 137,
        "13" => 137,
        "14" => 112,
        "15" => 128,
        "16" => 115,
        "17" => 137,
        "18" => 126,
        "19" => 137,
        "20" => 114,
        "21" => 121,
        "22" => 121,
        "23" => 111,
        "24" => 137,
        "25" => 133,
        "26" => 137,
        "27" => 137,
        "28" => 131,
        "30" => 117,
        "31" => 117,
        "32" => 117,
        "33" => 117,
        "34" => 117,
        "35" => 117,
        "36" => 117,
        "37" => 117,
        "38" => 117,
        "39" => 117,
        "40" => 137,
        "41" => 115,
        "42" => 137,
        "43" => 137,
        "44" => 128,
        "45" => 128,
        "46" => 128,
        "47" => 128,
        "48" => 128,
        "49" => 128,
        "50" => 138,
        "51" => 137,
        "52" => 135,
        "53" => 115,
        "54" => 137,
        "55" => 120,
        "56" => 137,
        "57" => 119,
        "58" => 137,
        "59" => 115,
        "60" => 120,
        "66" => 120,
        "67" => 120,
        "68" => 120,
        "70" => 138,
        "71" => 136,
        "79" => 115,
        "80" => 115,
        "81" => 137,
        "83" => 137,
        "87" => 137,
        "88" => 137,
        "98" => 137,
        "82" => 137,
        "83" => 137,
        "84" => 137,
        "85" => 137, 
        "86" => 137,       
        "87" => 137,
        "88" => 137,
        "90" => 137,       
        "91" => 137,       
        "92" => 137,      
        "93" => 137,
        "94" => 125,       
        "95" => 125,
        "97" => 137, 
        "98" => 137,
        "C2" => 115
    );
    public static function getOweStatusCode($vivaStatus){
        $vivaStatus = trim($vivaStatus);
        $vivaTrackingStatus = self::$oneworld_viva;
        return isset($vivaTrackingStatus[$vivaStatus]) ? $vivaTrackingStatus[$vivaStatus] : 0;
    }
    public static function getConsignmentStatus($vivaStatus){
        $consignmentStatusCodes = Tracking::$oneworld_consignment_code_mapping;
        return isset($consignmentStatusCodes[$vivaStatus]) ? $consignmentStatusCodes[$vivaStatus] : 0;
    }
}
