<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of YodelTrackingStatus
 *
 * @author kiran.iftikhar
 */
class WnDirectTrackingStatus {
    
    public function __construct() {
        
    }
    
    public static $wndirect_status_code = array( 
        '1' => 'Awaiting',
        '2' => 'Despatched',
        '3' => 'Not yet received by carrier',
        '4' => 'Received by carrier',
        '5' => 'Recd by carrier - no elec advice',
        '6' => 'Collection request recd by carrier',
        '7' => 'Collection made',
        '8' => 'Collection Failed',
        '9' => 'Misroute',
        '10' => 'Carrier delays',
        '11' => 'Parcel Lost',
        '12' => 'Delayed (not Carrier)',
        '13' => 'Held by HM Customs',
        '14' => 'Parcel Damaged',
        '15' => 'In transit',
        '16' => 'Local Collect at PO',
        '17' => 'Sub contractor event',
        '18' => 'Out for delivery',
        '19' => 'Sub-contractor received',
        '20' => 'Address query',
        '21' => 'Recipient Carded',
        '22' => 'Delivered in part',
        '23' => 'Customer to collect from carrier',
        '24' => 'Held by carrier',
        '25' => 'Customer moved',
        '26' => 'Refused by customer',
        '27' => 'Return to sender',
        '28' => 'Non delivery',
        '29' => 'Delivered',
        '30' => 'Information',
        '31' => 'Post transit status',
        '32' => 'SDIs apply',
        '33' => 'Cancelled',
        '34' => 'Elec Advice recd by carrier',
        '35' => 'Closed by system',
        '36' => 'Mis sort by carrier',
        '37' => 'Delivery Arranged with recipient',
        '38' => 'No access to recipients address',
        '39' => 'COD amount not paid',
        '40' => 'Customer Identification failed',
        '41' => 'Invalid method of payment',
        '42' => 'COD amount paid',
        '43' => 'Customs cleared',
        '44' => 'Package repacked',
        '45' => 'Package disposed',
        '46' => 'Declared weight not correct',
        '47' => 'Held by import customs',
        '48' => 'Held by export customs',
        '49' => 'Delivered to neighbour',
        '50' => 'Delivered - specified safe place',
        '51' => 'Parcel collected from store',
        '52' => 'Awaiting collection from store',
        '53' => 'Not collected from store (shopper notified)',
        '54' => 'Delivered to locker/collection point',
        '55' => 'Delivered to alternate delivery point',
        '56' => 'Held by carrier for clearance preprocessing',
        '57' => 'Package over-labelled',
        '58' => 'Package outside of service capability',
        '59' => 'Parcel update notification via SMS',
        '60' => 'Parcel update notification via Email',
        '61' => 'Attempted delivery'           
    );
 
    public static $consignment_status_code = array(
        '1' => Consignment::STATUS_INTRANSIT,
        '2' => Consignment::STATUS_DISPATCHED,
        '3' => Consignment::STATUS_LABEL_CREATED,
        '4' => Consignment::STATUS_INTRANSIT,
        '5' => Consignment::STATUS_INTRANSIT,
        '6' => Consignment::STATUS_INTRANSIT,
        '7' => Consignment::STATUS_INTRANSIT,
        '8' => Consignment::STATUS_PROBLEM,
        '9' => Consignment::STATUS_PROBLEM,
        '10' => Consignment::STATUS_INTRANSIT,
        '11' => Consignment::STATUS_PROBLEM,
        '12' => Consignment::STATUS_INTRANSIT,
        '13' => Consignment::STATUS_INTRANSIT,
        '14' => Consignment::STATUS_PROBLEM,
        '15' => Consignment::STATUS_INTRANSIT,
        '16' => Consignment::STATUS_INTRANSIT,
        '17' => Consignment::STATUS_INTRANSIT,
        '18' => Consignment::STATUS_INTRANSIT,
        '19' => Consignment::STATUS_INTRANSIT,
        '20' => Consignment::STATUS_INTRANSIT,
        '21' => Consignment::STATUS_INTRANSIT,
        '22' => Consignment::STATUS_INTRANSIT,
        '23' => Consignment::STATUS_INTRANSIT,
        '24' => Consignment::STATUS_HOLD,
        '25' => Consignment::STATUS_INTRANSIT,
        '26' => Consignment::STATUS_PROBLEM,
        '27' => Consignment::STATUS_RETURNED,
        '28' => Consignment::STATUS_PROBLEM,
        '29' => Consignment::STATUS_DELIVERED,
        '30' => Consignment::STATUS_INTRANSIT,
        '31' => Consignment::STATUS_INTRANSIT,
        '32' => Consignment::STATUS_INTRANSIT,
        '33' => Consignment::STATUS_CANCELLED,
        '34' => Consignment::STATUS_INTRANSIT,
        '35' => Consignment::STATUS_CLOSE,
        '36' => Consignment::STATUS_PROBLEM,
        '37' => Consignment::STATUS_INTRANSIT,
        '38' => Consignment::STATUS_PROBLEM,
        '39' => Consignment::STATUS_PROBLEM,
        '40' => Consignment::STATUS_PROBLEM,
        '41' => Consignment::STATUS_PROBLEM,
        '42' => Consignment::STATUS_INTRANSIT,
        '43' => Consignment::STATUS_INTRANSIT,
        '44' => Consignment::STATUS_INTRANSIT,
        '45' => Consignment::STATUS_CANCELLED,
        '46' => Consignment::STATUS_PROBLEM,
        '47' => Consignment::STATUS_HOLD,
        '48' => Consignment::STATUS_HOLD,
        '49' => Consignment::STATUS_DELIVERED,
        '50' => Consignment::STATUS_DELIVERED,
        '51' => Consignment::STATUS_INTRANSIT,
        '52' => Consignment::STATUS_INTRANSIT,
        '53' => Consignment::STATUS_INTRANSIT,
        '54' => Consignment::STATUS_DELIVERED,
        '55' => Consignment::STATUS_DELIVERED,
        '56' => Consignment::STATUS_HOLD,
        '57' => Consignment::STATUS_PROBLEM,
        '58' => Consignment::STATUS_PROBLEM,
        '59' => Consignment::STATUS_INTRANSIT,
        '60' => Consignment::STATUS_INTRANSIT,
        '61' => Consignment::STATUS_INTRANSIT          
    );

    public static $oneworld_wndirect = array(        
        '1' => 113,
        '2' => 126,
        '3' => 120,
        '4' => 137,
        '5' => 137,
        '6' => 114,
        '7' => 114,
        '8' => 115,
        '9' => 115,
        '10' => 120,
        '11' => 115,
        '12' => 120,
        '13' => 128,
        '14' => 119,
        '15' => 137,
        '16' => 137,
        '17' => 137,
        '18' => 111,
        '19' => 137,
        '20' => 112,
        '21' => 137,
        '22' => 147,
        '23' => 137,
        '24' => 128,
        '25' => 115,
        '26' => 115,
        '27' => 143,
        
        '28' => 115,
        '30' => 137,
        '31' => 137,
        '32' => 137,
        '33' => 127,
        '34' => 144,
        '35' => 137,
        '36' => 115,
        '37' => 137,
        '38' => 112,
        '39' => 115,
        '40' => 127,
        '41' => 115,
        '42' => 137,
        '43' => 117,
        '44' => 137,
        '45' => 119,
        '46' => 115,
        '47' => 117,
        '48' => 117,        
        '51' => 140,
        '52' => 137,
        '53' => 138,
        '49' => 121,
        '50' => 121,
        '54' => 121,
        '55' => 121,
        '29' => 121,
        '56' => 128,
        '57' => 137,
        '58' => 115,
        '59' => 137,
        '60' => 137,
        '61' => 123

    );
    public static function getOweStatusCode($wndirectStatus){
        $wndirectTrackingStatus = self::$oneworld_wndirect;
        return isset($wndirectTrackingStatus[$wndirectStatus]) ? $wndirectTrackingStatus[$wndirectStatus] : 0;
    }
    public static function getConsignmentStatus($wndirectStatus){
        $consignmentStatusCodes = Tracking::$oneworld_consignment_code_mapping;
        return isset($consignmentStatusCodes[$wndirectStatus]) ? $consignmentStatusCodes[$wndirectStatus] : 0;
    }
}
