<?php

////////////////////////////////////////////////////
//
// Class for dealing with Baskets
//
////////////////////////////////////////////////////

/**
 * Basket - Basket class
 * @package Ecommerce
 */
class Basket extends DbAccess3
{
	protected $discount;
	protected $offer_code;
	protected $order_id;
	protected $customer_id;
	protected $billing_address_id;
	protected $delivery_address_id;
	protected $contact_name;
	protected $email_address;
	protected $telephone;
	protected $order_reference;
	protected $vendor_transaction_code;

	protected $orderq;
	protected $active;
	protected $deletedq;
	protected $added_on;
	protected $added_by;
	protected $changed_on;
	protected $changed_by;

	private $basketItems = null;
	private $parcelGroups = null;
	private $billingAddress = null;
	private $vat_total = -1;

	/**
	 * Constructor. Returns the object.
	 * @param int $id
	 * @return obj
	 */
	public function __construct($id=0)
	{

		$this->tablename = 'baskets';
		$this->pkey	 = 'id';
		$this->fields	=
		array( 'discount'                => 'discount',
				'offer_code'             => 'offer_code',
				'order_id'               => 'order_id',
				'customer_id'            => 'customer_id',
				'billing_address_id'     => 'billing_address_id',
				'delivery_address_id'    => 'delivery_address_id',
				'email_address'          => 'email_address',
				'contact_name'           => 'contact_name',
				'telephone'              => 'telephone',
				'order_reference'        => 'order_reference',
				'orderq'                 => 'orderq',
				'active'                 => 'active',
				'deletedq'               => 'deletedq',
				'vendor_transaction_code' => 'vendor_transaction_code',

				'added_on'               => 'added_on',
				'added_by'               => 'added_by',
				'changed_on'             => 'changed_on',
				'changed_by'             => 'changed_by'
				);

		// construct object
		$this->_construct($id);

		return $this;
	}

	/**
	 * Get list of baskets, that have parcel groups that
	 * have booking that need to be made
	 *
	 */
	public static function getBasketsForBatch()
	{
		$sql = "SELECT bi.basket_id
				FROM basket_items bi
				LEFT JOIN parcel_groups pg on bi.parcel_group_id=pg.id
				WHERE (pg.booking_status=" . Parcelgroup::BOOKING_STATUS_READY . ")
				";

		$sql = "SELECT b.*
				FROM baskets b
				LEFT JOIN orders o on b.order_id=o.id
				WHERE b.order_id > 0 and o.order_status=" . Order::STATUS_COMPLETE . "
				AND b.id in ($sql)
				";
		t($sql);

		return self::getObjectList("Basket", $sql);
	}

	/**
	 * Factory method to get basket for transaction code
	 * generated by this class.
	 * Returns null if basket cannot be found.
	 *
	 * @param string $transaction
	 * @return Basket
	 */
	public static function getBasketForClientTransaction($transaction)
	{
		$where = "vendor_transaction_code ='"  . DbAccess3::escape($transaction) . "'";

		$list = self::getAnyBasket($where);
		//
		if (sizeof($list) == 0) return null;

		//
		return $list[0];
	}

	////////////////////////////////////////////////////
	// Access and update methods
	////////////////////////////////////////////////////

	/**
	 * getAnyBasket. Returns the object array of Baskets.
	 * @param string $where
	 * @param string $activeOnly
	 * @param string $orderBy
	 * @return string
	 */
	public static function getAnyBasket($where = "", $activeOnly = true, $orderBy = "id")
	{
		$basket = new Basket();
		$ret = array();
		$ids = $basket->getAnyBasketIds($where, $activeOnly, $orderBy);

		if (count($ids)>0)
		{
			foreach ($ids as $i)
			{
				$ret[] = new Basket($i);
			}
			return $ret;
		}
		else return $ret;
	}

	/**
	 * getAnyBasketIds. Returns the object array of Basket ids.
	 * @param string $where
	 * @param string $activeOnly
	 * @param string $orderBy
	 * @return string
	 */
	public function getAnyBasketIds($where = "", $activeOnly = true, $orderBy = "id")
	{
		$ret	 = array();
		$whereSql = "WHERE deletedq <> 'Y' ";

		if ($where)	 $whereSql .= " AND $where";
		if ($activeOnly) $whereSql .= " AND active=1";
		 $sql = "SELECT {$this->pkey}
				 FROM {$this->tablename}
						 $whereSql
			 ORDER BY $orderBy";

		//echo "<p>$sql</p>";

		$result = Db::query($sql);
		while (list($pId) = mysqli_fetch_row($result))
		{
			$ret[] = $pId;
		}

		return $ret;
	}



	/**
	 * updateCustomerId. Updates row with customer id
	 * @return void
	 */
	public function updateCustomerId()
	{

		$sql = "UPDATE {$this->tablename}
				 SET {$this->fields['customer_id']} = '$this->customer_id'
				 WHERE {$this->pkey} = '{$this->id}'";
		$result = Db::query($sql);
		return;

	}

	/**
	 * delete. Updates row as deleted
	 * @return void
	 */
	public function delete()
	{
		$sql = "Delete From Baskets WHERE {$this->pkey} = '{$this->id}'";
		$result = Db::query($sql);
	}

	////////////////////////////////////////////////////
	// main basket processing methods
	////////////////////////////////////////////////////

	/**
	 * createBasket. create a basket
	 * @return int
	 */
	public static function createBasket()
	{
		$BskObj = new Basket;

		// load value object
		$BskObj->id		= NULL;
		$BskObj->discount = NULL;
		$BskObj->offercode = NULL;
		$BskObj->order_id = 0;
		$BskObj->customer_id = 0;

		$BskObj->orderq	= 1;
		$BskObj->active	= 1;
		$BskObj->deletedq = "N";

		// update table
		$BskObj->save();

		return $BskObj;
	}

	/**
	 * addToBasket. add a product and size to the basket
	 * @return void
	 */
	public function addToBasket($parcel_group_id, $quantity_to_add = 1)
	{
		// init vars
		$id				= NULL;

		// get parcel group
		$PgpObj 		= new Parcelgroup($parcel_group_id);

		// get the basket id
		$basket_id 		= $this->getId();

		// basket items object
		$BimObj 		= new Basketitem;

		// check to see whether parcel group is already in the basket
		$where			= " basket_id = " . $basket_id . " and parcel_group_id = " . $PgpObj->getId();
		$basket_items 	= $BimObj->getAnyBasketitem($where);
		$basket_item 	= @$basket_items[0];

		// get id
		if (@$basket_item->id > 0 AND $PgpObj->getId() > 0)
		{
			// increment quantity if a product based parcel group
			if ($PgpObj->getProductId() > 0)
			{
				$quantity_to_add = $basket_item->getQuantity() + 1;
			}

			$id = $basket_item->getId();
		}
		else
		{
			$id = 0;
		}

		// create/update basket item
		$BimObj->setId($id);
		$BimObj->setBasketId($basket_id);
		$BimObj->setParcelGroupId($PgpObj->getId());
		$BimObj->setQuantity($quantity_to_add);
		$BimObj->setDiscount(0);
		$BimObj->setActive(1);
		$BimObj->setDeleted("N");
		$BimObj->save();

	}

	/**
	 * getBasket. get the basket contents
	 * @return array
	 */
	public function getBasketItems()
	{
		// If basket is empty get the basket
		if ($this->basketItems == null)
		{
			// get basket items
			$BimObj	 = new Basketitem;
			$where		= " basket_id = " . $this->getId();
			$this->basketItems= $BimObj->getAnyBasketitem($where);
		}
		return $this->basketItems;
	}

	/**
	 * Get list of parcel groups for this basket.
	 *
	 */
	public function getParcelGroups()
	{
		return ParcelGroup::getParcelGroupListFromBasketId($this->id);
	}

	/**
	 * getBasketByOrderId. get the basket by order id
	 * @return array
	 */
	public function getBasketByOrderId()
	{
		// only pick up baskets that are orders
		if ($this->getOrderId() == 0) return;

		// get basket items
		$where = " order_id = " . $this->getOrderId();
		$basket = $this->getAnyBasketIds($where);

		// if no basket found, exit
		if (!isset($basket[0])) return;

		return $basket[0];

	}

	/**
	 * updateRow. update a basket row
	 * @return string
	 */
	public function updateRow($id, $quantity)
	{
		$BdetObj = new Basketitem($id);

		if ($quantity > 0)
		{
			$BdetObj->updateQuantity($quantity);
		}
		else
		{
			$BdetObj->delete();
		}
	}

	/**
	 * hasPackaging. does this basket have packaging
	 * @return boolean
	 */
	public function hasPackaging()
	{
		$basket_items = $this->getBasketItems();

		foreach ($basket_items as $basket_item)
		{
			if ($basket_item->getParcelGroup()->getProductId() != 0)
			{
				return true;
			}
		}

		return false;
	}

	/**
	 * Has packages - does this basket contain any parcel groups
	 * @return boolean
	 */
	public function hasParcelGroups()
	{
		$basket_items = $this->getBasketItems();
		foreach ($basket_items as $basket_item)
		{
			if ($basket_item->getParcelGroup()->getProductId() == 0)
			{
				return true;
			}
		}
		return false;
	}

	public function addDeliveryAddress()
	{
		// add the delivery address to the order address table
		$OadObj = new ParcelGroupAddress();
		$OadObj->setBasketId($this->getId());
		$OadObj->setType('D');
		$OadObj->setFullname($CusObj->getFullname());
		$OadObj->setAddress1(Sessionmanager::getDelAddr1());
		$OadObj->setAddress2(Sessionmanager::getDelAddr2());
		$OadObj->setAddress3(Sessionmanager::getDelAddr3());
		$OadObj->setTown(Sessionmanager::getDelTown());
		$OadObj->setRegion(Sessionmanager::getDelRegion());
		$OadObj->setPostcode(Sessionmanager::getDelPostcode());
		$OadObj->setActive(1);
		$OadObj->setDeleted('N');
		$OadObj->save();

		// update the delivery address id
		$this->setDeliveryAddressId($this->getId());
		$this->updateDelAddress();

	}


	/**
	 * updateDelAddress. Updates delivery address
	 * @return void
	 */
	public function updateDelAddress()
	{

		$sql = "UPDATE {$this->tablename}
				 SET {$this->fields['delivery_address_id']} = '" . $this->getDeliveryAddressId() . "'
				 WHERE {$this->pkey} = '{$this->id}'";
		$result = Db::query($sql);
		return;

	}

	/**
	 * Email address for person who owns this basket
	 *
	 * @return string
	 */
	public function getEmailAddress ()	 { return $this->email_address; }
	public function setEmailAddress ($email) { $this->email_address = $email; }

	/**
	 * Get Customer name who owns this basket.
	 *
	 * @return string
	 */
	public function getCustomerName() { return $this->contact_name; }
	public function setCustomerName($contact_name) { $this->contact_name = $contact_name; }

	/**
	 * Get phone number of person who owns this basket.
	 *
	 * @return string
	 */
	public function getPhoneNumber() { return $this->telephone; }
	public function setPhoneNumber($phone_number) { $this->telephone = $phone_number; }

	/**
	 * Order reference entered by customers
	 *
	 * @return string
	 */
	public function getOrderReference() { return $this->order_reference; }
	public function setOrderReference ($order_reference) { $this->order_reference = $order_reference; }

	/**
	 * Shipping cost is not stored until customer makes an order.
	 * This will return the default shipping cost if any of the items
	 * in the basket are products
	 *
	 * @param boolean $formatted
	 */
	public function getShippingCost($formatted = false)
	{
		$cost = 0;
		// charge default passed if there are any products in the database.
		foreach ($this->getParcelGroups() as $parcelGroup)
		{
			if ($parcelGroup->getProductId() > 0)
			{
				$cost = CONFIG_SHIPPING_COST;
				break;
			}
		}
		//
		return ($formatted ? util_money($cost) : $cost);
	}



	////////////////////////////////////////////////////
	// Getters
	////////////////////////////////////////////////////

	// specific getters
	public function getId()					 {	 return $this->id; }
	public function getDiscount()			 {	 return $this->discount; }
	public function getOfferId()				{	 return $this->offer_id; }
	public function getOrderId()				{	 return $this->order_id; }
	public function getCustomerId()			 {	 return $this->customer_id; }
	public function getDeliveryAddressId()	 {	 return $this->delivery_address_id; }
	public function getDeliveryAddress()		{	 return new ParcelGroupAddress($this->getDeliveryAddressId()); }

	// general and audit getters
	public function getRowOrder()			 {	 return $this->orderq; }
	public function getActive()				 {	 return $this->active; }
	public function getDeleted()				{	 return $this->deletedq; }
	public function getAddedOn()				{	 return $this->added_on; }
	public function getAddedBy()				{	 return $this->added_by; }
	public function getChangedOn()			 {	 return $this->changed_on; }
	public function getChangedBy()			 {	 return $this->changed_by; }

	// special getters
	public function getBasketAmount($include_vat = false, $formatted = false)
	{

		$total = 0;

		$BimObj = new Basketitem;
		$where = "basket_id = " . $this->getId();
		$items = $BimObj->getAnyBasketitem($where);

		// calculate vat (to avoid rounding errors, read vat from the basket items)
		$this->vat_total = 0;

		foreach ($items as $item)
		{
			// get parcel group
			$PgpObj = new Parcelgroup($item->getParcelGroupId());

			// for booking parcel groups
			$total += $PgpObj->getTotalPrice() - $PgpObj->getDiscount();

			$this->vat_total += $PgpObj->getVAT();
		}

		if ($include_vat)
		{
			$total += $this->vat_total;
		}

		return ($formatted ? util_money($total) : $total);

	}

	public function getBasketVAT($formatted = false)
	{
		if ($this->vat_total < 0) // If not yet set
		{
			// this forces VAT to be calculate for the basket!!
			$this->getBasketAmount();
		}
		return ($formatted ? util_money($this->vat_total) : $this->vat_total);
	}

	/**
	 * Includes the cost of items in the basket, plus the shipping cost (which is passed in).
	 * Does not include VAT!
	 *
	 * @param bool $formatted
	 */
	public function getBasketTotalAmount($formatted = false)
	{
		$total = 0;
		$total = $this->getBasketAmount(false) + $this->getShippingCost();
		return ($formatted ? util_money($total) : $total);
	}

	public function getBasketTotalAmountPlusVat($formatted = false)
	{
		$total = $this->getBasketTotalAmount(false) + $this->getBasketVAT();
		return ($formatted ? util_money($total) : $total);
	}

	/**
	 * Gets the number of items in the basekt.
	 * Or if flag set, gives number of parcels saved in basket
	 *
	 * @param bool $parcels_only_flag
	 * @return number
	 */
	public function getBasketCount($parcels_only_flag = true)
	{
		// Only count parcels
		if ($parcels_only_flag)
		{
			$sql = "SELECT COUNT(b.id)
					FROM basket_items b
					LEFT JOIN parcel_groups pg on b.parcel_group_id=pg.id
					WHERE pg.product_id=0
					AND b.basket_id=" . $this->getId();

	    	$rs = Db::query($sql);
			{
	    		if(($row = mysqli_fetch_row($rs))) return $row[0];
	    	}
		}
		else
		{
			$BimObj = new Basketitem;
			$where	= " basket_id = " . $this->getId();
			return $BimObj->rowsCount($where);
		}

	}

	public function getMiniBasketSummary()
	{
		return $this->getBasketCount() . " items. Cost: " . $this->getBasketAmount(true, true);
	}

	/**
	 * Get the billing address for this basket
	 *
	 */
	public function getBillingAddress()
	{
		if ($this->billingAddress == null)
		{
			$this->billingAddress = new ParcelGroupAddress(intval($this->billing_address_id));
		}
		return $this->billingAddress;
	}

	/**
	 * Set the billing address for this basket
	 *
	 * @param unknown_type $addressId
	 */
	public function setBillingAddressId($addressId)
	{
		$this->billing_address_id = $addressId;
		$this->billingAddress = null;
	}

	/**
	 * Generates a transaction code that is guarenteed to be unique.
	 * old - generateTransactionCode
	 *
	 * @return string
	 */
	public function getVendorTransactionCode($renew_flag = false)
	{
		if (($this->vendor_transaction_code == "") || $renew_flag)
		{
			$this->vendor_transaction_code = $this->getId() . "-";
			// get seconds from 1970
			$this->vendor_transaction_code .= time();

			// Update in the database.
			$sql = "UPDATE baskets set vendor_transaction_code='" . $this->vendor_transaction_code . "'
					WHERE id=" . intval($this->getId());
			Db::query($sql);
		}
		//
		return $this->vendor_transaction_code;
	}

	////////////////////////////////////////////////////
	// Setters
	////////////////////////////////////////////////////

	// specific setters
	public function setId($id)	 			{	 $this->id = $id; }
	public function setDiscount($discount)	 {	 $this->discount = $discount; }
	public function setOfferId($offer_id)	 {	 $this->offer_id = $offer_id; }
	public function setOrderId($order_id)	 {	 $this->order_id = $order_id; }
	public function setCustomerId($customer_id) {	 $this->customer_id = $customer_id; }
	public function setDeliveryAddressId($delivery_address_id)
	{
		$this->delivery_address_id = $delivery_address_id;
	}

	// general and audit setters
	public function setRowOrder($order)		 {	 $this->orderq = $order; }
	public function setActive($active)		 {	 $this->active = $active; }
	public function setDeleted($deleted)		{	 $this->deletedq = $deleted; }
	public function setAddedOn($added_on)	 {	 $this->added_on = added_on; }
	public function setAddedBy($added_by)	 {	 $this->added_by = added_by; }
	public function setChangedOn($changed_on) {	 $this->changed_on = changed_on; }
	public function setChangedBy($changed_by) {	 $this->changed_by = changed_by; }

}
?>
