<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ConsignmentChargesTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('consignment_charges_types')->delete();
        
        \DB::table('consignment_charges_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Basic Charges',
                'charges_key' => 'BASIC_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Fuel Charges',
                'charges_key' => 'FUEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-03-05 17:31:05',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Additional Charges',
                'charges_key' => 'ADDITIONAL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:26',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'On Forward Charges',
                'charges_key' => 'ON_FORWARD_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-05-16 15:11:46',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'NDX',
                'charges_key' => 'NDX',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            5 => 
            array (
                'id' => 6,
                'title' => 'DDP',
                'charges_key' => 'DDP',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            6 => 
            array (
                'id' => 7,
                'title' => 'H/V',
                'charges_key' => 'H_V',
                'charge_type' => 'customer',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:15',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            7 => 
            array (
                'id' => 8,
                'title' => 'Remote Area Charges',
                'charges_key' => 'REMOTE_AREA_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:42',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            8 => 
            array (
                'id' => 9,
                'title' => 'Handling Charges',
                'charges_key' => 'HANDLING_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 19:35:21',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            9 => 
            array (
                'id' => 10,
                'title' => 'Reference',
                'charges_key' => 'REFERENCE',
                'charge_type' => 'agent',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            10 => 
            array (
                'id' => 11,
                'title' => 'Linehaul',
                'charges_key' => 'LINEHAUL',
                'charge_type' => 'agent',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            11 => 
            array (
                'id' => 12,
                'title' => 'Address Correction',
                'charges_key' => 'ADDRESS_CORRECTION',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            12 => 
            array (
                'id' => 14,
                'title' => 'Airline Handling',
                'charges_key' => 'AIRLINE_HANDLING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            13 => 
            array (
                'id' => 15,
                'title' => 'Clearance',
                'charges_key' => 'CLEARANCE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            14 => 
            array (
                'id' => 16,
                'title' => 'Collections',
                'charges_key' => 'COLLECTIONS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            15 => 
            array (
                'id' => 17,
                'title' => 'DDP Admin Fee',
                'charges_key' => 'DDP_ADMIN_FEE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            16 => 
            array (
                'id' => 18,
                'title' => 'DDP Charge',
                'charges_key' => 'DDP_CHARGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            17 => 
            array (
                'id' => 19,
                'title' => 'Delivery',
                'charges_key' => 'DELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            18 => 
            array (
                'id' => 20,
                'title' => 'Dispatch',
                'charges_key' => 'DISPATCH',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            19 => 
            array (
                'id' => 21,
                'title' => 'Labour',
                'charges_key' => 'LABOUR',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:24',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            20 => 
            array (
                'id' => 22,
                'title' => 'Other',
                'charges_key' => 'OTHER',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            21 => 
            array (
                'id' => 23,
                'title' => 'Out of gauge',
                'charges_key' => 'OUT_OF_GAUGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-15 00:28:06',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            22 => 
            array (
                'id' => 24,
                'title' => 'Over Weight',
                'charges_key' => 'OVER_WEIGHT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            23 => 
            array (
                'id' => 25,
                'title' => 'RAS',
                'charges_key' => 'RAS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            24 => 
            array (
                'id' => 26,
                'title' => 'Redelivery',
                'charges_key' => 'REDELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:39',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            25 => 
            array (
                'id' => 27,
                'title' => 'Label Charges',
                'charges_key' => 'LABEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:07:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            26 => 
            array (
                'id' => 28,
                'title' => 'VAT',
                'charges_key' => 'VAT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            27 => 
            array (
                'id' => 29,
                'title' => 'Discount',
                'charges_key' => 'DISCOUNT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 18:28:42',
                'updated_by' => 58,
                'updated_date' => '2018-11-28 18:39:53',
            ),
            28 => 
            array (
                'id' => 30,
                'title' => 'Test Charges1243',
                'charges_key' => 'TEST_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 1,
                'added_by' => 0,
                'added_date' => '2019-11-20 16:34:40',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'title' => 'mobile tracking',
                'charges_key' => 'MOBILE_TRACKING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 0,
                'added_date' => '2019-11-20 17:12:30',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            30 => 
            array (
                'id' => 1,
                'title' => 'Basic Charges',
                'charges_key' => 'BASIC_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            31 => 
            array (
                'id' => 2,
                'title' => 'Fuel Charges',
                'charges_key' => 'FUEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-03-05 17:31:05',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            32 => 
            array (
                'id' => 3,
                'title' => 'Additional Charges',
                'charges_key' => 'ADDITIONAL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:26',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            33 => 
            array (
                'id' => 4,
                'title' => 'On Forward Charges',
                'charges_key' => 'ON_FORWARD_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-05-16 15:11:46',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            34 => 
            array (
                'id' => 5,
                'title' => 'NDX',
                'charges_key' => 'NDX',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            35 => 
            array (
                'id' => 6,
                'title' => 'DDP',
                'charges_key' => 'DDP',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            36 => 
            array (
                'id' => 7,
                'title' => 'H/V',
                'charges_key' => 'H_V',
                'charge_type' => 'customer',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:15',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            37 => 
            array (
                'id' => 8,
                'title' => 'Remote Area Charges',
                'charges_key' => 'REMOTE_AREA_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:42',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            38 => 
            array (
                'id' => 9,
                'title' => 'Handling Charges',
                'charges_key' => 'HANDLING_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 19:35:21',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            39 => 
            array (
                'id' => 10,
                'title' => 'Reference',
                'charges_key' => 'REFERENCE',
                'charge_type' => 'agent',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            40 => 
            array (
                'id' => 11,
                'title' => 'Linehaul',
                'charges_key' => 'LINEHAUL',
                'charge_type' => 'agent',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            41 => 
            array (
                'id' => 12,
                'title' => 'Address Correction',
                'charges_key' => 'ADDRESS_CORRECTION',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            42 => 
            array (
                'id' => 14,
                'title' => 'Airline Handling',
                'charges_key' => 'AIRLINE_HANDLING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            43 => 
            array (
                'id' => 15,
                'title' => 'Clearance',
                'charges_key' => 'CLEARANCE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            44 => 
            array (
                'id' => 16,
                'title' => 'Collections',
                'charges_key' => 'COLLECTIONS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            45 => 
            array (
                'id' => 17,
                'title' => 'DDP Admin Fee',
                'charges_key' => 'DDP_ADMIN_FEE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            46 => 
            array (
                'id' => 18,
                'title' => 'DDP Charge',
                'charges_key' => 'DDP_CHARGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            47 => 
            array (
                'id' => 19,
                'title' => 'Delivery',
                'charges_key' => 'DELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            48 => 
            array (
                'id' => 20,
                'title' => 'Dispatch',
                'charges_key' => 'DISPATCH',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            49 => 
            array (
                'id' => 21,
                'title' => 'Labour',
                'charges_key' => 'LABOUR',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:24',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            50 => 
            array (
                'id' => 22,
                'title' => 'Other',
                'charges_key' => 'OTHER',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            51 => 
            array (
                'id' => 23,
                'title' => 'Out of gauge',
                'charges_key' => 'OUT_OF_GAUGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-15 00:28:06',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            52 => 
            array (
                'id' => 24,
                'title' => 'Over Weight',
                'charges_key' => 'OVER_WEIGHT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            53 => 
            array (
                'id' => 25,
                'title' => 'RAS',
                'charges_key' => 'RAS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            54 => 
            array (
                'id' => 26,
                'title' => 'Redelivery',
                'charges_key' => 'REDELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:39',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            55 => 
            array (
                'id' => 27,
                'title' => 'Label Charges',
                'charges_key' => 'LABEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:07:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            56 => 
            array (
                'id' => 28,
                'title' => 'VAT',
                'charges_key' => 'VAT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            57 => 
            array (
                'id' => 29,
                'title' => 'Discount',
                'charges_key' => 'DISCOUNT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 18:28:42',
                'updated_by' => 58,
                'updated_date' => '2018-11-28 18:39:53',
            ),
            58 => 
            array (
                'id' => 30,
                'title' => 'Test Charges1243',
                'charges_key' => 'TEST_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 1,
                'added_by' => 0,
                'added_date' => '2019-11-20 16:34:40',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            59 => 
            array (
                'id' => 31,
                'title' => 'mobile tracking',
                'charges_key' => 'MOBILE_TRACKING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 0,
                'added_date' => '2019-11-20 17:12:30',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            60 => 
            array (
                'id' => 1,
                'title' => 'Basic Charges',
                'charges_key' => 'BASIC_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            61 => 
            array (
                'id' => 2,
                'title' => 'Fuel Charges',
                'charges_key' => 'FUEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-03-05 17:31:05',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            62 => 
            array (
                'id' => 3,
                'title' => 'Additional Charges',
                'charges_key' => 'ADDITIONAL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:26',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            63 => 
            array (
                'id' => 4,
                'title' => 'On Forward Charges',
                'charges_key' => 'ON_FORWARD_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-05-16 15:11:46',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            64 => 
            array (
                'id' => 5,
                'title' => 'NDX',
                'charges_key' => 'NDX',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            65 => 
            array (
                'id' => 6,
                'title' => 'DDP',
                'charges_key' => 'DDP',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            66 => 
            array (
                'id' => 7,
                'title' => 'H/V',
                'charges_key' => 'H_V',
                'charge_type' => 'customer',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:15',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            67 => 
            array (
                'id' => 8,
                'title' => 'Remote Area Charges',
                'charges_key' => 'REMOTE_AREA_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:42',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            68 => 
            array (
                'id' => 9,
                'title' => 'Handling Charges',
                'charges_key' => 'HANDLING_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 19:35:21',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            69 => 
            array (
                'id' => 10,
                'title' => 'Reference',
                'charges_key' => 'REFERENCE',
                'charge_type' => 'agent',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            70 => 
            array (
                'id' => 11,
                'title' => 'Linehaul',
                'charges_key' => 'LINEHAUL',
                'charge_type' => 'agent',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            71 => 
            array (
                'id' => 12,
                'title' => 'Address Correction',
                'charges_key' => 'ADDRESS_CORRECTION',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            72 => 
            array (
                'id' => 14,
                'title' => 'Airline Handling',
                'charges_key' => 'AIRLINE_HANDLING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            73 => 
            array (
                'id' => 15,
                'title' => 'Clearance',
                'charges_key' => 'CLEARANCE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            74 => 
            array (
                'id' => 16,
                'title' => 'Collections',
                'charges_key' => 'COLLECTIONS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            75 => 
            array (
                'id' => 17,
                'title' => 'DDP Admin Fee',
                'charges_key' => 'DDP_ADMIN_FEE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            76 => 
            array (
                'id' => 18,
                'title' => 'DDP Charge',
                'charges_key' => 'DDP_CHARGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            77 => 
            array (
                'id' => 19,
                'title' => 'Delivery',
                'charges_key' => 'DELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            78 => 
            array (
                'id' => 20,
                'title' => 'Dispatch',
                'charges_key' => 'DISPATCH',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            79 => 
            array (
                'id' => 21,
                'title' => 'Labour',
                'charges_key' => 'LABOUR',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:24',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            80 => 
            array (
                'id' => 22,
                'title' => 'Other',
                'charges_key' => 'OTHER',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            81 => 
            array (
                'id' => 23,
                'title' => 'Out of gauge',
                'charges_key' => 'OUT_OF_GAUGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-15 00:28:06',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            82 => 
            array (
                'id' => 24,
                'title' => 'Over Weight',
                'charges_key' => 'OVER_WEIGHT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            83 => 
            array (
                'id' => 25,
                'title' => 'RAS',
                'charges_key' => 'RAS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            84 => 
            array (
                'id' => 26,
                'title' => 'Redelivery',
                'charges_key' => 'REDELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:39',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            85 => 
            array (
                'id' => 27,
                'title' => 'Label Charges',
                'charges_key' => 'LABEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:07:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            86 => 
            array (
                'id' => 28,
                'title' => 'VAT',
                'charges_key' => 'VAT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            87 => 
            array (
                'id' => 29,
                'title' => 'Discount',
                'charges_key' => 'DISCOUNT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 18:28:42',
                'updated_by' => 58,
                'updated_date' => '2018-11-28 18:39:53',
            ),
            88 => 
            array (
                'id' => 30,
                'title' => 'Test Charges1243',
                'charges_key' => 'TEST_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 1,
                'added_by' => 0,
                'added_date' => '2019-11-20 16:34:40',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            89 => 
            array (
                'id' => 31,
                'title' => 'mobile tracking',
                'charges_key' => 'MOBILE_TRACKING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 0,
                'added_date' => '2019-11-20 17:12:30',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            90 => 
            array (
                'id' => 1,
                'title' => 'Basic Charges',
                'charges_key' => 'BASIC_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            91 => 
            array (
                'id' => 2,
                'title' => 'Fuel Charges',
                'charges_key' => 'FUEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-03-05 17:31:05',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            92 => 
            array (
                'id' => 3,
                'title' => 'Additional Charges',
                'charges_key' => 'ADDITIONAL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:26',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            93 => 
            array (
                'id' => 4,
                'title' => 'On Forward Charges',
                'charges_key' => 'ON_FORWARD_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-05-16 15:11:46',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            94 => 
            array (
                'id' => 5,
                'title' => 'NDX',
                'charges_key' => 'NDX',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            95 => 
            array (
                'id' => 6,
                'title' => 'DDP',
                'charges_key' => 'DDP',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            96 => 
            array (
                'id' => 7,
                'title' => 'H/V',
                'charges_key' => 'H_V',
                'charge_type' => 'customer',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:15',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            97 => 
            array (
                'id' => 8,
                'title' => 'Remote Area Charges',
                'charges_key' => 'REMOTE_AREA_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:42',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            98 => 
            array (
                'id' => 9,
                'title' => 'Handling Charges',
                'charges_key' => 'HANDLING_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 19:35:21',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            99 => 
            array (
                'id' => 10,
                'title' => 'Reference',
                'charges_key' => 'REFERENCE',
                'charge_type' => 'agent',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            100 => 
            array (
                'id' => 11,
                'title' => 'Linehaul',
                'charges_key' => 'LINEHAUL',
                'charge_type' => 'agent',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            101 => 
            array (
                'id' => 12,
                'title' => 'Address Correction',
                'charges_key' => 'ADDRESS_CORRECTION',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            102 => 
            array (
                'id' => 14,
                'title' => 'Airline Handling',
                'charges_key' => 'AIRLINE_HANDLING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            103 => 
            array (
                'id' => 15,
                'title' => 'Clearance',
                'charges_key' => 'CLEARANCE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            104 => 
            array (
                'id' => 16,
                'title' => 'Collections',
                'charges_key' => 'COLLECTIONS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            105 => 
            array (
                'id' => 17,
                'title' => 'DDP Admin Fee',
                'charges_key' => 'DDP_ADMIN_FEE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            106 => 
            array (
                'id' => 18,
                'title' => 'DDP Charge',
                'charges_key' => 'DDP_CHARGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            107 => 
            array (
                'id' => 19,
                'title' => 'Delivery',
                'charges_key' => 'DELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            108 => 
            array (
                'id' => 20,
                'title' => 'Dispatch',
                'charges_key' => 'DISPATCH',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            109 => 
            array (
                'id' => 21,
                'title' => 'Labour',
                'charges_key' => 'LABOUR',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:24',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            110 => 
            array (
                'id' => 22,
                'title' => 'Other',
                'charges_key' => 'OTHER',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            111 => 
            array (
                'id' => 23,
                'title' => 'Out of gauge',
                'charges_key' => 'OUT_OF_GAUGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-15 00:28:06',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            112 => 
            array (
                'id' => 24,
                'title' => 'Over Weight',
                'charges_key' => 'OVER_WEIGHT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            113 => 
            array (
                'id' => 25,
                'title' => 'RAS',
                'charges_key' => 'RAS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            114 => 
            array (
                'id' => 26,
                'title' => 'Redelivery',
                'charges_key' => 'REDELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:39',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            115 => 
            array (
                'id' => 27,
                'title' => 'Label Charges',
                'charges_key' => 'LABEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:07:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            116 => 
            array (
                'id' => 28,
                'title' => 'VAT',
                'charges_key' => 'VAT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            117 => 
            array (
                'id' => 29,
                'title' => 'Discount',
                'charges_key' => 'DISCOUNT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 18:28:42',
                'updated_by' => 58,
                'updated_date' => '2018-11-28 18:39:53',
            ),
            118 => 
            array (
                'id' => 30,
                'title' => 'Test Charges1243',
                'charges_key' => 'TEST_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 1,
                'added_by' => 0,
                'added_date' => '2019-11-20 16:34:40',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            119 => 
            array (
                'id' => 31,
                'title' => 'mobile tracking',
                'charges_key' => 'MOBILE_TRACKING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 0,
                'added_date' => '2019-11-20 17:12:30',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            120 => 
            array (
                'id' => 1,
                'title' => 'Basic Charges',
                'charges_key' => 'BASIC_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            121 => 
            array (
                'id' => 2,
                'title' => 'Fuel Charges',
                'charges_key' => 'FUEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-03-05 17:31:05',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            122 => 
            array (
                'id' => 3,
                'title' => 'Additional Charges',
                'charges_key' => 'ADDITIONAL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:26',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            123 => 
            array (
                'id' => 4,
                'title' => 'On Forward Charges',
                'charges_key' => 'ON_FORWARD_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-05-16 15:11:46',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            124 => 
            array (
                'id' => 5,
                'title' => 'NDX',
                'charges_key' => 'NDX',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            125 => 
            array (
                'id' => 6,
                'title' => 'DDP',
                'charges_key' => 'DDP',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            126 => 
            array (
                'id' => 7,
                'title' => 'H/V',
                'charges_key' => 'H_V',
                'charge_type' => 'customer',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:15',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:04:36',
            ),
            127 => 
            array (
                'id' => 8,
                'title' => 'Remote Area Charges',
                'charges_key' => 'REMOTE_AREA_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:06:42',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            128 => 
            array (
                'id' => 9,
                'title' => 'Handling Charges',
                'charges_key' => 'HANDLING_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 19:35:21',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            129 => 
            array (
                'id' => 10,
                'title' => 'Reference',
                'charges_key' => 'REFERENCE',
                'charge_type' => 'agent',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            130 => 
            array (
                'id' => 11,
                'title' => 'Linehaul',
                'charges_key' => 'LINEHAUL',
                'charge_type' => 'agent',
                'apply_per_kg' => 1,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            131 => 
            array (
                'id' => 12,
                'title' => 'Address Correction',
                'charges_key' => 'ADDRESS_CORRECTION',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-10 12:06:57',
            ),
            132 => 
            array (
                'id' => 14,
                'title' => 'Airline Handling',
                'charges_key' => 'AIRLINE_HANDLING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            133 => 
            array (
                'id' => 15,
                'title' => 'Clearance',
                'charges_key' => 'CLEARANCE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            134 => 
            array (
                'id' => 16,
                'title' => 'Collections',
                'charges_key' => 'COLLECTIONS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            135 => 
            array (
                'id' => 17,
                'title' => 'DDP Admin Fee',
                'charges_key' => 'DDP_ADMIN_FEE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            136 => 
            array (
                'id' => 18,
                'title' => 'DDP Charge',
                'charges_key' => 'DDP_CHARGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            137 => 
            array (
                'id' => 19,
                'title' => 'Delivery',
                'charges_key' => 'DELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            138 => 
            array (
                'id' => 20,
                'title' => 'Dispatch',
                'charges_key' => 'DISPATCH',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            139 => 
            array (
                'id' => 21,
                'title' => 'Labour',
                'charges_key' => 'LABOUR',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:24',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            140 => 
            array (
                'id' => 22,
                'title' => 'Other',
                'charges_key' => 'OTHER',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            141 => 
            array (
                'id' => 23,
                'title' => 'Out of gauge',
                'charges_key' => 'OUT_OF_GAUGE',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-15 00:28:06',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            142 => 
            array (
                'id' => 24,
                'title' => 'Over Weight',
                'charges_key' => 'OVER_WEIGHT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            143 => 
            array (
                'id' => 25,
                'title' => 'RAS',
                'charges_key' => 'RAS',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            144 => 
            array (
                'id' => 26,
                'title' => 'Redelivery',
                'charges_key' => 'REDELIVERY',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-12-12 01:41:39',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            145 => 
            array (
                'id' => 27,
                'title' => 'Label Charges',
                'charges_key' => 'LABEL_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-06-25 15:07:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            146 => 
            array (
                'id' => 28,
                'title' => 'VAT',
                'charges_key' => 'VAT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2018-10-18 05:14:01',
                'updated_by' => 58,
                'updated_date' => '2018-05-11 13:33:39',
            ),
            147 => 
            array (
                'id' => 29,
                'title' => 'Discount',
                'charges_key' => 'DISCOUNT',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 0,
                'is_vat' => 0,
                'has_account_default_value' => 1,
                'is_replace_charges' => 1,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 58,
                'added_date' => '2019-09-04 18:28:42',
                'updated_by' => 58,
                'updated_date' => '2018-11-28 18:39:53',
            ),
            148 => 
            array (
                'id' => 30,
                'title' => 'Test Charges1243',
                'charges_key' => 'TEST_CHARGES',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 0,
                'is_delete' => 1,
                'added_by' => 0,
                'added_date' => '2019-11-20 16:34:40',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            149 => 
            array (
                'id' => 31,
                'title' => 'mobile tracking',
                'charges_key' => 'MOBILE_TRACKING',
                'charge_type' => 'both',
                'apply_per_kg' => 0,
                'is_extra_charge' => 1,
                'is_vat' => 0,
                'has_account_default_value' => 0,
                'is_replace_charges' => 0,
                'status' => 1,
                'is_delete' => 0,
                'added_by' => 0,
                'added_date' => '2019-11-20 17:12:30',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
        ));
        
        
    }
}