<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CostTariffsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cost_tariffs')->delete();
        
        \DB::table('cost_tariffs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '1.00',
                'tariff_cost' => '70.00',
                'unit_cost' => '70.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            1 => 
            array (
                'id' => 2,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '1.00',
                'weight_to' => '2.00',
                'tariff_cost' => '80.00',
                'unit_cost' => '80.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            2 => 
            array (
                'id' => 3,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '3.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            3 => 
            array (
                'id' => 4,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '3.00',
                'weight_to' => '4.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            4 => 
            array (
                'id' => 5,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '4.00',
                'weight_to' => '5.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            5 => 
            array (
                'id' => 6,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '5.00',
                'weight_to' => '6.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            6 => 
            array (
                'id' => 7,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '6.00',
                'weight_to' => '7.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            7 => 
            array (
                'id' => 8,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '2.00',
                'tariff_cost' => '23.00',
                'unit_cost' => '23.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:14',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:14',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test',
                'formula' => 'Q * ITMCHR',
            ),
            8 => 
            array (
                'id' => 9,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '5.00',
                'tariff_cost' => '66.00',
                'unit_cost' => '66.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:31',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:31',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test1',
            'formula' => '( Q * ITMCHR ) + ( W * CHRG ) ',
            ),
            9 => 
            array (
                'id' => 10,
                'courier_service_id' => 162,
                'collection_rateband_id' => 1009,
                'destination_rateband_id' => 1010,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '10.00',
                'tariff_cost' => '5.00',
                'unit_cost' => '15.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-02-10 10:48:22',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-02-10 10:48:22',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TEST_TAHIR',
                'formula' => 'Q * ITMCHR',
            ),
            10 => 
            array (
                'id' => 1,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '1.00',
                'tariff_cost' => '70.00',
                'unit_cost' => '70.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            11 => 
            array (
                'id' => 2,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '1.00',
                'weight_to' => '2.00',
                'tariff_cost' => '80.00',
                'unit_cost' => '80.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            12 => 
            array (
                'id' => 3,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '3.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            13 => 
            array (
                'id' => 4,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '3.00',
                'weight_to' => '4.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            14 => 
            array (
                'id' => 5,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '4.00',
                'weight_to' => '5.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            15 => 
            array (
                'id' => 6,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '5.00',
                'weight_to' => '6.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            16 => 
            array (
                'id' => 7,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '6.00',
                'weight_to' => '7.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            17 => 
            array (
                'id' => 8,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '2.00',
                'tariff_cost' => '23.00',
                'unit_cost' => '23.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:14',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:14',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test',
                'formula' => 'Q * ITMCHR',
            ),
            18 => 
            array (
                'id' => 9,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '5.00',
                'tariff_cost' => '66.00',
                'unit_cost' => '66.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:31',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:31',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test1',
            'formula' => '( Q * ITMCHR ) + ( W * CHRG ) ',
            ),
            19 => 
            array (
                'id' => 10,
                'courier_service_id' => 162,
                'collection_rateband_id' => 1009,
                'destination_rateband_id' => 1010,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '10.00',
                'tariff_cost' => '5.00',
                'unit_cost' => '15.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-02-10 10:48:22',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-02-10 10:48:22',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TEST_TAHIR',
                'formula' => 'Q * ITMCHR',
            ),
            20 => 
            array (
                'id' => 1,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '1.00',
                'tariff_cost' => '70.00',
                'unit_cost' => '70.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            21 => 
            array (
                'id' => 2,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '1.00',
                'weight_to' => '2.00',
                'tariff_cost' => '80.00',
                'unit_cost' => '80.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            22 => 
            array (
                'id' => 3,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '3.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            23 => 
            array (
                'id' => 4,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '3.00',
                'weight_to' => '4.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            24 => 
            array (
                'id' => 5,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '4.00',
                'weight_to' => '5.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            25 => 
            array (
                'id' => 6,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '5.00',
                'weight_to' => '6.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            26 => 
            array (
                'id' => 7,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '6.00',
                'weight_to' => '7.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            27 => 
            array (
                'id' => 8,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '2.00',
                'tariff_cost' => '23.00',
                'unit_cost' => '23.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:14',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:14',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test',
                'formula' => 'Q * ITMCHR',
            ),
            28 => 
            array (
                'id' => 9,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '5.00',
                'tariff_cost' => '66.00',
                'unit_cost' => '66.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:31',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:31',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test1',
            'formula' => '( Q * ITMCHR ) + ( W * CHRG ) ',
            ),
            29 => 
            array (
                'id' => 10,
                'courier_service_id' => 162,
                'collection_rateband_id' => 1009,
                'destination_rateband_id' => 1010,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '10.00',
                'tariff_cost' => '5.00',
                'unit_cost' => '15.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-02-10 10:48:22',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-02-10 10:48:22',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TEST_TAHIR',
                'formula' => 'Q * ITMCHR',
            ),
            30 => 
            array (
                'id' => 1,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '1.00',
                'tariff_cost' => '70.00',
                'unit_cost' => '70.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            31 => 
            array (
                'id' => 2,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '1.00',
                'weight_to' => '2.00',
                'tariff_cost' => '80.00',
                'unit_cost' => '80.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            32 => 
            array (
                'id' => 3,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '3.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            33 => 
            array (
                'id' => 4,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '3.00',
                'weight_to' => '4.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            34 => 
            array (
                'id' => 5,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '4.00',
                'weight_to' => '5.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            35 => 
            array (
                'id' => 6,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '5.00',
                'weight_to' => '6.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            36 => 
            array (
                'id' => 7,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '6.00',
                'weight_to' => '7.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            37 => 
            array (
                'id' => 8,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '2.00',
                'tariff_cost' => '23.00',
                'unit_cost' => '23.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:14',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:14',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test',
                'formula' => 'Q * ITMCHR',
            ),
            38 => 
            array (
                'id' => 9,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '5.00',
                'tariff_cost' => '66.00',
                'unit_cost' => '66.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:31',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:31',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test1',
            'formula' => '( Q * ITMCHR ) + ( W * CHRG ) ',
            ),
            39 => 
            array (
                'id' => 10,
                'courier_service_id' => 162,
                'collection_rateband_id' => 1009,
                'destination_rateband_id' => 1010,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '10.00',
                'tariff_cost' => '5.00',
                'unit_cost' => '15.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-02-10 10:48:22',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-02-10 10:48:22',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TEST_TAHIR',
                'formula' => 'Q * ITMCHR',
            ),
            40 => 
            array (
                'id' => 1,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '1.00',
                'tariff_cost' => '70.00',
                'unit_cost' => '70.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            41 => 
            array (
                'id' => 2,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '1.00',
                'weight_to' => '2.00',
                'tariff_cost' => '80.00',
                'unit_cost' => '80.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            42 => 
            array (
                'id' => 3,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '3.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            43 => 
            array (
                'id' => 4,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '3.00',
                'weight_to' => '4.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            44 => 
            array (
                'id' => 5,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '4.00',
                'weight_to' => '5.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            45 => 
            array (
                'id' => 6,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '5.00',
                'weight_to' => '6.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            46 => 
            array (
                'id' => 7,
                'courier_service_id' => 79,
                'collection_rateband_id' => 916,
                'destination_rateband_id' => 916,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '6.00',
                'weight_to' => '7.00',
                'tariff_cost' => '90.00',
                'unit_cost' => '90.00',
                'unit_size' => '1.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-16 04:46:21',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-16 04:46:21',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TESTBYKZ_1',
                'formula' => 'Q * ITMCHR',
            ),
            47 => 
            array (
                'id' => 8,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '2.00',
                'tariff_cost' => '23.00',
                'unit_cost' => '23.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:14',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:14',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test',
                'formula' => 'Q * ITMCHR',
            ),
            48 => 
            array (
                'id' => 9,
                'courier_service_id' => 114,
                'collection_rateband_id' => 987,
                'destination_rateband_id' => 984,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '2.00',
                'weight_to' => '5.00',
                'tariff_cost' => '66.00',
                'unit_cost' => '66.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-01-30 07:27:31',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-01-30 07:27:31',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'test1',
            'formula' => '( Q * ITMCHR ) + ( W * CHRG ) ',
            ),
            49 => 
            array (
                'id' => 10,
                'courier_service_id' => 162,
                'collection_rateband_id' => 1009,
                'destination_rateband_id' => 1010,
                'collection_postcode_group_id' => 0,
                'destination_postcode_group_id' => 0,
                'weight_from' => '0.00',
                'weight_to' => '10.00',
                'tariff_cost' => '5.00',
                'unit_cost' => '15.00',
                'unit_size' => '0.00',
                'active' => 1,
                'deletedq' => 'N',
                'added_on' => '2017-02-10 10:48:22',
                'added_by' => 'ITTEAM',
                'changed_on' => '2017-02-10 10:48:22',
                'changed_by' => 'ITTEAM',
                'tariff_name' => 'TEST_TAHIR',
                'formula' => 'Q * ITMCHR',
            ),
        ));
        
        
    }
}