<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CreditNoteDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('credit_note_details')->delete();
        
        \DB::table('credit_note_details')->insert(array (
            0 => 
            array (
                'id' => 2,
                'credit_note_id' => 2,
                'hawb' => 'Test',
                'date_booked' => '2018-11-25 00:00:00',
                'reference' => 'Test ref',
                'invoice_amount' => '50.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '30.00',
                'description' => '',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-23 19:45:20',
                'updated_by' => 2170,
                'date_updated' => '2018-11-23 13:45:20',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            1 => 
            array (
                'id' => 3,
                'credit_note_id' => 3,
                'hawb' => 'Negative Test Case',
                'date_booked' => '2018-11-30 00:00:00',
                'reference' => 'Test',
                'invoice_amount' => '45.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '25.00',
                'description' => 'Credit to Corporate account but HAWB no given of its child shipment',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-23 19:59:46',
                'updated_by' => 58,
                'date_updated' => '2018-11-23 13:59:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            2 => 
            array (
                'id' => 4,
                'credit_note_id' => 1,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-27 19:22:15',
                'updated_by' => 2170,
                'date_updated' => '2018-11-27 13:22:15',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            3 => 
            array (
                'id' => 6,
                'credit_note_id' => 4,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '30.00',
                'chargeable_amount' => '25.00',
                'credit_amount' => '5.00',
                'description' => '5 GBP is Credited to the Client',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-28 22:20:51',
                'updated_by' => 2170,
                'date_updated' => '2018-11-28 16:20:51',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            4 => 
            array (
                'id' => 7,
                'credit_note_id' => 5,
                'hawb' => '15482573187818',
                'date_booked' => NULL,
                'reference' => 'test_reference',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-01-29 17:20:14',
                'updated_by' => 58,
                'date_updated' => '2019-01-29 11:20:14',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            5 => 
            array (
                'id' => 8,
                'credit_note_id' => 6,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.05',
                'credit_amount' => '0.05',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-13 20:43:55',
                'updated_by' => 2181,
                'date_updated' => '2019-05-13 15:43:55',
                'vat_amount' => '0.00',
                'added_by' => 2181,
            ),
            6 => 
            array (
                'id' => 9,
                'credit_note_id' => 7,
                'hawb' => '1558717530875',
                'date_booked' => '2019-05-29 00:00:00',
                'reference' => 'test_reference',
                'invoice_amount' => '10.02',
                'chargeable_amount' => '9.02',
                'credit_amount' => '1.00',
                'description' => '1 GBP should be credited',
                'is_vatable' => 'YES',
                'date_created' => '2019-05-31 21:51:14',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 16:51:14',
                'vat_amount' => '0.20',
                'added_by' => 58,
            ),
            7 => 
            array (
                'id' => 10,
                'credit_note_id' => 8,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '14.00',
                'chargeable_amount' => '10.00',
                'credit_amount' => '4.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:15:26',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:15:26',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            8 => 
            array (
                'id' => 11,
                'credit_note_id' => 9,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '5.00',
                'chargeable_amount' => '4.00',
                'credit_amount' => '1.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:58:30',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:58:30',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            9 => 
            array (
                'id' => 12,
                'credit_note_id' => 10,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '8.00',
                'credit_amount' => '2.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-10 17:11:58',
                'updated_by' => 58,
                'date_updated' => '2019-06-10 12:11:58',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            10 => 
            array (
                'id' => 13,
                'credit_note_id' => 11,
                'hawb' => '',
                'date_booked' => '2019-06-27 00:00:00',
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-06-27 16:11:56',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:11:56',
                'vat_amount' => '0.36',
                'added_by' => 58,
            ),
            11 => 
            array (
                'id' => 14,
                'credit_note_id' => 12,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-27 16:26:22',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:26:22',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            12 => 
            array (
                'id' => 15,
                'credit_note_id' => 13,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '9.00',
                'credit_amount' => '1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-07-03 16:18:00',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:18:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            13 => 
            array (
                'id' => 16,
                'credit_note_id' => 14,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '-1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-07-03 16:26:02',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:26:02',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            14 => 
            array (
                'id' => 36,
                'credit_note_id' => 16,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-21 18:04:46',
                'updated_by' => 58,
                'date_updated' => '2019-08-21 13:04:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            15 => 
            array (
                'id' => 37,
                'credit_note_id' => 17,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-22 19:25:10',
                'updated_by' => 58,
                'date_updated' => '2019-08-22 14:25:10',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            16 => 
            array (
                'id' => 38,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:57:53',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:57:53',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            17 => 
            array (
                'id' => 39,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:58:36',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:58:36',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            18 => 
            array (
                'id' => 40,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => NULL,
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.00',
                'description' => 'TEST mruga',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 20:00:03',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 15:00:03',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            19 => 
            array (
                'id' => 41,
                'credit_note_id' => 18,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:31:52',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:31:52',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            20 => 
            array (
                'id' => 42,
                'credit_note_id' => 19,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:44:06',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:44:06',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            21 => 
            array (
                'id' => 43,
                'credit_note_id' => 20,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            22 => 
            array (
                'id' => 44,
                'credit_note_id' => 20,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            23 => 
            array (
                'id' => 47,
                'credit_note_id' => 21,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            24 => 
            array (
                'id' => 48,
                'credit_note_id' => 21,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            25 => 
            array (
                'id' => 2,
                'credit_note_id' => 2,
                'hawb' => 'Test',
                'date_booked' => '2018-11-25 00:00:00',
                'reference' => 'Test ref',
                'invoice_amount' => '50.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '30.00',
                'description' => '',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-23 19:45:20',
                'updated_by' => 2170,
                'date_updated' => '2018-11-23 13:45:20',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            26 => 
            array (
                'id' => 3,
                'credit_note_id' => 3,
                'hawb' => 'Negative Test Case',
                'date_booked' => '2018-11-30 00:00:00',
                'reference' => 'Test',
                'invoice_amount' => '45.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '25.00',
                'description' => 'Credit to Corporate account but HAWB no given of its child shipment',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-23 19:59:46',
                'updated_by' => 58,
                'date_updated' => '2018-11-23 13:59:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            27 => 
            array (
                'id' => 4,
                'credit_note_id' => 1,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-27 19:22:15',
                'updated_by' => 2170,
                'date_updated' => '2018-11-27 13:22:15',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            28 => 
            array (
                'id' => 6,
                'credit_note_id' => 4,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '30.00',
                'chargeable_amount' => '25.00',
                'credit_amount' => '5.00',
                'description' => '5 GBP is Credited to the Client',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-28 22:20:51',
                'updated_by' => 2170,
                'date_updated' => '2018-11-28 16:20:51',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            29 => 
            array (
                'id' => 7,
                'credit_note_id' => 5,
                'hawb' => '15482573187818',
                'date_booked' => NULL,
                'reference' => 'test_reference',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-01-29 17:20:14',
                'updated_by' => 58,
                'date_updated' => '2019-01-29 11:20:14',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            30 => 
            array (
                'id' => 8,
                'credit_note_id' => 6,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.05',
                'credit_amount' => '0.05',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-13 20:43:55',
                'updated_by' => 2181,
                'date_updated' => '2019-05-13 15:43:55',
                'vat_amount' => '0.00',
                'added_by' => 2181,
            ),
            31 => 
            array (
                'id' => 9,
                'credit_note_id' => 7,
                'hawb' => '1558717530875',
                'date_booked' => '2019-05-29 00:00:00',
                'reference' => 'test_reference',
                'invoice_amount' => '10.02',
                'chargeable_amount' => '9.02',
                'credit_amount' => '1.00',
                'description' => '1 GBP should be credited',
                'is_vatable' => 'YES',
                'date_created' => '2019-05-31 21:51:14',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 16:51:14',
                'vat_amount' => '0.20',
                'added_by' => 58,
            ),
            32 => 
            array (
                'id' => 10,
                'credit_note_id' => 8,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '14.00',
                'chargeable_amount' => '10.00',
                'credit_amount' => '4.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:15:26',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:15:26',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            33 => 
            array (
                'id' => 11,
                'credit_note_id' => 9,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '5.00',
                'chargeable_amount' => '4.00',
                'credit_amount' => '1.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:58:30',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:58:30',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            34 => 
            array (
                'id' => 12,
                'credit_note_id' => 10,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '8.00',
                'credit_amount' => '2.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-10 17:11:58',
                'updated_by' => 58,
                'date_updated' => '2019-06-10 12:11:58',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            35 => 
            array (
                'id' => 13,
                'credit_note_id' => 11,
                'hawb' => '',
                'date_booked' => '2019-06-27 00:00:00',
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-06-27 16:11:56',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:11:56',
                'vat_amount' => '0.36',
                'added_by' => 58,
            ),
            36 => 
            array (
                'id' => 14,
                'credit_note_id' => 12,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-27 16:26:22',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:26:22',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            37 => 
            array (
                'id' => 15,
                'credit_note_id' => 13,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '9.00',
                'credit_amount' => '1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-07-03 16:18:00',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:18:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            38 => 
            array (
                'id' => 16,
                'credit_note_id' => 14,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '-1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-07-03 16:26:02',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:26:02',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            39 => 
            array (
                'id' => 36,
                'credit_note_id' => 16,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-21 18:04:46',
                'updated_by' => 58,
                'date_updated' => '2019-08-21 13:04:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            40 => 
            array (
                'id' => 37,
                'credit_note_id' => 17,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-22 19:25:10',
                'updated_by' => 58,
                'date_updated' => '2019-08-22 14:25:10',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            41 => 
            array (
                'id' => 38,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:57:53',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:57:53',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            42 => 
            array (
                'id' => 39,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:58:36',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:58:36',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            43 => 
            array (
                'id' => 40,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => NULL,
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.00',
                'description' => 'TEST mruga',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 20:00:03',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 15:00:03',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            44 => 
            array (
                'id' => 41,
                'credit_note_id' => 18,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:31:52',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:31:52',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            45 => 
            array (
                'id' => 42,
                'credit_note_id' => 19,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:44:06',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:44:06',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            46 => 
            array (
                'id' => 43,
                'credit_note_id' => 20,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            47 => 
            array (
                'id' => 44,
                'credit_note_id' => 20,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            48 => 
            array (
                'id' => 47,
                'credit_note_id' => 21,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            49 => 
            array (
                'id' => 48,
                'credit_note_id' => 21,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            50 => 
            array (
                'id' => 2,
                'credit_note_id' => 2,
                'hawb' => 'Test',
                'date_booked' => '2018-11-25 00:00:00',
                'reference' => 'Test ref',
                'invoice_amount' => '50.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '30.00',
                'description' => '',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-23 19:45:20',
                'updated_by' => 2170,
                'date_updated' => '2018-11-23 13:45:20',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            51 => 
            array (
                'id' => 3,
                'credit_note_id' => 3,
                'hawb' => 'Negative Test Case',
                'date_booked' => '2018-11-30 00:00:00',
                'reference' => 'Test',
                'invoice_amount' => '45.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '25.00',
                'description' => 'Credit to Corporate account but HAWB no given of its child shipment',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-23 19:59:46',
                'updated_by' => 58,
                'date_updated' => '2018-11-23 13:59:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            52 => 
            array (
                'id' => 4,
                'credit_note_id' => 1,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-27 19:22:15',
                'updated_by' => 2170,
                'date_updated' => '2018-11-27 13:22:15',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            53 => 
            array (
                'id' => 6,
                'credit_note_id' => 4,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '30.00',
                'chargeable_amount' => '25.00',
                'credit_amount' => '5.00',
                'description' => '5 GBP is Credited to the Client',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-28 22:20:51',
                'updated_by' => 2170,
                'date_updated' => '2018-11-28 16:20:51',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            54 => 
            array (
                'id' => 7,
                'credit_note_id' => 5,
                'hawb' => '15482573187818',
                'date_booked' => NULL,
                'reference' => 'test_reference',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-01-29 17:20:14',
                'updated_by' => 58,
                'date_updated' => '2019-01-29 11:20:14',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            55 => 
            array (
                'id' => 8,
                'credit_note_id' => 6,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.05',
                'credit_amount' => '0.05',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-13 20:43:55',
                'updated_by' => 2181,
                'date_updated' => '2019-05-13 15:43:55',
                'vat_amount' => '0.00',
                'added_by' => 2181,
            ),
            56 => 
            array (
                'id' => 9,
                'credit_note_id' => 7,
                'hawb' => '1558717530875',
                'date_booked' => '2019-05-29 00:00:00',
                'reference' => 'test_reference',
                'invoice_amount' => '10.02',
                'chargeable_amount' => '9.02',
                'credit_amount' => '1.00',
                'description' => '1 GBP should be credited',
                'is_vatable' => 'YES',
                'date_created' => '2019-05-31 21:51:14',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 16:51:14',
                'vat_amount' => '0.20',
                'added_by' => 58,
            ),
            57 => 
            array (
                'id' => 10,
                'credit_note_id' => 8,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '14.00',
                'chargeable_amount' => '10.00',
                'credit_amount' => '4.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:15:26',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:15:26',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            58 => 
            array (
                'id' => 11,
                'credit_note_id' => 9,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '5.00',
                'chargeable_amount' => '4.00',
                'credit_amount' => '1.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:58:30',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:58:30',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            59 => 
            array (
                'id' => 12,
                'credit_note_id' => 10,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '8.00',
                'credit_amount' => '2.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-10 17:11:58',
                'updated_by' => 58,
                'date_updated' => '2019-06-10 12:11:58',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            60 => 
            array (
                'id' => 13,
                'credit_note_id' => 11,
                'hawb' => '',
                'date_booked' => '2019-06-27 00:00:00',
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-06-27 16:11:56',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:11:56',
                'vat_amount' => '0.36',
                'added_by' => 58,
            ),
            61 => 
            array (
                'id' => 14,
                'credit_note_id' => 12,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-27 16:26:22',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:26:22',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            62 => 
            array (
                'id' => 15,
                'credit_note_id' => 13,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '9.00',
                'credit_amount' => '1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-07-03 16:18:00',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:18:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            63 => 
            array (
                'id' => 16,
                'credit_note_id' => 14,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '-1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-07-03 16:26:02',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:26:02',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            64 => 
            array (
                'id' => 36,
                'credit_note_id' => 16,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-21 18:04:46',
                'updated_by' => 58,
                'date_updated' => '2019-08-21 13:04:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            65 => 
            array (
                'id' => 37,
                'credit_note_id' => 17,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-22 19:25:10',
                'updated_by' => 58,
                'date_updated' => '2019-08-22 14:25:10',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            66 => 
            array (
                'id' => 38,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:57:53',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:57:53',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            67 => 
            array (
                'id' => 39,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:58:36',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:58:36',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            68 => 
            array (
                'id' => 40,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => NULL,
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.00',
                'description' => 'TEST mruga',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 20:00:03',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 15:00:03',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            69 => 
            array (
                'id' => 41,
                'credit_note_id' => 18,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:31:52',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:31:52',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            70 => 
            array (
                'id' => 42,
                'credit_note_id' => 19,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:44:06',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:44:06',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            71 => 
            array (
                'id' => 43,
                'credit_note_id' => 20,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            72 => 
            array (
                'id' => 44,
                'credit_note_id' => 20,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            73 => 
            array (
                'id' => 47,
                'credit_note_id' => 21,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            74 => 
            array (
                'id' => 48,
                'credit_note_id' => 21,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            75 => 
            array (
                'id' => 2,
                'credit_note_id' => 2,
                'hawb' => 'Test',
                'date_booked' => '2018-11-25 00:00:00',
                'reference' => 'Test ref',
                'invoice_amount' => '50.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '30.00',
                'description' => '',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-23 19:45:20',
                'updated_by' => 2170,
                'date_updated' => '2018-11-23 13:45:20',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            76 => 
            array (
                'id' => 3,
                'credit_note_id' => 3,
                'hawb' => 'Negative Test Case',
                'date_booked' => '2018-11-30 00:00:00',
                'reference' => 'Test',
                'invoice_amount' => '45.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '25.00',
                'description' => 'Credit to Corporate account but HAWB no given of its child shipment',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-23 19:59:46',
                'updated_by' => 58,
                'date_updated' => '2018-11-23 13:59:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            77 => 
            array (
                'id' => 4,
                'credit_note_id' => 1,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-27 19:22:15',
                'updated_by' => 2170,
                'date_updated' => '2018-11-27 13:22:15',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            78 => 
            array (
                'id' => 6,
                'credit_note_id' => 4,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '30.00',
                'chargeable_amount' => '25.00',
                'credit_amount' => '5.00',
                'description' => '5 GBP is Credited to the Client',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-28 22:20:51',
                'updated_by' => 2170,
                'date_updated' => '2018-11-28 16:20:51',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            79 => 
            array (
                'id' => 7,
                'credit_note_id' => 5,
                'hawb' => '15482573187818',
                'date_booked' => NULL,
                'reference' => 'test_reference',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-01-29 17:20:14',
                'updated_by' => 58,
                'date_updated' => '2019-01-29 11:20:14',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            80 => 
            array (
                'id' => 8,
                'credit_note_id' => 6,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.05',
                'credit_amount' => '0.05',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-13 20:43:55',
                'updated_by' => 2181,
                'date_updated' => '2019-05-13 15:43:55',
                'vat_amount' => '0.00',
                'added_by' => 2181,
            ),
            81 => 
            array (
                'id' => 9,
                'credit_note_id' => 7,
                'hawb' => '1558717530875',
                'date_booked' => '2019-05-29 00:00:00',
                'reference' => 'test_reference',
                'invoice_amount' => '10.02',
                'chargeable_amount' => '9.02',
                'credit_amount' => '1.00',
                'description' => '1 GBP should be credited',
                'is_vatable' => 'YES',
                'date_created' => '2019-05-31 21:51:14',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 16:51:14',
                'vat_amount' => '0.20',
                'added_by' => 58,
            ),
            82 => 
            array (
                'id' => 10,
                'credit_note_id' => 8,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '14.00',
                'chargeable_amount' => '10.00',
                'credit_amount' => '4.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:15:26',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:15:26',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            83 => 
            array (
                'id' => 11,
                'credit_note_id' => 9,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '5.00',
                'chargeable_amount' => '4.00',
                'credit_amount' => '1.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:58:30',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:58:30',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            84 => 
            array (
                'id' => 12,
                'credit_note_id' => 10,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '8.00',
                'credit_amount' => '2.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-10 17:11:58',
                'updated_by' => 58,
                'date_updated' => '2019-06-10 12:11:58',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            85 => 
            array (
                'id' => 13,
                'credit_note_id' => 11,
                'hawb' => '',
                'date_booked' => '2019-06-27 00:00:00',
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-06-27 16:11:56',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:11:56',
                'vat_amount' => '0.36',
                'added_by' => 58,
            ),
            86 => 
            array (
                'id' => 14,
                'credit_note_id' => 12,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-27 16:26:22',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:26:22',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            87 => 
            array (
                'id' => 15,
                'credit_note_id' => 13,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '9.00',
                'credit_amount' => '1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-07-03 16:18:00',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:18:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            88 => 
            array (
                'id' => 16,
                'credit_note_id' => 14,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '-1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-07-03 16:26:02',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:26:02',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            89 => 
            array (
                'id' => 36,
                'credit_note_id' => 16,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-21 18:04:46',
                'updated_by' => 58,
                'date_updated' => '2019-08-21 13:04:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            90 => 
            array (
                'id' => 37,
                'credit_note_id' => 17,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-22 19:25:10',
                'updated_by' => 58,
                'date_updated' => '2019-08-22 14:25:10',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            91 => 
            array (
                'id' => 38,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:57:53',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:57:53',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            92 => 
            array (
                'id' => 39,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:58:36',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:58:36',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            93 => 
            array (
                'id' => 40,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => NULL,
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.00',
                'description' => 'TEST mruga',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 20:00:03',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 15:00:03',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            94 => 
            array (
                'id' => 41,
                'credit_note_id' => 18,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:31:52',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:31:52',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            95 => 
            array (
                'id' => 42,
                'credit_note_id' => 19,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:44:06',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:44:06',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            96 => 
            array (
                'id' => 43,
                'credit_note_id' => 20,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            97 => 
            array (
                'id' => 44,
                'credit_note_id' => 20,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            98 => 
            array (
                'id' => 47,
                'credit_note_id' => 21,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            99 => 
            array (
                'id' => 48,
                'credit_note_id' => 21,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            100 => 
            array (
                'id' => 2,
                'credit_note_id' => 2,
                'hawb' => 'Test',
                'date_booked' => '2018-11-25 00:00:00',
                'reference' => 'Test ref',
                'invoice_amount' => '50.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '30.00',
                'description' => '',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-23 19:45:20',
                'updated_by' => 2170,
                'date_updated' => '2018-11-23 13:45:20',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            101 => 
            array (
                'id' => 3,
                'credit_note_id' => 3,
                'hawb' => 'Negative Test Case',
                'date_booked' => '2018-11-30 00:00:00',
                'reference' => 'Test',
                'invoice_amount' => '45.00',
                'chargeable_amount' => '20.00',
                'credit_amount' => '25.00',
                'description' => 'Credit to Corporate account but HAWB no given of its child shipment',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-23 19:59:46',
                'updated_by' => 58,
                'date_updated' => '2018-11-23 13:59:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            102 => 
            array (
                'id' => 4,
                'credit_note_id' => 1,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2018-11-27 19:22:15',
                'updated_by' => 2170,
                'date_updated' => '2018-11-27 13:22:15',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            103 => 
            array (
                'id' => 6,
                'credit_note_id' => 4,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '30.00',
                'chargeable_amount' => '25.00',
                'credit_amount' => '5.00',
                'description' => '5 GBP is Credited to the Client',
                'is_vatable' => 'YES',
                'date_created' => '2018-11-28 22:20:51',
                'updated_by' => 2170,
                'date_updated' => '2018-11-28 16:20:51',
                'vat_amount' => '0.00',
                'added_by' => 2170,
            ),
            104 => 
            array (
                'id' => 7,
                'credit_note_id' => 5,
                'hawb' => '15482573187818',
                'date_booked' => NULL,
                'reference' => 'test_reference',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-01-29 17:20:14',
                'updated_by' => 58,
                'date_updated' => '2019-01-29 11:20:14',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            105 => 
            array (
                'id' => 8,
                'credit_note_id' => 6,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.05',
                'credit_amount' => '0.05',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-13 20:43:55',
                'updated_by' => 2181,
                'date_updated' => '2019-05-13 15:43:55',
                'vat_amount' => '0.00',
                'added_by' => 2181,
            ),
            106 => 
            array (
                'id' => 9,
                'credit_note_id' => 7,
                'hawb' => '1558717530875',
                'date_booked' => '2019-05-29 00:00:00',
                'reference' => 'test_reference',
                'invoice_amount' => '10.02',
                'chargeable_amount' => '9.02',
                'credit_amount' => '1.00',
                'description' => '1 GBP should be credited',
                'is_vatable' => 'YES',
                'date_created' => '2019-05-31 21:51:14',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 16:51:14',
                'vat_amount' => '0.20',
                'added_by' => 58,
            ),
            107 => 
            array (
                'id' => 10,
                'credit_note_id' => 8,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '14.00',
                'chargeable_amount' => '10.00',
                'credit_amount' => '4.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:15:26',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:15:26',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            108 => 
            array (
                'id' => 11,
                'credit_note_id' => 9,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '5.00',
                'chargeable_amount' => '4.00',
                'credit_amount' => '1.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-05-31 22:58:30',
                'updated_by' => 58,
                'date_updated' => '2019-05-31 17:58:30',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            109 => 
            array (
                'id' => 12,
                'credit_note_id' => 10,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '8.00',
                'credit_amount' => '2.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-10 17:11:58',
                'updated_by' => 58,
                'date_updated' => '2019-06-10 12:11:58',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            110 => 
            array (
                'id' => 13,
                'credit_note_id' => 11,
                'hawb' => '',
                'date_booked' => '2019-06-27 00:00:00',
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-06-27 16:11:56',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:11:56',
                'vat_amount' => '0.36',
                'added_by' => 58,
            ),
            111 => 
            array (
                'id' => 14,
                'credit_note_id' => 12,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '1.78',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.78',
                'description' => 'Account Number: 2294 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-06-27 16:26:22',
                'updated_by' => 58,
                'date_updated' => '2019-06-27 11:26:22',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            112 => 
            array (
                'id' => 15,
                'credit_note_id' => 13,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '10.00',
                'chargeable_amount' => '9.00',
                'credit_amount' => '1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-07-03 16:18:00',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:18:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            113 => 
            array (
                'id' => 16,
                'credit_note_id' => 14,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '-1.00',
                'description' => 'Account Number: 2320 has  consignments for credit note.',
                'is_vatable' => 'NO',
                'date_created' => '2019-07-03 16:26:02',
                'updated_by' => 58,
                'date_updated' => '2019-07-03 11:26:02',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            114 => 
            array (
                'id' => 36,
                'credit_note_id' => 16,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.10',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.10',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-21 18:04:46',
                'updated_by' => 58,
                'date_updated' => '2019-08-21 13:04:46',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            115 => 
            array (
                'id' => 37,
                'credit_note_id' => 17,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-22 19:25:10',
                'updated_by' => 58,
                'date_updated' => '2019-08-22 14:25:10',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            116 => 
            array (
                'id' => 38,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:57:53',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:57:53',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            117 => 
            array (
                'id' => 39,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => '2019-08-23 00:00:00',
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '1.00',
                'credit_amount' => '0.00',
                'description' => 'TEST',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 21:58:36',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 16:58:36',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            118 => 
            array (
                'id' => 40,
                'credit_note_id' => 0,
                'hawb' => '1565881624',
                'date_booked' => NULL,
                'reference' => 'TEST',
                'invoice_amount' => '1.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '1.00',
                'description' => 'TEST mruga',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 20:00:03',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 15:00:03',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            119 => 
            array (
                'id' => 41,
                'credit_note_id' => 18,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:31:52',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:31:52',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            120 => 
            array (
                'id' => 42,
                'credit_note_id' => 19,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-08-23 22:44:06',
                'updated_by' => 58,
                'date_updated' => '2019-08-23 17:44:06',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            121 => 
            array (
                'id' => 43,
                'credit_note_id' => 20,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            122 => 
            array (
                'id' => 44,
                'credit_note_id' => 20,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:31:35',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:31:35',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            123 => 
            array (
                'id' => 47,
                'credit_note_id' => 21,
                'hawb' => '12346465',
                'date_booked' => NULL,
                'reference' => '0001111',
                'invoice_amount' => '1806.30',
                'chargeable_amount' => '23.00',
                'credit_amount' => '1783.30',
                'description' => 'Account Number: 2300 has  consignments for credit note.',
                'is_vatable' => 'YES',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
            124 => 
            array (
                'id' => 48,
                'credit_note_id' => 21,
                'hawb' => '',
                'date_booked' => NULL,
                'reference' => '',
                'invoice_amount' => '0.00',
                'chargeable_amount' => '0.00',
                'credit_amount' => '0.00',
                'description' => '',
                'is_vatable' => 'NO',
                'date_created' => '2019-11-20 21:36:00',
                'updated_by' => 58,
                'date_updated' => '2019-11-20 15:36:00',
                'vat_amount' => '0.00',
                'added_by' => 58,
            ),
        ));
        
        
    }
}