<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CsLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cs_logs')->delete();
        
        \DB::table('cs_logs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:54:59',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            1 => 
            array (
                'id' => 2,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:06',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            2 => 
            array (
                'id' => 3,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:28',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            3 => 
            array (
                'id' => 4,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdfaf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:57:42',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            4 => 
            array (
                'id' => 5,
                'consignment_id' => 886,
                'internal_message' => 'test log',
                'customer_message' => 'please ingor this',
                'cust_mail' => 'Yes',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:37',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            5 => 
            array (
                'id' => 6,
                'consignment_id' => 886,
                'internal_message' => '',
                'customer_message' => '*please ingor this<br>',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:49',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            6 => 
            array (
                'id' => 7,
                'consignment_id' => 132421,
                'internal_message' => 'This is a test package',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:29',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            7 => 
            array (
                'id' => 8,
                'consignment_id' => 132421,
                'internal_message' => 'There has been a change of address to: ',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:57',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            8 => 
            array (
                'id' => 1,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:54:59',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            9 => 
            array (
                'id' => 2,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:06',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            10 => 
            array (
                'id' => 3,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:28',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            11 => 
            array (
                'id' => 4,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdfaf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:57:42',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            12 => 
            array (
                'id' => 5,
                'consignment_id' => 886,
                'internal_message' => 'test log',
                'customer_message' => 'please ingor this',
                'cust_mail' => 'Yes',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:37',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            13 => 
            array (
                'id' => 6,
                'consignment_id' => 886,
                'internal_message' => '',
                'customer_message' => '*please ingor this<br>',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:49',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            14 => 
            array (
                'id' => 7,
                'consignment_id' => 132421,
                'internal_message' => 'This is a test package',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:29',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            15 => 
            array (
                'id' => 8,
                'consignment_id' => 132421,
                'internal_message' => 'There has been a change of address to: ',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:57',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            16 => 
            array (
                'id' => 1,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:54:59',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            17 => 
            array (
                'id' => 2,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:06',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            18 => 
            array (
                'id' => 3,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:28',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            19 => 
            array (
                'id' => 4,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdfaf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:57:42',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            20 => 
            array (
                'id' => 5,
                'consignment_id' => 886,
                'internal_message' => 'test log',
                'customer_message' => 'please ingor this',
                'cust_mail' => 'Yes',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:37',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            21 => 
            array (
                'id' => 6,
                'consignment_id' => 886,
                'internal_message' => '',
                'customer_message' => '*please ingor this<br>',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:49',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            22 => 
            array (
                'id' => 7,
                'consignment_id' => 132421,
                'internal_message' => 'This is a test package',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:29',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            23 => 
            array (
                'id' => 8,
                'consignment_id' => 132421,
                'internal_message' => 'There has been a change of address to: ',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:57',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            24 => 
            array (
                'id' => 1,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:54:59',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            25 => 
            array (
                'id' => 2,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:06',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            26 => 
            array (
                'id' => 3,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:28',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            27 => 
            array (
                'id' => 4,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdfaf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:57:42',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            28 => 
            array (
                'id' => 5,
                'consignment_id' => 886,
                'internal_message' => 'test log',
                'customer_message' => 'please ingor this',
                'cust_mail' => 'Yes',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:37',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            29 => 
            array (
                'id' => 6,
                'consignment_id' => 886,
                'internal_message' => '',
                'customer_message' => '*please ingor this<br>',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:49',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            30 => 
            array (
                'id' => 7,
                'consignment_id' => 132421,
                'internal_message' => 'This is a test package',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:29',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            31 => 
            array (
                'id' => 8,
                'consignment_id' => 132421,
                'internal_message' => 'There has been a change of address to: ',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:57',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            32 => 
            array (
                'id' => 1,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:54:59',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            33 => 
            array (
                'id' => 2,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:06',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            34 => 
            array (
                'id' => 3,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:56:28',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            35 => 
            array (
                'id' => 4,
                'consignment_id' => 93154,
                'internal_message' => '',
                'customer_message' => 'asdfasdfaf',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-07-30 11:57:42',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            36 => 
            array (
                'id' => 5,
                'consignment_id' => 886,
                'internal_message' => 'test log',
                'customer_message' => 'please ingor this',
                'cust_mail' => 'Yes',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:37',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            37 => 
            array (
                'id' => 6,
                'consignment_id' => 886,
                'internal_message' => '',
                'customer_message' => '*please ingor this<br>',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-08-02 17:28:49',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 58,
            ),
            38 => 
            array (
                'id' => 7,
                'consignment_id' => 132421,
                'internal_message' => 'This is a test package',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:29',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
            39 => 
            array (
                'id' => 8,
                'consignment_id' => 132421,
                'internal_message' => 'There has been a change of address to: ',
                'customer_message' => '',
                'cust_mail' => 'No',
                'agent_mail' => 'No',
                'date_created' => '2019-12-12 11:06:57',
                'reminder' => '',
                'reminder_expiry' => NULL,
                'userid' => 2309,
            ),
        ));
        
        
    }
}