<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CsvImportTemplatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('csv_import_templates')->delete();
        
        \DB::table('csv_import_templates')->insert(array (
            0 => 
            array (
                'id' => 3,
                'user_id' => 2191,
                'user_account_id' => 2297,
                'template_name' => 'Tahir Finance Account Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2191,
                'added_date' => '2019-04-12 14:09:19',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            1 => 
            array (
                'id' => 8,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'CH02 Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2277,
                'added_date' => '2019-09-02 13:27:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            2 => 
            array (
                'id' => 9,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'Demo1',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","parcels":"parcels"}',
                'added_by' => 2296,
                'added_date' => '2019-09-10 15:04:02',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            3 => 
            array (
                'id' => 10,
                'user_id' => 2283,
                'user_account_id' => 2331,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2283,
                'added_date' => '2019-09-13 16:51:44',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            4 => 
            array (
                'id' => 11,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-16 16:12:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            5 => 
            array (
                'id' => 12,
                'user_id' => 58,
                'user_account_id' => 148,
                'template_name' => 'hadi  tem',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 58,
                'added_date' => '2019-09-16 17:04:00',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            6 => 
            array (
                'id' => 13,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new-format-lwh',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 13:48:50',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            7 => 
            array (
                'id' => 14,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 12:27:41',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            8 => 
            array (
                'id' => 15,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-20 10:19:21',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            9 => 
            array (
                'id' => 16,
                'user_id' => 2265,
                'user_account_id' => 2328,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2265,
                'added_date' => '2019-10-11 11:53:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            10 => 
            array (
                'id' => 17,
                'user_id' => 2183,
                'user_account_id' => 2294,
                'template_name' => 'required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2183,
                'added_date' => '2019-11-13 13:55:33',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            11 => 
            array (
                'id' => 18,
                'user_id' => 2311,
                'user_account_id' => 2351,
                'template_name' => 'Required Fields',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2311,
                'added_date' => '2019-12-02 11:35:53',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            12 => 
            array (
                'id' => 19,
                'user_id' => 2307,
                'user_account_id' => 2342,
                'template_name' => 'Test CH03',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2307,
                'added_date' => '2019-12-19 12:15:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            13 => 
            array (
                'id' => 20,
                'user_id' => 2271,
                'user_account_id' => 2329,
                'template_name' => 'CL01_required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2271,
                'added_date' => '2020-01-20 16:09:28',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2277,
                'added_date' => '2020-01-23 15:41:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Amazon Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:27:34',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'AmazonMFNParcels Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","reference":"reference","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:50:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            17 => 
            array (
                'id' => 3,
                'user_id' => 2191,
                'user_account_id' => 2297,
                'template_name' => 'Tahir Finance Account Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2191,
                'added_date' => '2019-04-12 14:09:19',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            18 => 
            array (
                'id' => 8,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'CH02 Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2277,
                'added_date' => '2019-09-02 13:27:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            19 => 
            array (
                'id' => 9,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'Demo1',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","parcels":"parcels"}',
                'added_by' => 2296,
                'added_date' => '2019-09-10 15:04:02',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            20 => 
            array (
                'id' => 10,
                'user_id' => 2283,
                'user_account_id' => 2331,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2283,
                'added_date' => '2019-09-13 16:51:44',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            21 => 
            array (
                'id' => 11,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-16 16:12:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            22 => 
            array (
                'id' => 12,
                'user_id' => 58,
                'user_account_id' => 148,
                'template_name' => 'hadi  tem',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 58,
                'added_date' => '2019-09-16 17:04:00',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            23 => 
            array (
                'id' => 13,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new-format-lwh',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 13:48:50',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            24 => 
            array (
                'id' => 14,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 12:27:41',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            25 => 
            array (
                'id' => 15,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-20 10:19:21',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            26 => 
            array (
                'id' => 16,
                'user_id' => 2265,
                'user_account_id' => 2328,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2265,
                'added_date' => '2019-10-11 11:53:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            27 => 
            array (
                'id' => 17,
                'user_id' => 2183,
                'user_account_id' => 2294,
                'template_name' => 'required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2183,
                'added_date' => '2019-11-13 13:55:33',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            28 => 
            array (
                'id' => 18,
                'user_id' => 2311,
                'user_account_id' => 2351,
                'template_name' => 'Required Fields',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2311,
                'added_date' => '2019-12-02 11:35:53',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            29 => 
            array (
                'id' => 19,
                'user_id' => 2307,
                'user_account_id' => 2342,
                'template_name' => 'Test CH03',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2307,
                'added_date' => '2019-12-19 12:15:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            30 => 
            array (
                'id' => 20,
                'user_id' => 2271,
                'user_account_id' => 2329,
                'template_name' => 'CL01_required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2271,
                'added_date' => '2020-01-20 16:09:28',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            31 => 
            array (
                'id' => 21,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2277,
                'added_date' => '2020-01-23 15:41:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            32 => 
            array (
                'id' => 22,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Amazon Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:27:34',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            33 => 
            array (
                'id' => 23,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'AmazonMFNParcels Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","reference":"reference","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:50:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            34 => 
            array (
                'id' => 3,
                'user_id' => 2191,
                'user_account_id' => 2297,
                'template_name' => 'Tahir Finance Account Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2191,
                'added_date' => '2019-04-12 14:09:19',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            35 => 
            array (
                'id' => 8,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'CH02 Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2277,
                'added_date' => '2019-09-02 13:27:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            36 => 
            array (
                'id' => 9,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'Demo1',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","parcels":"parcels"}',
                'added_by' => 2296,
                'added_date' => '2019-09-10 15:04:02',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            37 => 
            array (
                'id' => 10,
                'user_id' => 2283,
                'user_account_id' => 2331,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2283,
                'added_date' => '2019-09-13 16:51:44',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            38 => 
            array (
                'id' => 11,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-16 16:12:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            39 => 
            array (
                'id' => 12,
                'user_id' => 58,
                'user_account_id' => 148,
                'template_name' => 'hadi  tem',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 58,
                'added_date' => '2019-09-16 17:04:00',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            40 => 
            array (
                'id' => 13,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new-format-lwh',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 13:48:50',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            41 => 
            array (
                'id' => 14,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 12:27:41',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            42 => 
            array (
                'id' => 15,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-20 10:19:21',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            43 => 
            array (
                'id' => 16,
                'user_id' => 2265,
                'user_account_id' => 2328,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2265,
                'added_date' => '2019-10-11 11:53:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            44 => 
            array (
                'id' => 17,
                'user_id' => 2183,
                'user_account_id' => 2294,
                'template_name' => 'required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2183,
                'added_date' => '2019-11-13 13:55:33',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            45 => 
            array (
                'id' => 18,
                'user_id' => 2311,
                'user_account_id' => 2351,
                'template_name' => 'Required Fields',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2311,
                'added_date' => '2019-12-02 11:35:53',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            46 => 
            array (
                'id' => 19,
                'user_id' => 2307,
                'user_account_id' => 2342,
                'template_name' => 'Test CH03',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2307,
                'added_date' => '2019-12-19 12:15:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            47 => 
            array (
                'id' => 20,
                'user_id' => 2271,
                'user_account_id' => 2329,
                'template_name' => 'CL01_required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2271,
                'added_date' => '2020-01-20 16:09:28',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            48 => 
            array (
                'id' => 21,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2277,
                'added_date' => '2020-01-23 15:41:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            49 => 
            array (
                'id' => 22,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Amazon Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:27:34',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            50 => 
            array (
                'id' => 23,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'AmazonMFNParcels Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","reference":"reference","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:50:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            51 => 
            array (
                'id' => 3,
                'user_id' => 2191,
                'user_account_id' => 2297,
                'template_name' => 'Tahir Finance Account Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2191,
                'added_date' => '2019-04-12 14:09:19',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            52 => 
            array (
                'id' => 8,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'CH02 Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2277,
                'added_date' => '2019-09-02 13:27:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            53 => 
            array (
                'id' => 9,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'Demo1',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","parcels":"parcels"}',
                'added_by' => 2296,
                'added_date' => '2019-09-10 15:04:02',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            54 => 
            array (
                'id' => 10,
                'user_id' => 2283,
                'user_account_id' => 2331,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2283,
                'added_date' => '2019-09-13 16:51:44',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            55 => 
            array (
                'id' => 11,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-16 16:12:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            56 => 
            array (
                'id' => 12,
                'user_id' => 58,
                'user_account_id' => 148,
                'template_name' => 'hadi  tem',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 58,
                'added_date' => '2019-09-16 17:04:00',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            57 => 
            array (
                'id' => 13,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new-format-lwh',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 13:48:50',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            58 => 
            array (
                'id' => 14,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 12:27:41',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            59 => 
            array (
                'id' => 15,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-20 10:19:21',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            60 => 
            array (
                'id' => 16,
                'user_id' => 2265,
                'user_account_id' => 2328,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2265,
                'added_date' => '2019-10-11 11:53:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            61 => 
            array (
                'id' => 17,
                'user_id' => 2183,
                'user_account_id' => 2294,
                'template_name' => 'required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2183,
                'added_date' => '2019-11-13 13:55:33',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            62 => 
            array (
                'id' => 18,
                'user_id' => 2311,
                'user_account_id' => 2351,
                'template_name' => 'Required Fields',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2311,
                'added_date' => '2019-12-02 11:35:53',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            63 => 
            array (
                'id' => 19,
                'user_id' => 2307,
                'user_account_id' => 2342,
                'template_name' => 'Test CH03',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2307,
                'added_date' => '2019-12-19 12:15:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            64 => 
            array (
                'id' => 20,
                'user_id' => 2271,
                'user_account_id' => 2329,
                'template_name' => 'CL01_required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2271,
                'added_date' => '2020-01-20 16:09:28',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            65 => 
            array (
                'id' => 21,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2277,
                'added_date' => '2020-01-23 15:41:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            66 => 
            array (
                'id' => 22,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Amazon Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:27:34',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            67 => 
            array (
                'id' => 23,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'AmazonMFNParcels Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","reference":"reference","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:50:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            68 => 
            array (
                'id' => 3,
                'user_id' => 2191,
                'user_account_id' => 2297,
                'template_name' => 'Tahir Finance Account Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2191,
                'added_date' => '2019-04-12 14:09:19',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            69 => 
            array (
                'id' => 8,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'CH02 Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","parcels":"parcels"}',
                'added_by' => 2277,
                'added_date' => '2019-09-02 13:27:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            70 => 
            array (
                'id' => 9,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'Demo1',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","parcels":"parcels"}',
                'added_by' => 2296,
                'added_date' => '2019-09-10 15:04:02',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            71 => 
            array (
                'id' => 10,
                'user_id' => 2283,
                'user_account_id' => 2331,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2283,
                'added_date' => '2019-09-13 16:51:44',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            72 => 
            array (
                'id' => 11,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Req Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-16 16:12:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            73 => 
            array (
                'id' => 12,
                'user_id' => 58,
                'user_account_id' => 148,
                'template_name' => 'hadi  tem',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 58,
                'added_date' => '2019-09-16 17:04:00',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            74 => 
            array (
                'id' => 13,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new-format-lwh',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_address_line_2":"receiver_address_line_2","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 13:48:50',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            75 => 
            array (
                'id' => 14,
                'user_id' => 2296,
                'user_account_id' => 2337,
                'template_name' => 'new',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2296,
                'added_date' => '2019-09-17 12:27:41',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            76 => 
            array (
                'id' => 15,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","itemvalue":"itemvalue","length":"length","height":"height","width":"width"}',
                'added_by' => 2253,
                'added_date' => '2019-09-20 10:19:21',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            77 => 
            array (
                'id' => 16,
                'user_id' => 2265,
                'user_account_id' => 2328,
                'template_name' => 'Test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2265,
                'added_date' => '2019-10-11 11:53:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            78 => 
            array (
                'id' => 17,
                'user_id' => 2183,
                'user_account_id' => 2294,
                'template_name' => 'required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2183,
                'added_date' => '2019-11-13 13:55:33',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            79 => 
            array (
                'id' => 18,
                'user_id' => 2311,
                'user_account_id' => 2351,
                'template_name' => 'Required Fields',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2311,
                'added_date' => '2019-12-02 11:35:53',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            80 => 
            array (
                'id' => 19,
                'user_id' => 2307,
                'user_account_id' => 2342,
                'template_name' => 'Test CH03',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2307,
                'added_date' => '2019-12-19 12:15:09',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            81 => 
            array (
                'id' => 20,
                'user_id' => 2271,
                'user_account_id' => 2329,
                'template_name' => 'CL01_required',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2271,
                'added_date' => '2020-01-20 16:09:28',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            82 => 
            array (
                'id' => 21,
                'user_id' => 2277,
                'user_account_id' => 2330,
                'template_name' => 'test',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_postcode":"receiver_postcode","description":"description","weight":"weight","length":"length","height":"height","width":"width"}',
                'added_by' => 2277,
                'added_date' => '2020-01-23 15:41:14',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            83 => 
            array (
                'id' => 22,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'Amazon Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:27:34',
                'update_by' => 0,
                'update_date' => NULL,
            ),
            84 => 
            array (
                'id' => 23,
                'user_id' => 2253,
                'user_account_id' => 2326,
                'template_name' => 'AmazonMFNParcels Template',
                'template' => '{"date_added":"date_added","shipper_country_iso":"shipper_country_iso","receiver_country_iso":"receiver_country_iso","service_code":"service_code","order_reference":"order_reference","receiver_contact":"receiver_contact","receiver_address_line_1":"receiver_address_line_1","receiver_city":"receiver_city","receiver_state":"receiver_state","receiver_postcode":"receiver_postcode","reference":"reference","items_value":"items_value","items_currency":"items_currency","description":"description","weight":"weight","length":"length","height":"height","width":"width","tracking_number":"tracking_number"}',
                'added_by' => 2253,
                'added_date' => '2020-03-11 18:50:49',
                'update_by' => 0,
                'update_date' => NULL,
            ),
        ));
        
        
    }
}