<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DepartmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('departments')->delete();
        
        \DB::table('departments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Accounts',
                'department_code' => 'ACC',
                'description' => 'Accounts & Finance',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'IT',
                'department_code' => 'IT',
                'description' => 'IT Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'Operation',
                'department_code' => 'OPS',
                'description' => 'Operation & Warehouse Management',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'title' => 'Customer Services',
                'department_code' => 'CS',
                'description' => 'Customer Service Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'title' => 'Corporate Customer',
                'department_code' => 'COCS',
                'description' => 'Corporate Customer',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'title' => 'Admin',
                'department_code' => 'AD',
                'description' => 'Administrator',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            6 => 
            array (
                'id' => 49,
                'title' => 'Accounts',
                'department_code' => '',
                'description' => 'Accounts 1',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '2017-08-17 17:24:08',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            7 => 
            array (
                'id' => 1,
                'title' => 'Accounts',
                'department_code' => 'ACC',
                'description' => 'Accounts & Finance',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            8 => 
            array (
                'id' => 2,
                'title' => 'IT',
                'department_code' => 'IT',
                'description' => 'IT Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            9 => 
            array (
                'id' => 3,
                'title' => 'Operation',
                'department_code' => 'OPS',
                'description' => 'Operation & Warehouse Management',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            10 => 
            array (
                'id' => 5,
                'title' => 'Customer Services',
                'department_code' => 'CS',
                'description' => 'Customer Service Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            11 => 
            array (
                'id' => 6,
                'title' => 'Corporate Customer',
                'department_code' => 'COCS',
                'description' => 'Corporate Customer',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            12 => 
            array (
                'id' => 7,
                'title' => 'Admin',
                'department_code' => 'AD',
                'description' => 'Administrator',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            13 => 
            array (
                'id' => 49,
                'title' => 'Accounts',
                'department_code' => '',
                'description' => 'Accounts 1',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '2017-08-17 17:24:08',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            14 => 
            array (
                'id' => 1,
                'title' => 'Accounts',
                'department_code' => 'ACC',
                'description' => 'Accounts & Finance',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            15 => 
            array (
                'id' => 2,
                'title' => 'IT',
                'department_code' => 'IT',
                'description' => 'IT Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            16 => 
            array (
                'id' => 3,
                'title' => 'Operation',
                'department_code' => 'OPS',
                'description' => 'Operation & Warehouse Management',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            17 => 
            array (
                'id' => 5,
                'title' => 'Customer Services',
                'department_code' => 'CS',
                'description' => 'Customer Service Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            18 => 
            array (
                'id' => 6,
                'title' => 'Corporate Customer',
                'department_code' => 'COCS',
                'description' => 'Corporate Customer',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            19 => 
            array (
                'id' => 7,
                'title' => 'Admin',
                'department_code' => 'AD',
                'description' => 'Administrator',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            20 => 
            array (
                'id' => 49,
                'title' => 'Accounts',
                'department_code' => '',
                'description' => 'Accounts 1',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '2017-08-17 17:24:08',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            21 => 
            array (
                'id' => 1,
                'title' => 'Accounts',
                'department_code' => 'ACC',
                'description' => 'Accounts & Finance',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            22 => 
            array (
                'id' => 2,
                'title' => 'IT',
                'department_code' => 'IT',
                'description' => 'IT Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            23 => 
            array (
                'id' => 3,
                'title' => 'Operation',
                'department_code' => 'OPS',
                'description' => 'Operation & Warehouse Management',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            24 => 
            array (
                'id' => 5,
                'title' => 'Customer Services',
                'department_code' => 'CS',
                'description' => 'Customer Service Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            25 => 
            array (
                'id' => 6,
                'title' => 'Corporate Customer',
                'department_code' => 'COCS',
                'description' => 'Corporate Customer',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            26 => 
            array (
                'id' => 7,
                'title' => 'Admin',
                'department_code' => 'AD',
                'description' => 'Administrator',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            27 => 
            array (
                'id' => 49,
                'title' => 'Accounts',
                'department_code' => '',
                'description' => 'Accounts 1',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '2017-08-17 17:24:08',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            28 => 
            array (
                'id' => 1,
                'title' => 'Accounts',
                'department_code' => 'ACC',
                'description' => 'Accounts & Finance',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            29 => 
            array (
                'id' => 2,
                'title' => 'IT',
                'department_code' => 'IT',
                'description' => 'IT Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            30 => 
            array (
                'id' => 3,
                'title' => 'Operation',
                'department_code' => 'OPS',
                'description' => 'Operation & Warehouse Management',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            31 => 
            array (
                'id' => 5,
                'title' => 'Customer Services',
                'department_code' => 'CS',
                'description' => 'Customer Service Manager',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            32 => 
            array (
                'id' => 6,
                'title' => 'Corporate Customer',
                'department_code' => 'COCS',
                'description' => 'Corporate Customer',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            33 => 
            array (
                'id' => 7,
                'title' => 'Admin',
                'department_code' => 'AD',
                'description' => 'Administrator',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '1970-01-01 01:33:36',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
            34 => 
            array (
                'id' => 49,
                'title' => 'Accounts',
                'department_code' => '',
                'description' => 'Accounts 1',
                'department_head' => 58,
                'isactive' => 1,
                'isdeleted' => 0,
                'addedby' => 148,
                'added_date' => '2017-08-17 17:24:08',
                'updatedby' => 0,
                'updated_on' => NULL,
            ),
        ));
        
        
    }
}