<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DocumentTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('document_types')->delete();
        
        \DB::table('document_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:23:43',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            1 => 
            array (
                'id' => 2,
                'document_name' => 'Agreed Tariif',
                'description' => 'Agreed Tariif',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            2 => 
            array (
                'id' => 3,
                'document_name' => 'Account Form',
                'description' => 'Account Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:38',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            3 => 
            array (
                'id' => 4,
                'document_name' => 'Postcode Form',
                'description' => 'Postcode Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            4 => 
            array (
                'id' => 5,
                'document_name' => 'Dangrous Goods From',
                'description' => 'Dangrous Goods From',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            5 => 
            array (
                'id' => 6,
                'document_name' => 'Contract Form',
                'description' => 'Service Contract Form',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            6 => 
            array (
                'id' => 7,
                'document_name' => 'API Doc',
                'description' => 'Service API Doc',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            7 => 
            array (
                'id' => 8,
                'document_name' => 'Postcodes',
                'description' => 'Service Postcodes',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            8 => 
            array (
                'id' => 9,
                'document_name' => 'T & Cs',
                'description' => 'Service Terms and Conditions',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            9 => 
            array (
                'id' => 10,
                'document_name' => 'Contract',
                'description' => 'Agent Contract',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            10 => 
            array (
                'id' => 11,
                'document_name' => 'Others',
                'description' => 'Agent Others',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            11 => 
            array (
                'id' => 12,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            12 => 
            array (
                'id' => 13,
                'document_name' => 'Contract Form',
                'description' => 'Contract Form',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            13 => 
            array (
                'id' => 14,
                'document_name' => 'API Doc',
                'description' => 'API Doc',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            14 => 
            array (
                'id' => 15,
                'document_name' => 'Postcodes',
                'description' => 'Postcodes',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            15 => 
            array (
                'id' => 16,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            16 => 
            array (
                'id' => 17,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            17 => 
            array (
                'id' => 1,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:23:43',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            18 => 
            array (
                'id' => 2,
                'document_name' => 'Agreed Tariif',
                'description' => 'Agreed Tariif',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            19 => 
            array (
                'id' => 3,
                'document_name' => 'Account Form',
                'description' => 'Account Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:38',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            20 => 
            array (
                'id' => 4,
                'document_name' => 'Postcode Form',
                'description' => 'Postcode Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            21 => 
            array (
                'id' => 5,
                'document_name' => 'Dangrous Goods From',
                'description' => 'Dangrous Goods From',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            22 => 
            array (
                'id' => 6,
                'document_name' => 'Contract Form',
                'description' => 'Service Contract Form',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            23 => 
            array (
                'id' => 7,
                'document_name' => 'API Doc',
                'description' => 'Service API Doc',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            24 => 
            array (
                'id' => 8,
                'document_name' => 'Postcodes',
                'description' => 'Service Postcodes',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            25 => 
            array (
                'id' => 9,
                'document_name' => 'T & Cs',
                'description' => 'Service Terms and Conditions',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            26 => 
            array (
                'id' => 10,
                'document_name' => 'Contract',
                'description' => 'Agent Contract',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            27 => 
            array (
                'id' => 11,
                'document_name' => 'Others',
                'description' => 'Agent Others',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            28 => 
            array (
                'id' => 12,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            29 => 
            array (
                'id' => 13,
                'document_name' => 'Contract Form',
                'description' => 'Contract Form',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            30 => 
            array (
                'id' => 14,
                'document_name' => 'API Doc',
                'description' => 'API Doc',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            31 => 
            array (
                'id' => 15,
                'document_name' => 'Postcodes',
                'description' => 'Postcodes',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            32 => 
            array (
                'id' => 16,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            33 => 
            array (
                'id' => 17,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            34 => 
            array (
                'id' => 1,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:23:43',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            35 => 
            array (
                'id' => 2,
                'document_name' => 'Agreed Tariif',
                'description' => 'Agreed Tariif',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            36 => 
            array (
                'id' => 3,
                'document_name' => 'Account Form',
                'description' => 'Account Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:38',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            37 => 
            array (
                'id' => 4,
                'document_name' => 'Postcode Form',
                'description' => 'Postcode Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            38 => 
            array (
                'id' => 5,
                'document_name' => 'Dangrous Goods From',
                'description' => 'Dangrous Goods From',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            39 => 
            array (
                'id' => 6,
                'document_name' => 'Contract Form',
                'description' => 'Service Contract Form',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            40 => 
            array (
                'id' => 7,
                'document_name' => 'API Doc',
                'description' => 'Service API Doc',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            41 => 
            array (
                'id' => 8,
                'document_name' => 'Postcodes',
                'description' => 'Service Postcodes',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            42 => 
            array (
                'id' => 9,
                'document_name' => 'T & Cs',
                'description' => 'Service Terms and Conditions',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            43 => 
            array (
                'id' => 10,
                'document_name' => 'Contract',
                'description' => 'Agent Contract',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            44 => 
            array (
                'id' => 11,
                'document_name' => 'Others',
                'description' => 'Agent Others',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            45 => 
            array (
                'id' => 12,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            46 => 
            array (
                'id' => 13,
                'document_name' => 'Contract Form',
                'description' => 'Contract Form',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            47 => 
            array (
                'id' => 14,
                'document_name' => 'API Doc',
                'description' => 'API Doc',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            48 => 
            array (
                'id' => 15,
                'document_name' => 'Postcodes',
                'description' => 'Postcodes',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            49 => 
            array (
                'id' => 16,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            50 => 
            array (
                'id' => 17,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            51 => 
            array (
                'id' => 1,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:23:43',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            52 => 
            array (
                'id' => 2,
                'document_name' => 'Agreed Tariif',
                'description' => 'Agreed Tariif',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            53 => 
            array (
                'id' => 3,
                'document_name' => 'Account Form',
                'description' => 'Account Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:38',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            54 => 
            array (
                'id' => 4,
                'document_name' => 'Postcode Form',
                'description' => 'Postcode Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            55 => 
            array (
                'id' => 5,
                'document_name' => 'Dangrous Goods From',
                'description' => 'Dangrous Goods From',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            56 => 
            array (
                'id' => 6,
                'document_name' => 'Contract Form',
                'description' => 'Service Contract Form',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            57 => 
            array (
                'id' => 7,
                'document_name' => 'API Doc',
                'description' => 'Service API Doc',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            58 => 
            array (
                'id' => 8,
                'document_name' => 'Postcodes',
                'description' => 'Service Postcodes',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            59 => 
            array (
                'id' => 9,
                'document_name' => 'T & Cs',
                'description' => 'Service Terms and Conditions',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            60 => 
            array (
                'id' => 10,
                'document_name' => 'Contract',
                'description' => 'Agent Contract',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            61 => 
            array (
                'id' => 11,
                'document_name' => 'Others',
                'description' => 'Agent Others',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            62 => 
            array (
                'id' => 12,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            63 => 
            array (
                'id' => 13,
                'document_name' => 'Contract Form',
                'description' => 'Contract Form',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            64 => 
            array (
                'id' => 14,
                'document_name' => 'API Doc',
                'description' => 'API Doc',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            65 => 
            array (
                'id' => 15,
                'document_name' => 'Postcodes',
                'description' => 'Postcodes',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            66 => 
            array (
                'id' => 16,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            67 => 
            array (
                'id' => 17,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            68 => 
            array (
                'id' => 1,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:23:43',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            69 => 
            array (
                'id' => 2,
                'document_name' => 'Agreed Tariif',
                'description' => 'Agreed Tariif',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            70 => 
            array (
                'id' => 3,
                'document_name' => 'Account Form',
                'description' => 'Account Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 00:24:38',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            71 => 
            array (
                'id' => 4,
                'document_name' => 'Postcode Form',
                'description' => 'Postcode Form',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            72 => 
            array (
                'id' => 5,
                'document_name' => 'Dangrous Goods From',
                'description' => 'Dangrous Goods From',
                'document_type' => 'company_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            73 => 
            array (
                'id' => 6,
                'document_name' => 'Contract Form',
                'description' => 'Service Contract Form',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            74 => 
            array (
                'id' => 7,
                'document_name' => 'API Doc',
                'description' => 'Service API Doc',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            75 => 
            array (
                'id' => 8,
                'document_name' => 'Postcodes',
                'description' => 'Service Postcodes',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            76 => 
            array (
                'id' => 9,
                'document_name' => 'T & Cs',
                'description' => 'Service Terms and Conditions',
                'document_type' => 'service_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            77 => 
            array (
                'id' => 10,
                'document_name' => 'Contract',
                'description' => 'Agent Contract',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            78 => 
            array (
                'id' => 11,
                'document_name' => 'Others',
                'description' => 'Agent Others',
                'document_type' => 'agent_contract',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            79 => 
            array (
                'id' => 12,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            80 => 
            array (
                'id' => 13,
                'document_name' => 'Contract Form',
                'description' => 'Contract Form',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            81 => 
            array (
                'id' => 14,
                'document_name' => 'API Doc',
                'description' => 'API Doc',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            82 => 
            array (
                'id' => 15,
                'document_name' => 'Postcodes',
                'description' => 'Postcodes',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            83 => 
            array (
                'id' => 16,
                'document_name' => 'T & Cs',
                'description' => 'T & Cs',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
            84 => 
            array (
                'id' => 17,
                'document_name' => 'Others',
                'description' => 'Others',
                'document_type' => 'service_agent',
                'is_active' => '1',
                'added_by' => 148,
                'added_date' => '2017-10-10 05:40:56',
                'updated_by' => NULL,
                'updated_date' => NULL,
                'is_delete' => '0',
            ),
        ));
        
        
    }
}