<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DomesticsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('domestics')->delete();
        
        \DB::table('domestics')->insert(array (
            0 => 
            array (
                'id' => 11990,
                'postcode_sector' => 'ZE1 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '7',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            1 => 
            array (
                'id' => 11991,
                'postcode_sector' => 'ZE2 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            2 => 
            array (
                'id' => 11992,
                'postcode_sector' => 'ZE3 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            3 => 
            array (
                'id' => 11993,
                'postcode_sector' => 'ZZ71 0',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            4 => 
            array (
                'id' => 11994,
                'postcode_sector' => 'ZZ71',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            5 => 
            array (
                'id' => 11995,
                'postcode_sector' => 'ZZ75 0',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            6 => 
            array (
                'id' => 11996,
                'postcode_sector' => 'ZZ75',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            7 => 
            array (
                'id' => 11997,
                'postcode_sector' => 'ZZ77 0',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            8 => 
            array (
                'id' => 11998,
                'postcode_sector' => 'ZZ77',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            9 => 
            array (
                'id' => 11999,
                'postcode_sector' => 'ZZ78 0',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            10 => 
            array (
                'id' => 12000,
                'postcode_sector' => 'ZZ78',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            11 => 
            array (
                'id' => 11990,
                'postcode_sector' => 'ZE1 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '7',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            12 => 
            array (
                'id' => 11991,
                'postcode_sector' => 'ZE2 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            13 => 
            array (
                'id' => 11992,
                'postcode_sector' => 'ZE3 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            14 => 
            array (
                'id' => 11993,
                'postcode_sector' => 'ZZ71 0',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            15 => 
            array (
                'id' => 11994,
                'postcode_sector' => 'ZZ71',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            16 => 
            array (
                'id' => 11995,
                'postcode_sector' => 'ZZ75 0',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            17 => 
            array (
                'id' => 11996,
                'postcode_sector' => 'ZZ75',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            18 => 
            array (
                'id' => 11997,
                'postcode_sector' => 'ZZ77 0',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            19 => 
            array (
                'id' => 11998,
                'postcode_sector' => 'ZZ77',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            20 => 
            array (
                'id' => 11999,
                'postcode_sector' => 'ZZ78 0',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            21 => 
            array (
                'id' => 12000,
                'postcode_sector' => 'ZZ78',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            22 => 
            array (
                'id' => 11990,
                'postcode_sector' => 'ZE1 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '7',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            23 => 
            array (
                'id' => 11991,
                'postcode_sector' => 'ZE2 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            24 => 
            array (
                'id' => 11992,
                'postcode_sector' => 'ZE3 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            25 => 
            array (
                'id' => 11993,
                'postcode_sector' => 'ZZ71 0',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            26 => 
            array (
                'id' => 11994,
                'postcode_sector' => 'ZZ71',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            27 => 
            array (
                'id' => 11995,
                'postcode_sector' => 'ZZ75 0',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            28 => 
            array (
                'id' => 11996,
                'postcode_sector' => 'ZZ75',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            29 => 
            array (
                'id' => 11997,
                'postcode_sector' => 'ZZ77 0',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            30 => 
            array (
                'id' => 11998,
                'postcode_sector' => 'ZZ77',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            31 => 
            array (
                'id' => 11999,
                'postcode_sector' => 'ZZ78 0',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            32 => 
            array (
                'id' => 12000,
                'postcode_sector' => 'ZZ78',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            33 => 
            array (
                'id' => 11990,
                'postcode_sector' => 'ZE1 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '7',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            34 => 
            array (
                'id' => 11991,
                'postcode_sector' => 'ZE2 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            35 => 
            array (
                'id' => 11992,
                'postcode_sector' => 'ZE3 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            36 => 
            array (
                'id' => 11993,
                'postcode_sector' => 'ZZ71 0',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            37 => 
            array (
                'id' => 11994,
                'postcode_sector' => 'ZZ71',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            38 => 
            array (
                'id' => 11995,
                'postcode_sector' => 'ZZ75 0',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            39 => 
            array (
                'id' => 11996,
                'postcode_sector' => 'ZZ75',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            40 => 
            array (
                'id' => 11997,
                'postcode_sector' => 'ZZ77 0',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            41 => 
            array (
                'id' => 11998,
                'postcode_sector' => 'ZZ77',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            42 => 
            array (
                'id' => 11999,
                'postcode_sector' => 'ZZ78 0',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            43 => 
            array (
                'id' => 12000,
                'postcode_sector' => 'ZZ78',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            44 => 
            array (
                'id' => 11990,
                'postcode_sector' => 'ZE1 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '7',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            45 => 
            array (
                'id' => 11991,
                'postcode_sector' => 'ZE2 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            46 => 
            array (
                'id' => 11992,
                'postcode_sector' => 'ZE3 9',
                'dpd_depot' => '0082',
                'dpd_services_group' => '6',
                'dpd_offshore_zone' => '3221',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0082',
                'ilk_services_group' => '2',
                'ilk_offshore_zone' => '3221',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            47 => 
            array (
                'id' => 11993,
                'postcode_sector' => 'ZZ71 0',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            48 => 
            array (
                'id' => 11994,
                'postcode_sector' => 'ZZ71',
                'dpd_depot' => '0071',
                'dpd_services_group' => '19',
                'dpd_offshore_zone' => '4111',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            49 => 
            array (
                'id' => 11995,
                'postcode_sector' => 'ZZ75 0',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            50 => 
            array (
                'id' => 11996,
                'postcode_sector' => 'ZZ75',
                'dpd_depot' => '0075',
                'dpd_services_group' => '8',
                'dpd_offshore_zone' => '4000',
                'timeslots_code' => '',
                'cluster' => '0',
                'ilk_depot' => '0075',
                'ilk_services_group' => '3',
                'ilk_offshore_zone' => '4000',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            51 => 
            array (
                'id' => 11997,
                'postcode_sector' => 'ZZ77 0',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            52 => 
            array (
                'id' => 11998,
                'postcode_sector' => 'ZZ77',
                'dpd_depot' => '0077',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1903',
                'ilk_services_group' => '68',
                'ilk_offshore_zone' => '9900',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            53 => 
            array (
                'id' => 11999,
                'postcode_sector' => 'ZZ78 0',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
            54 => 
            array (
                'id' => 12000,
                'postcode_sector' => 'ZZ78',
                'dpd_depot' => '0078',
                'dpd_services_group' => '25',
                'dpd_offshore_zone' => '',
                'timeslots_code' => '3',
                'cluster' => '0',
                'ilk_depot' => '1904',
                'ilk_services_group' => '67',
                'ilk_offshore_zone' => '8100',
                'ilk_alternate_service' => '',
                'new_postcode' => '',
            ),
        ));
        
        
    }
}