<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class InvoiceBankDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('invoice_bank_details')->delete();
        
        \DB::table('invoice_bank_details')->insert(array (
            0 => 
            array (
                'id' => 5,
                'user_account_id' => 148,
                'account_title' => 'testing here',
                'account_sortcode' => '2',
                'account_number' => 3,
                'account_iban' => '258',
                'bank_name' => 'test',
                'bank_branch' => 'test',
                'bank_address' => '01004',
                'date_added' => '2018-03-09 10:53:16',
                'added_by' => 58,
                'status' => 1,
            ),
            1 => 
            array (
                'id' => 6,
                'user_account_id' => 2258,
                'account_title' => 'Stellar Test',
                'account_sortcode' => '12345',
                'account_number' => 987654321,
                'account_iban' => '000789',
                'bank_name' => 'Sharjah',
                'bank_branch' => 'Dubai ',
                'bank_address' => 'Test Address 2',
                'date_added' => '2018-09-03 06:02:00',
                'added_by' => 2128,
                'status' => 1,
            ),
            2 => 
            array (
                'id' => 7,
                'user_account_id' => 2265,
                'account_title' => 'testing here',
                'account_sortcode' => '1',
                'account_number' => 1,
                'account_iban' => '1',
                'bank_name' => '1',
                'bank_branch' => '1',
                'bank_address' => 'xx defence, xx defence, pcsir phase',
                'date_added' => '2018-09-03 07:57:56',
                'added_by' => 2139,
                'status' => 1,
            ),
            3 => 
            array (
                'id' => 8,
                'user_account_id' => 2285,
                'account_title' => 'Test Account',
                'account_sortcode' => '7',
                'account_number' => 2147483647,
                'account_iban' => '03e423423',
                'bank_name' => 'Test Bank ',
                'bank_branch' => 'Muslim Town',
                'bank_address' => 'Abrar Centre',
                'date_added' => '2018-11-28 18:09:00',
                'added_by' => 2170,
                'status' => 1,
            ),
            4 => 
            array (
                'id' => 9,
                'user_account_id' => 2297,
                'account_title' => 'Account Title',
                'account_sortcode' => '12121212',
                'account_number' => 25825825,
                'account_iban' => 'IBAN',
                'bank_name' => 'Bank Name',
                'bank_branch' => 'Bank Branch',
                'bank_address' => 'Bank Address',
                'date_added' => '2019-05-16 14:25:59',
                'added_by' => 2191,
                'status' => 1,
            ),
            5 => 
            array (
                'id' => 10,
                'user_account_id' => 148,
                'account_title' => 'testing mruga',
                'account_sortcode' => '203721',
                'account_number' => 123456789,
                'account_iban' => '1234',
                'bank_name' => 'SBI',
                'bank_branch' => 'AHMEDABAD',
                'bank_address' => 'AHMEDABAD',
                'date_added' => '2019-08-21 06:30:08',
                'added_by' => 58,
                'status' => 1,
            ),
            6 => 
            array (
                'id' => 11,
                'user_account_id' => 148,
                'account_title' => 'test1 mruga',
                'account_sortcode' => '203721',
                'account_number' => 1234567891,
                'account_iban' => '1456',
                'bank_name' => 'HDFC',
                'bank_branch' => 'LONDON',
                'bank_address' => 'LONDON',
                'date_added' => '2019-08-22 14:07:20',
                'added_by' => 58,
                'status' => 1,
            ),
            7 => 
            array (
                'id' => 12,
                'user_account_id' => 148,
                'account_title' => 'Test PA POST Account',
                'account_sortcode' => '123',
                'account_number' => 987612345,
                'account_iban' => '9510357',
                'bank_name' => 'HBL',
                'bank_branch' => 'Wahdat Road',
                'bank_address' => 'Commercial Plot # 4 Wahdat Road',
                'date_added' => '2019-12-13 12:29:56',
                'added_by' => 58,
                'status' => 1,
            ),
            8 => 
            array (
                'id' => 5,
                'user_account_id' => 148,
                'account_title' => 'testing here',
                'account_sortcode' => '2',
                'account_number' => 3,
                'account_iban' => '258',
                'bank_name' => 'test',
                'bank_branch' => 'test',
                'bank_address' => '01004',
                'date_added' => '2018-03-09 10:53:16',
                'added_by' => 58,
                'status' => 1,
            ),
            9 => 
            array (
                'id' => 6,
                'user_account_id' => 2258,
                'account_title' => 'Stellar Test',
                'account_sortcode' => '12345',
                'account_number' => 987654321,
                'account_iban' => '000789',
                'bank_name' => 'Sharjah',
                'bank_branch' => 'Dubai ',
                'bank_address' => 'Test Address 2',
                'date_added' => '2018-09-03 06:02:00',
                'added_by' => 2128,
                'status' => 1,
            ),
            10 => 
            array (
                'id' => 7,
                'user_account_id' => 2265,
                'account_title' => 'testing here',
                'account_sortcode' => '1',
                'account_number' => 1,
                'account_iban' => '1',
                'bank_name' => '1',
                'bank_branch' => '1',
                'bank_address' => 'xx defence, xx defence, pcsir phase',
                'date_added' => '2018-09-03 07:57:56',
                'added_by' => 2139,
                'status' => 1,
            ),
            11 => 
            array (
                'id' => 8,
                'user_account_id' => 2285,
                'account_title' => 'Test Account',
                'account_sortcode' => '7',
                'account_number' => 2147483647,
                'account_iban' => '03e423423',
                'bank_name' => 'Test Bank ',
                'bank_branch' => 'Muslim Town',
                'bank_address' => 'Abrar Centre',
                'date_added' => '2018-11-28 18:09:00',
                'added_by' => 2170,
                'status' => 1,
            ),
            12 => 
            array (
                'id' => 9,
                'user_account_id' => 2297,
                'account_title' => 'Account Title',
                'account_sortcode' => '12121212',
                'account_number' => 25825825,
                'account_iban' => 'IBAN',
                'bank_name' => 'Bank Name',
                'bank_branch' => 'Bank Branch',
                'bank_address' => 'Bank Address',
                'date_added' => '2019-05-16 14:25:59',
                'added_by' => 2191,
                'status' => 1,
            ),
            13 => 
            array (
                'id' => 10,
                'user_account_id' => 148,
                'account_title' => 'testing mruga',
                'account_sortcode' => '203721',
                'account_number' => 123456789,
                'account_iban' => '1234',
                'bank_name' => 'SBI',
                'bank_branch' => 'AHMEDABAD',
                'bank_address' => 'AHMEDABAD',
                'date_added' => '2019-08-21 06:30:08',
                'added_by' => 58,
                'status' => 1,
            ),
            14 => 
            array (
                'id' => 11,
                'user_account_id' => 148,
                'account_title' => 'test1 mruga',
                'account_sortcode' => '203721',
                'account_number' => 1234567891,
                'account_iban' => '1456',
                'bank_name' => 'HDFC',
                'bank_branch' => 'LONDON',
                'bank_address' => 'LONDON',
                'date_added' => '2019-08-22 14:07:20',
                'added_by' => 58,
                'status' => 1,
            ),
            15 => 
            array (
                'id' => 12,
                'user_account_id' => 148,
                'account_title' => 'Test PA POST Account',
                'account_sortcode' => '123',
                'account_number' => 987612345,
                'account_iban' => '9510357',
                'bank_name' => 'HBL',
                'bank_branch' => 'Wahdat Road',
                'bank_address' => 'Commercial Plot # 4 Wahdat Road',
                'date_added' => '2019-12-13 12:29:56',
                'added_by' => 58,
                'status' => 1,
            ),
            16 => 
            array (
                'id' => 5,
                'user_account_id' => 148,
                'account_title' => 'testing here',
                'account_sortcode' => '2',
                'account_number' => 3,
                'account_iban' => '258',
                'bank_name' => 'test',
                'bank_branch' => 'test',
                'bank_address' => '01004',
                'date_added' => '2018-03-09 10:53:16',
                'added_by' => 58,
                'status' => 1,
            ),
            17 => 
            array (
                'id' => 6,
                'user_account_id' => 2258,
                'account_title' => 'Stellar Test',
                'account_sortcode' => '12345',
                'account_number' => 987654321,
                'account_iban' => '000789',
                'bank_name' => 'Sharjah',
                'bank_branch' => 'Dubai ',
                'bank_address' => 'Test Address 2',
                'date_added' => '2018-09-03 06:02:00',
                'added_by' => 2128,
                'status' => 1,
            ),
            18 => 
            array (
                'id' => 7,
                'user_account_id' => 2265,
                'account_title' => 'testing here',
                'account_sortcode' => '1',
                'account_number' => 1,
                'account_iban' => '1',
                'bank_name' => '1',
                'bank_branch' => '1',
                'bank_address' => 'xx defence, xx defence, pcsir phase',
                'date_added' => '2018-09-03 07:57:56',
                'added_by' => 2139,
                'status' => 1,
            ),
            19 => 
            array (
                'id' => 8,
                'user_account_id' => 2285,
                'account_title' => 'Test Account',
                'account_sortcode' => '7',
                'account_number' => 2147483647,
                'account_iban' => '03e423423',
                'bank_name' => 'Test Bank ',
                'bank_branch' => 'Muslim Town',
                'bank_address' => 'Abrar Centre',
                'date_added' => '2018-11-28 18:09:00',
                'added_by' => 2170,
                'status' => 1,
            ),
            20 => 
            array (
                'id' => 9,
                'user_account_id' => 2297,
                'account_title' => 'Account Title',
                'account_sortcode' => '12121212',
                'account_number' => 25825825,
                'account_iban' => 'IBAN',
                'bank_name' => 'Bank Name',
                'bank_branch' => 'Bank Branch',
                'bank_address' => 'Bank Address',
                'date_added' => '2019-05-16 14:25:59',
                'added_by' => 2191,
                'status' => 1,
            ),
            21 => 
            array (
                'id' => 10,
                'user_account_id' => 148,
                'account_title' => 'testing mruga',
                'account_sortcode' => '203721',
                'account_number' => 123456789,
                'account_iban' => '1234',
                'bank_name' => 'SBI',
                'bank_branch' => 'AHMEDABAD',
                'bank_address' => 'AHMEDABAD',
                'date_added' => '2019-08-21 06:30:08',
                'added_by' => 58,
                'status' => 1,
            ),
            22 => 
            array (
                'id' => 11,
                'user_account_id' => 148,
                'account_title' => 'test1 mruga',
                'account_sortcode' => '203721',
                'account_number' => 1234567891,
                'account_iban' => '1456',
                'bank_name' => 'HDFC',
                'bank_branch' => 'LONDON',
                'bank_address' => 'LONDON',
                'date_added' => '2019-08-22 14:07:20',
                'added_by' => 58,
                'status' => 1,
            ),
            23 => 
            array (
                'id' => 12,
                'user_account_id' => 148,
                'account_title' => 'Test PA POST Account',
                'account_sortcode' => '123',
                'account_number' => 987612345,
                'account_iban' => '9510357',
                'bank_name' => 'HBL',
                'bank_branch' => 'Wahdat Road',
                'bank_address' => 'Commercial Plot # 4 Wahdat Road',
                'date_added' => '2019-12-13 12:29:56',
                'added_by' => 58,
                'status' => 1,
            ),
            24 => 
            array (
                'id' => 5,
                'user_account_id' => 148,
                'account_title' => 'testing here',
                'account_sortcode' => '2',
                'account_number' => 3,
                'account_iban' => '258',
                'bank_name' => 'test',
                'bank_branch' => 'test',
                'bank_address' => '01004',
                'date_added' => '2018-03-09 10:53:16',
                'added_by' => 58,
                'status' => 1,
            ),
            25 => 
            array (
                'id' => 6,
                'user_account_id' => 2258,
                'account_title' => 'Stellar Test',
                'account_sortcode' => '12345',
                'account_number' => 987654321,
                'account_iban' => '000789',
                'bank_name' => 'Sharjah',
                'bank_branch' => 'Dubai ',
                'bank_address' => 'Test Address 2',
                'date_added' => '2018-09-03 06:02:00',
                'added_by' => 2128,
                'status' => 1,
            ),
            26 => 
            array (
                'id' => 7,
                'user_account_id' => 2265,
                'account_title' => 'testing here',
                'account_sortcode' => '1',
                'account_number' => 1,
                'account_iban' => '1',
                'bank_name' => '1',
                'bank_branch' => '1',
                'bank_address' => 'xx defence, xx defence, pcsir phase',
                'date_added' => '2018-09-03 07:57:56',
                'added_by' => 2139,
                'status' => 1,
            ),
            27 => 
            array (
                'id' => 8,
                'user_account_id' => 2285,
                'account_title' => 'Test Account',
                'account_sortcode' => '7',
                'account_number' => 2147483647,
                'account_iban' => '03e423423',
                'bank_name' => 'Test Bank ',
                'bank_branch' => 'Muslim Town',
                'bank_address' => 'Abrar Centre',
                'date_added' => '2018-11-28 18:09:00',
                'added_by' => 2170,
                'status' => 1,
            ),
            28 => 
            array (
                'id' => 9,
                'user_account_id' => 2297,
                'account_title' => 'Account Title',
                'account_sortcode' => '12121212',
                'account_number' => 25825825,
                'account_iban' => 'IBAN',
                'bank_name' => 'Bank Name',
                'bank_branch' => 'Bank Branch',
                'bank_address' => 'Bank Address',
                'date_added' => '2019-05-16 14:25:59',
                'added_by' => 2191,
                'status' => 1,
            ),
            29 => 
            array (
                'id' => 10,
                'user_account_id' => 148,
                'account_title' => 'testing mruga',
                'account_sortcode' => '203721',
                'account_number' => 123456789,
                'account_iban' => '1234',
                'bank_name' => 'SBI',
                'bank_branch' => 'AHMEDABAD',
                'bank_address' => 'AHMEDABAD',
                'date_added' => '2019-08-21 06:30:08',
                'added_by' => 58,
                'status' => 1,
            ),
            30 => 
            array (
                'id' => 11,
                'user_account_id' => 148,
                'account_title' => 'test1 mruga',
                'account_sortcode' => '203721',
                'account_number' => 1234567891,
                'account_iban' => '1456',
                'bank_name' => 'HDFC',
                'bank_branch' => 'LONDON',
                'bank_address' => 'LONDON',
                'date_added' => '2019-08-22 14:07:20',
                'added_by' => 58,
                'status' => 1,
            ),
            31 => 
            array (
                'id' => 12,
                'user_account_id' => 148,
                'account_title' => 'Test PA POST Account',
                'account_sortcode' => '123',
                'account_number' => 987612345,
                'account_iban' => '9510357',
                'bank_name' => 'HBL',
                'bank_branch' => 'Wahdat Road',
                'bank_address' => 'Commercial Plot # 4 Wahdat Road',
                'date_added' => '2019-12-13 12:29:56',
                'added_by' => 58,
                'status' => 1,
            ),
            32 => 
            array (
                'id' => 5,
                'user_account_id' => 148,
                'account_title' => 'testing here',
                'account_sortcode' => '2',
                'account_number' => 3,
                'account_iban' => '258',
                'bank_name' => 'test',
                'bank_branch' => 'test',
                'bank_address' => '01004',
                'date_added' => '2018-03-09 10:53:16',
                'added_by' => 58,
                'status' => 1,
            ),
            33 => 
            array (
                'id' => 6,
                'user_account_id' => 2258,
                'account_title' => 'Stellar Test',
                'account_sortcode' => '12345',
                'account_number' => 987654321,
                'account_iban' => '000789',
                'bank_name' => 'Sharjah',
                'bank_branch' => 'Dubai ',
                'bank_address' => 'Test Address 2',
                'date_added' => '2018-09-03 06:02:00',
                'added_by' => 2128,
                'status' => 1,
            ),
            34 => 
            array (
                'id' => 7,
                'user_account_id' => 2265,
                'account_title' => 'testing here',
                'account_sortcode' => '1',
                'account_number' => 1,
                'account_iban' => '1',
                'bank_name' => '1',
                'bank_branch' => '1',
                'bank_address' => 'xx defence, xx defence, pcsir phase',
                'date_added' => '2018-09-03 07:57:56',
                'added_by' => 2139,
                'status' => 1,
            ),
            35 => 
            array (
                'id' => 8,
                'user_account_id' => 2285,
                'account_title' => 'Test Account',
                'account_sortcode' => '7',
                'account_number' => 2147483647,
                'account_iban' => '03e423423',
                'bank_name' => 'Test Bank ',
                'bank_branch' => 'Muslim Town',
                'bank_address' => 'Abrar Centre',
                'date_added' => '2018-11-28 18:09:00',
                'added_by' => 2170,
                'status' => 1,
            ),
            36 => 
            array (
                'id' => 9,
                'user_account_id' => 2297,
                'account_title' => 'Account Title',
                'account_sortcode' => '12121212',
                'account_number' => 25825825,
                'account_iban' => 'IBAN',
                'bank_name' => 'Bank Name',
                'bank_branch' => 'Bank Branch',
                'bank_address' => 'Bank Address',
                'date_added' => '2019-05-16 14:25:59',
                'added_by' => 2191,
                'status' => 1,
            ),
            37 => 
            array (
                'id' => 10,
                'user_account_id' => 148,
                'account_title' => 'testing mruga',
                'account_sortcode' => '203721',
                'account_number' => 123456789,
                'account_iban' => '1234',
                'bank_name' => 'SBI',
                'bank_branch' => 'AHMEDABAD',
                'bank_address' => 'AHMEDABAD',
                'date_added' => '2019-08-21 06:30:08',
                'added_by' => 58,
                'status' => 1,
            ),
            38 => 
            array (
                'id' => 11,
                'user_account_id' => 148,
                'account_title' => 'test1 mruga',
                'account_sortcode' => '203721',
                'account_number' => 1234567891,
                'account_iban' => '1456',
                'bank_name' => 'HDFC',
                'bank_branch' => 'LONDON',
                'bank_address' => 'LONDON',
                'date_added' => '2019-08-22 14:07:20',
                'added_by' => 58,
                'status' => 1,
            ),
            39 => 
            array (
                'id' => 12,
                'user_account_id' => 148,
                'account_title' => 'Test PA POST Account',
                'account_sortcode' => '123',
                'account_number' => 987612345,
                'account_iban' => '9510357',
                'bank_name' => 'HBL',
                'bank_branch' => 'Wahdat Road',
                'bank_address' => 'Commercial Plot # 4 Wahdat Road',
                'date_added' => '2019-12-13 12:29:56',
                'added_by' => 58,
                'status' => 1,
            ),
        ));
        
        
    }
}