<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LicencePlateCountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('licence_plate_countries')->delete();
        
        \DB::table('licence_plate_countries')->insert(array (
            0 => 
            array (
                'id' => 3,
                'licence_plate_id' => 112,
                'country_id' => 13,
                'range_name' => 'Sweden Post Australia',
                'range_start' => 91713500,
                'range_end' => 91713999,
                'next_number' => 91713531,
                'increment_date' => NULL,
                'prefix' => 'LX',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:37:25',
                'date_updated' => '2018-03-07 12:37:25',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            1 => 
            array (
                'id' => 4,
                'licence_plate_id' => 112,
                'country_id' => 38,
                'range_name' => 'Sweden Post Canada',
                'range_start' => 61495600,
                'range_end' => 61496099,
                'next_number' => 61495615,
                'increment_date' => NULL,
                'prefix' => 'LB',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:44:34',
                'date_updated' => '2018-03-07 12:44:34',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            2 => 
            array (
                'id' => 5,
                'licence_plate_id' => 128,
                'country_id' => 18,
                'range_name' => 'Test',
                'range_start' => 1,
                'range_end' => 500,
                'next_number' => 1,
                'increment_date' => NULL,
                'prefix' => '',
                'sufix' => '',
                'date_created' => '2018-07-27 17:00:13',
                'date_updated' => '2018-07-27 17:00:13',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            3 => 
            array (
                'id' => 6,
                'licence_plate_id' => 112,
                'country_id' => 5,
                'range_name' => 'Sweden Post Andorra',
                'range_start' => 91714500,
                'range_end' => 91714999,
                'next_number' => 91714525,
                'increment_date' => NULL,
                'prefix' => 'RE',
                'sufix' => '',
                'date_created' => '2019-02-05 13:42:52',
                'date_updated' => '2019-02-05 13:42:52',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            4 => 
            array (
                'id' => 3,
                'licence_plate_id' => 112,
                'country_id' => 13,
                'range_name' => 'Sweden Post Australia',
                'range_start' => 91713500,
                'range_end' => 91713999,
                'next_number' => 91713531,
                'increment_date' => NULL,
                'prefix' => 'LX',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:37:25',
                'date_updated' => '2018-03-07 12:37:25',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            5 => 
            array (
                'id' => 4,
                'licence_plate_id' => 112,
                'country_id' => 38,
                'range_name' => 'Sweden Post Canada',
                'range_start' => 61495600,
                'range_end' => 61496099,
                'next_number' => 61495615,
                'increment_date' => NULL,
                'prefix' => 'LB',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:44:34',
                'date_updated' => '2018-03-07 12:44:34',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            6 => 
            array (
                'id' => 5,
                'licence_plate_id' => 128,
                'country_id' => 18,
                'range_name' => 'Test',
                'range_start' => 1,
                'range_end' => 500,
                'next_number' => 1,
                'increment_date' => NULL,
                'prefix' => '',
                'sufix' => '',
                'date_created' => '2018-07-27 17:00:13',
                'date_updated' => '2018-07-27 17:00:13',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            7 => 
            array (
                'id' => 6,
                'licence_plate_id' => 112,
                'country_id' => 5,
                'range_name' => 'Sweden Post Andorra',
                'range_start' => 91714500,
                'range_end' => 91714999,
                'next_number' => 91714525,
                'increment_date' => NULL,
                'prefix' => 'RE',
                'sufix' => '',
                'date_created' => '2019-02-05 13:42:52',
                'date_updated' => '2019-02-05 13:42:52',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            8 => 
            array (
                'id' => 3,
                'licence_plate_id' => 112,
                'country_id' => 13,
                'range_name' => 'Sweden Post Australia',
                'range_start' => 91713500,
                'range_end' => 91713999,
                'next_number' => 91713531,
                'increment_date' => NULL,
                'prefix' => 'LX',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:37:25',
                'date_updated' => '2018-03-07 12:37:25',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            9 => 
            array (
                'id' => 4,
                'licence_plate_id' => 112,
                'country_id' => 38,
                'range_name' => 'Sweden Post Canada',
                'range_start' => 61495600,
                'range_end' => 61496099,
                'next_number' => 61495615,
                'increment_date' => NULL,
                'prefix' => 'LB',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:44:34',
                'date_updated' => '2018-03-07 12:44:34',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            10 => 
            array (
                'id' => 5,
                'licence_plate_id' => 128,
                'country_id' => 18,
                'range_name' => 'Test',
                'range_start' => 1,
                'range_end' => 500,
                'next_number' => 1,
                'increment_date' => NULL,
                'prefix' => '',
                'sufix' => '',
                'date_created' => '2018-07-27 17:00:13',
                'date_updated' => '2018-07-27 17:00:13',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            11 => 
            array (
                'id' => 6,
                'licence_plate_id' => 112,
                'country_id' => 5,
                'range_name' => 'Sweden Post Andorra',
                'range_start' => 91714500,
                'range_end' => 91714999,
                'next_number' => 91714525,
                'increment_date' => NULL,
                'prefix' => 'RE',
                'sufix' => '',
                'date_created' => '2019-02-05 13:42:52',
                'date_updated' => '2019-02-05 13:42:52',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            12 => 
            array (
                'id' => 3,
                'licence_plate_id' => 112,
                'country_id' => 13,
                'range_name' => 'Sweden Post Australia',
                'range_start' => 91713500,
                'range_end' => 91713999,
                'next_number' => 91713531,
                'increment_date' => NULL,
                'prefix' => 'LX',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:37:25',
                'date_updated' => '2018-03-07 12:37:25',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            13 => 
            array (
                'id' => 4,
                'licence_plate_id' => 112,
                'country_id' => 38,
                'range_name' => 'Sweden Post Canada',
                'range_start' => 61495600,
                'range_end' => 61496099,
                'next_number' => 61495615,
                'increment_date' => NULL,
                'prefix' => 'LB',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:44:34',
                'date_updated' => '2018-03-07 12:44:34',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            14 => 
            array (
                'id' => 5,
                'licence_plate_id' => 128,
                'country_id' => 18,
                'range_name' => 'Test',
                'range_start' => 1,
                'range_end' => 500,
                'next_number' => 1,
                'increment_date' => NULL,
                'prefix' => '',
                'sufix' => '',
                'date_created' => '2018-07-27 17:00:13',
                'date_updated' => '2018-07-27 17:00:13',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            15 => 
            array (
                'id' => 6,
                'licence_plate_id' => 112,
                'country_id' => 5,
                'range_name' => 'Sweden Post Andorra',
                'range_start' => 91714500,
                'range_end' => 91714999,
                'next_number' => 91714525,
                'increment_date' => NULL,
                'prefix' => 'RE',
                'sufix' => '',
                'date_created' => '2019-02-05 13:42:52',
                'date_updated' => '2019-02-05 13:42:52',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            16 => 
            array (
                'id' => 3,
                'licence_plate_id' => 112,
                'country_id' => 13,
                'range_name' => 'Sweden Post Australia',
                'range_start' => 91713500,
                'range_end' => 91713999,
                'next_number' => 91713531,
                'increment_date' => NULL,
                'prefix' => 'LX',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:37:25',
                'date_updated' => '2018-03-07 12:37:25',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            17 => 
            array (
                'id' => 4,
                'licence_plate_id' => 112,
                'country_id' => 38,
                'range_name' => 'Sweden Post Canada',
                'range_start' => 61495600,
                'range_end' => 61496099,
                'next_number' => 61495615,
                'increment_date' => NULL,
                'prefix' => 'LB',
                'sufix' => 'SE',
                'date_created' => '2018-03-07 12:44:34',
                'date_updated' => '2018-03-07 12:44:34',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            18 => 
            array (
                'id' => 5,
                'licence_plate_id' => 128,
                'country_id' => 18,
                'range_name' => 'Test',
                'range_start' => 1,
                'range_end' => 500,
                'next_number' => 1,
                'increment_date' => NULL,
                'prefix' => '',
                'sufix' => '',
                'date_created' => '2018-07-27 17:00:13',
                'date_updated' => '2018-07-27 17:00:13',
                'addedby' => 58,
                'updatedby' => 58,
            ),
            19 => 
            array (
                'id' => 6,
                'licence_plate_id' => 112,
                'country_id' => 5,
                'range_name' => 'Sweden Post Andorra',
                'range_start' => 91714500,
                'range_end' => 91714999,
                'next_number' => 91714525,
                'increment_date' => NULL,
                'prefix' => 'RE',
                'sufix' => '',
                'date_created' => '2019-02-05 13:42:52',
                'date_updated' => '2019-02-05 13:42:52',
                'addedby' => 58,
                'updatedby' => 58,
            ),
        ));
        
        
    }
}