<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MarketplaceOrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('marketplace_order_details')->delete();
        
        \DB::table('marketplace_order_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '1',
                'sku' => '',
                'title' => 'Ship Your Idea - Blue',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '30',
                'currency' => 'USD',
            ),
            1 => 
            array (
                'id' => 2,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '2',
                'sku' => '',
                'title' => 'Happy Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '18',
                'currency' => 'USD',
            ),
            2 => 
            array (
                'id' => 3,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '3',
                'sku' => '',
                'title' => 'Ninja Silhouette',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            3 => 
            array (
                'id' => 4,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '4',
                'sku' => '',
                'title' => 'Woo Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            4 => 
            array (
                'id' => 5,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '5',
                'sku' => '',
                'title' => 'Woo Single #2',
                'quantity_purchased' => '3',
                'asin' => '',
                'item_price' => '6',
                'currency' => 'USD',
            ),
            5 => 
            array (
                'id' => 6,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '7',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            6 => 
            array (
                'id' => 7,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '8',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            7 => 
            array (
                'id' => 8,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '10',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            8 => 
            array (
                'id' => 9,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '11',
                'sku' => '',
                'title' => 'Luxury Watche',
                'quantity_purchased' => '8',
                'asin' => '',
                'item_price' => '4320',
                'currency' => 'USD',
            ),
            9 => 
            array (
                'id' => 10,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '12',
                'sku' => '',
                'title' => 'Intel Laptop',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            10 => 
            array (
                'id' => 11,
                'marketplace_order_id' => 4,
                'marketplace_item_id' => '14',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '540',
                'currency' => 'USD',
            ),
            11 => 
            array (
                'id' => 12,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '16',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            12 => 
            array (
                'id' => 13,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '17',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            13 => 
            array (
                'id' => 14,
                'marketplace_order_id' => 6,
                'marketplace_item_id' => '19',
                'sku' => '',
                'title' => 'Core i7 Laptop',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '125',
                'currency' => 'USD',
            ),
            14 => 
            array (
                'id' => 15,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '21',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '2',
                'asin' => '',
                'item_price' => '440',
                'currency' => 'USD',
            ),
            15 => 
            array (
                'id' => 16,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '22',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            16 => 
            array (
                'id' => 17,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '23',
                'sku' => '',
                'title' => '7th Generation',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '520',
                'currency' => 'USD',
            ),
            17 => 
            array (
                'id' => 18,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '24',
                'sku' => '',
                'title' => 'Bluetooth Speaker',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '70',
                'currency' => 'USD',
            ),
            18 => 
            array (
                'id' => 19,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '25',
                'sku' => '',
                'title' => 'Branch Apple',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '12',
                'currency' => 'USD',
            ),
            19 => 
            array (
                'id' => 20,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '26',
                'sku' => '',
                'title' => 'Bracelet Watch',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '40',
                'currency' => 'USD',
            ),
            20 => 
            array (
                'id' => 21,
                'marketplace_order_id' => 8,
                'marketplace_item_id' => '28',
                'sku' => '',
                'title' => 'Goldenhour Watch',
                'quantity_purchased' => '4',
                'asin' => '',
                'item_price' => '240',
                'currency' => 'USD',
            ),
            21 => 
            array (
                'id' => 22,
                'marketplace_order_id' => 9,
                'marketplace_item_id' => '30',
                'sku' => '',
                'title' => 'Silicon Orange Juice',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '14',
                'currency' => 'USD',
            ),
            22 => 
            array (
                'id' => 23,
                'marketplace_order_id' => 10,
                'marketplace_item_id' => '32',
                'sku' => '',
                'title' => 'Pionner Men Casual Short Sleeve',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '29',
                'currency' => 'USD',
            ),
            23 => 
            array (
                'id' => 24,
                'marketplace_order_id' => 11,
                'marketplace_item_id' => '56',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            24 => 
            array (
                'id' => 1,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '1',
                'sku' => '',
                'title' => 'Ship Your Idea - Blue',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '30',
                'currency' => 'USD',
            ),
            25 => 
            array (
                'id' => 2,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '2',
                'sku' => '',
                'title' => 'Happy Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '18',
                'currency' => 'USD',
            ),
            26 => 
            array (
                'id' => 3,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '3',
                'sku' => '',
                'title' => 'Ninja Silhouette',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            27 => 
            array (
                'id' => 4,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '4',
                'sku' => '',
                'title' => 'Woo Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            28 => 
            array (
                'id' => 5,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '5',
                'sku' => '',
                'title' => 'Woo Single #2',
                'quantity_purchased' => '3',
                'asin' => '',
                'item_price' => '6',
                'currency' => 'USD',
            ),
            29 => 
            array (
                'id' => 6,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '7',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            30 => 
            array (
                'id' => 7,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '8',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            31 => 
            array (
                'id' => 8,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '10',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            32 => 
            array (
                'id' => 9,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '11',
                'sku' => '',
                'title' => 'Luxury Watche',
                'quantity_purchased' => '8',
                'asin' => '',
                'item_price' => '4320',
                'currency' => 'USD',
            ),
            33 => 
            array (
                'id' => 10,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '12',
                'sku' => '',
                'title' => 'Intel Laptop',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            34 => 
            array (
                'id' => 11,
                'marketplace_order_id' => 4,
                'marketplace_item_id' => '14',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '540',
                'currency' => 'USD',
            ),
            35 => 
            array (
                'id' => 12,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '16',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            36 => 
            array (
                'id' => 13,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '17',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            37 => 
            array (
                'id' => 14,
                'marketplace_order_id' => 6,
                'marketplace_item_id' => '19',
                'sku' => '',
                'title' => 'Core i7 Laptop',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '125',
                'currency' => 'USD',
            ),
            38 => 
            array (
                'id' => 15,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '21',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '2',
                'asin' => '',
                'item_price' => '440',
                'currency' => 'USD',
            ),
            39 => 
            array (
                'id' => 16,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '22',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            40 => 
            array (
                'id' => 17,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '23',
                'sku' => '',
                'title' => '7th Generation',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '520',
                'currency' => 'USD',
            ),
            41 => 
            array (
                'id' => 18,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '24',
                'sku' => '',
                'title' => 'Bluetooth Speaker',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '70',
                'currency' => 'USD',
            ),
            42 => 
            array (
                'id' => 19,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '25',
                'sku' => '',
                'title' => 'Branch Apple',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '12',
                'currency' => 'USD',
            ),
            43 => 
            array (
                'id' => 20,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '26',
                'sku' => '',
                'title' => 'Bracelet Watch',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '40',
                'currency' => 'USD',
            ),
            44 => 
            array (
                'id' => 21,
                'marketplace_order_id' => 8,
                'marketplace_item_id' => '28',
                'sku' => '',
                'title' => 'Goldenhour Watch',
                'quantity_purchased' => '4',
                'asin' => '',
                'item_price' => '240',
                'currency' => 'USD',
            ),
            45 => 
            array (
                'id' => 22,
                'marketplace_order_id' => 9,
                'marketplace_item_id' => '30',
                'sku' => '',
                'title' => 'Silicon Orange Juice',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '14',
                'currency' => 'USD',
            ),
            46 => 
            array (
                'id' => 23,
                'marketplace_order_id' => 10,
                'marketplace_item_id' => '32',
                'sku' => '',
                'title' => 'Pionner Men Casual Short Sleeve',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '29',
                'currency' => 'USD',
            ),
            47 => 
            array (
                'id' => 24,
                'marketplace_order_id' => 11,
                'marketplace_item_id' => '56',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            48 => 
            array (
                'id' => 1,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '1',
                'sku' => '',
                'title' => 'Ship Your Idea - Blue',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '30',
                'currency' => 'USD',
            ),
            49 => 
            array (
                'id' => 2,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '2',
                'sku' => '',
                'title' => 'Happy Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '18',
                'currency' => 'USD',
            ),
            50 => 
            array (
                'id' => 3,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '3',
                'sku' => '',
                'title' => 'Ninja Silhouette',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            51 => 
            array (
                'id' => 4,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '4',
                'sku' => '',
                'title' => 'Woo Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            52 => 
            array (
                'id' => 5,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '5',
                'sku' => '',
                'title' => 'Woo Single #2',
                'quantity_purchased' => '3',
                'asin' => '',
                'item_price' => '6',
                'currency' => 'USD',
            ),
            53 => 
            array (
                'id' => 6,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '7',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            54 => 
            array (
                'id' => 7,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '8',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            55 => 
            array (
                'id' => 8,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '10',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            56 => 
            array (
                'id' => 9,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '11',
                'sku' => '',
                'title' => 'Luxury Watche',
                'quantity_purchased' => '8',
                'asin' => '',
                'item_price' => '4320',
                'currency' => 'USD',
            ),
            57 => 
            array (
                'id' => 10,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '12',
                'sku' => '',
                'title' => 'Intel Laptop',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            58 => 
            array (
                'id' => 11,
                'marketplace_order_id' => 4,
                'marketplace_item_id' => '14',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '540',
                'currency' => 'USD',
            ),
            59 => 
            array (
                'id' => 12,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '16',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            60 => 
            array (
                'id' => 13,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '17',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            61 => 
            array (
                'id' => 14,
                'marketplace_order_id' => 6,
                'marketplace_item_id' => '19',
                'sku' => '',
                'title' => 'Core i7 Laptop',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '125',
                'currency' => 'USD',
            ),
            62 => 
            array (
                'id' => 15,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '21',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '2',
                'asin' => '',
                'item_price' => '440',
                'currency' => 'USD',
            ),
            63 => 
            array (
                'id' => 16,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '22',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            64 => 
            array (
                'id' => 17,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '23',
                'sku' => '',
                'title' => '7th Generation',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '520',
                'currency' => 'USD',
            ),
            65 => 
            array (
                'id' => 18,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '24',
                'sku' => '',
                'title' => 'Bluetooth Speaker',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '70',
                'currency' => 'USD',
            ),
            66 => 
            array (
                'id' => 19,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '25',
                'sku' => '',
                'title' => 'Branch Apple',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '12',
                'currency' => 'USD',
            ),
            67 => 
            array (
                'id' => 20,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '26',
                'sku' => '',
                'title' => 'Bracelet Watch',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '40',
                'currency' => 'USD',
            ),
            68 => 
            array (
                'id' => 21,
                'marketplace_order_id' => 8,
                'marketplace_item_id' => '28',
                'sku' => '',
                'title' => 'Goldenhour Watch',
                'quantity_purchased' => '4',
                'asin' => '',
                'item_price' => '240',
                'currency' => 'USD',
            ),
            69 => 
            array (
                'id' => 22,
                'marketplace_order_id' => 9,
                'marketplace_item_id' => '30',
                'sku' => '',
                'title' => 'Silicon Orange Juice',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '14',
                'currency' => 'USD',
            ),
            70 => 
            array (
                'id' => 23,
                'marketplace_order_id' => 10,
                'marketplace_item_id' => '32',
                'sku' => '',
                'title' => 'Pionner Men Casual Short Sleeve',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '29',
                'currency' => 'USD',
            ),
            71 => 
            array (
                'id' => 24,
                'marketplace_order_id' => 11,
                'marketplace_item_id' => '56',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            72 => 
            array (
                'id' => 1,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '1',
                'sku' => '',
                'title' => 'Ship Your Idea - Blue',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '30',
                'currency' => 'USD',
            ),
            73 => 
            array (
                'id' => 2,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '2',
                'sku' => '',
                'title' => 'Happy Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '18',
                'currency' => 'USD',
            ),
            74 => 
            array (
                'id' => 3,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '3',
                'sku' => '',
                'title' => 'Ninja Silhouette',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            75 => 
            array (
                'id' => 4,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '4',
                'sku' => '',
                'title' => 'Woo Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            76 => 
            array (
                'id' => 5,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '5',
                'sku' => '',
                'title' => 'Woo Single #2',
                'quantity_purchased' => '3',
                'asin' => '',
                'item_price' => '6',
                'currency' => 'USD',
            ),
            77 => 
            array (
                'id' => 6,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '7',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            78 => 
            array (
                'id' => 7,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '8',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            79 => 
            array (
                'id' => 8,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '10',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            80 => 
            array (
                'id' => 9,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '11',
                'sku' => '',
                'title' => 'Luxury Watche',
                'quantity_purchased' => '8',
                'asin' => '',
                'item_price' => '4320',
                'currency' => 'USD',
            ),
            81 => 
            array (
                'id' => 10,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '12',
                'sku' => '',
                'title' => 'Intel Laptop',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            82 => 
            array (
                'id' => 11,
                'marketplace_order_id' => 4,
                'marketplace_item_id' => '14',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '540',
                'currency' => 'USD',
            ),
            83 => 
            array (
                'id' => 12,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '16',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            84 => 
            array (
                'id' => 13,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '17',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            85 => 
            array (
                'id' => 14,
                'marketplace_order_id' => 6,
                'marketplace_item_id' => '19',
                'sku' => '',
                'title' => 'Core i7 Laptop',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '125',
                'currency' => 'USD',
            ),
            86 => 
            array (
                'id' => 15,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '21',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '2',
                'asin' => '',
                'item_price' => '440',
                'currency' => 'USD',
            ),
            87 => 
            array (
                'id' => 16,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '22',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            88 => 
            array (
                'id' => 17,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '23',
                'sku' => '',
                'title' => '7th Generation',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '520',
                'currency' => 'USD',
            ),
            89 => 
            array (
                'id' => 18,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '24',
                'sku' => '',
                'title' => 'Bluetooth Speaker',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '70',
                'currency' => 'USD',
            ),
            90 => 
            array (
                'id' => 19,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '25',
                'sku' => '',
                'title' => 'Branch Apple',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '12',
                'currency' => 'USD',
            ),
            91 => 
            array (
                'id' => 20,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '26',
                'sku' => '',
                'title' => 'Bracelet Watch',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '40',
                'currency' => 'USD',
            ),
            92 => 
            array (
                'id' => 21,
                'marketplace_order_id' => 8,
                'marketplace_item_id' => '28',
                'sku' => '',
                'title' => 'Goldenhour Watch',
                'quantity_purchased' => '4',
                'asin' => '',
                'item_price' => '240',
                'currency' => 'USD',
            ),
            93 => 
            array (
                'id' => 22,
                'marketplace_order_id' => 9,
                'marketplace_item_id' => '30',
                'sku' => '',
                'title' => 'Silicon Orange Juice',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '14',
                'currency' => 'USD',
            ),
            94 => 
            array (
                'id' => 23,
                'marketplace_order_id' => 10,
                'marketplace_item_id' => '32',
                'sku' => '',
                'title' => 'Pionner Men Casual Short Sleeve',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '29',
                'currency' => 'USD',
            ),
            95 => 
            array (
                'id' => 24,
                'marketplace_order_id' => 11,
                'marketplace_item_id' => '56',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            96 => 
            array (
                'id' => 1,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '1',
                'sku' => '',
                'title' => 'Ship Your Idea - Blue',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '30',
                'currency' => 'USD',
            ),
            97 => 
            array (
                'id' => 2,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '2',
                'sku' => '',
                'title' => 'Happy Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '18',
                'currency' => 'USD',
            ),
            98 => 
            array (
                'id' => 3,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '3',
                'sku' => '',
                'title' => 'Ninja Silhouette',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            99 => 
            array (
                'id' => 4,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '4',
                'sku' => '',
                'title' => 'Woo Ninja',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '35',
                'currency' => 'USD',
            ),
            100 => 
            array (
                'id' => 5,
                'marketplace_order_id' => 1,
                'marketplace_item_id' => '5',
                'sku' => '',
                'title' => 'Woo Single #2',
                'quantity_purchased' => '3',
                'asin' => '',
                'item_price' => '6',
                'currency' => 'USD',
            ),
            101 => 
            array (
                'id' => 6,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '7',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            102 => 
            array (
                'id' => 7,
                'marketplace_order_id' => 2,
                'marketplace_item_id' => '8',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            103 => 
            array (
                'id' => 8,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '10',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            104 => 
            array (
                'id' => 9,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '11',
                'sku' => '',
                'title' => 'Luxury Watche',
                'quantity_purchased' => '8',
                'asin' => '',
                'item_price' => '4320',
                'currency' => 'USD',
            ),
            105 => 
            array (
                'id' => 10,
                'marketplace_order_id' => 3,
                'marketplace_item_id' => '12',
                'sku' => '',
                'title' => 'Intel Laptop',
                'quantity_purchased' => '7',
                'asin' => '',
                'item_price' => '3780',
                'currency' => 'USD',
            ),
            106 => 
            array (
                'id' => 11,
                'marketplace_order_id' => 4,
                'marketplace_item_id' => '14',
                'sku' => '',
                'title' => '3D Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '540',
                'currency' => 'USD',
            ),
            107 => 
            array (
                'id' => 12,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '16',
                'sku' => '',
                'title' => 'Apple iPhone 7s',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '660',
                'currency' => 'USD',
            ),
            108 => 
            array (
                'id' => 13,
                'marketplace_order_id' => 5,
                'marketplace_item_id' => '17',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
            109 => 
            array (
                'id' => 14,
                'marketplace_order_id' => 6,
                'marketplace_item_id' => '19',
                'sku' => '',
                'title' => 'Core i7 Laptop',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '125',
                'currency' => 'USD',
            ),
            110 => 
            array (
                'id' => 15,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '21',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '2',
                'asin' => '',
                'item_price' => '440',
                'currency' => 'USD',
            ),
            111 => 
            array (
                'id' => 16,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '22',
                'sku' => '',
                'title' => '3D VR Glass',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '245',
                'currency' => 'USD',
            ),
            112 => 
            array (
                'id' => 17,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '23',
                'sku' => '',
                'title' => '7th Generation',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '520',
                'currency' => 'USD',
            ),
            113 => 
            array (
                'id' => 18,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '24',
                'sku' => '',
                'title' => 'Bluetooth Speaker',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '70',
                'currency' => 'USD',
            ),
            114 => 
            array (
                'id' => 19,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '25',
                'sku' => '',
                'title' => 'Branch Apple',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '12',
                'currency' => 'USD',
            ),
            115 => 
            array (
                'id' => 20,
                'marketplace_order_id' => 7,
                'marketplace_item_id' => '26',
                'sku' => '',
                'title' => 'Bracelet Watch',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '40',
                'currency' => 'USD',
            ),
            116 => 
            array (
                'id' => 21,
                'marketplace_order_id' => 8,
                'marketplace_item_id' => '28',
                'sku' => '',
                'title' => 'Goldenhour Watch',
                'quantity_purchased' => '4',
                'asin' => '',
                'item_price' => '240',
                'currency' => 'USD',
            ),
            117 => 
            array (
                'id' => 22,
                'marketplace_order_id' => 9,
                'marketplace_item_id' => '30',
                'sku' => '',
                'title' => 'Silicon Orange Juice',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '14',
                'currency' => 'USD',
            ),
            118 => 
            array (
                'id' => 23,
                'marketplace_order_id' => 10,
                'marketplace_item_id' => '32',
                'sku' => '',
                'title' => 'Pionner Men Casual Short Sleeve',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '29',
                'currency' => 'USD',
            ),
            119 => 
            array (
                'id' => 24,
                'marketplace_order_id' => 11,
                'marketplace_item_id' => '56',
                'sku' => '',
                'title' => 'Bevigac Gamepad',
                'quantity_purchased' => '1',
                'asin' => '',
                'item_price' => '220',
                'currency' => 'USD',
            ),
        ));
        
        
    }
}