<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MawbParcelMappingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mawb_parcel_mappings')->delete();
        
        \DB::table('mawb_parcel_mappings')->insert(array (
            0 => 
            array (
                'id' => 3670,
                'mawb_id' => 85,
                'parcel_id' => 228079,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            1 => 
            array (
                'id' => 3671,
                'mawb_id' => 85,
                'parcel_id' => 228080,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            2 => 
            array (
                'id' => 3672,
                'mawb_id' => 85,
                'parcel_id' => 228081,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            3 => 
            array (
                'id' => 3673,
                'mawb_id' => 85,
                'parcel_id' => 228082,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            4 => 
            array (
                'id' => 3674,
                'mawb_id' => 85,
                'parcel_id' => 228083,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            5 => 
            array (
                'id' => 3675,
                'mawb_id' => 85,
                'parcel_id' => 228084,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            6 => 
            array (
                'id' => 3676,
                'mawb_id' => 85,
                'parcel_id' => 228085,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            7 => 
            array (
                'id' => 3677,
                'mawb_id' => 85,
                'parcel_id' => 228086,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            8 => 
            array (
                'id' => 3678,
                'mawb_id' => 85,
                'parcel_id' => 228087,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            9 => 
            array (
                'id' => 3679,
                'mawb_id' => 85,
                'parcel_id' => 228088,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            10 => 
            array (
                'id' => 3680,
                'mawb_id' => 85,
                'parcel_id' => 228089,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            11 => 
            array (
                'id' => 3681,
                'mawb_id' => 85,
                'parcel_id' => 228090,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            12 => 
            array (
                'id' => 3682,
                'mawb_id' => 85,
                'parcel_id' => 228091,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            13 => 
            array (
                'id' => 3683,
                'mawb_id' => 85,
                'parcel_id' => 228092,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            14 => 
            array (
                'id' => 3684,
                'mawb_id' => 85,
                'parcel_id' => 228093,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            15 => 
            array (
                'id' => 3670,
                'mawb_id' => 85,
                'parcel_id' => 228079,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            16 => 
            array (
                'id' => 3671,
                'mawb_id' => 85,
                'parcel_id' => 228080,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            17 => 
            array (
                'id' => 3672,
                'mawb_id' => 85,
                'parcel_id' => 228081,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            18 => 
            array (
                'id' => 3673,
                'mawb_id' => 85,
                'parcel_id' => 228082,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            19 => 
            array (
                'id' => 3674,
                'mawb_id' => 85,
                'parcel_id' => 228083,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            20 => 
            array (
                'id' => 3675,
                'mawb_id' => 85,
                'parcel_id' => 228084,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            21 => 
            array (
                'id' => 3676,
                'mawb_id' => 85,
                'parcel_id' => 228085,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            22 => 
            array (
                'id' => 3677,
                'mawb_id' => 85,
                'parcel_id' => 228086,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            23 => 
            array (
                'id' => 3678,
                'mawb_id' => 85,
                'parcel_id' => 228087,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            24 => 
            array (
                'id' => 3679,
                'mawb_id' => 85,
                'parcel_id' => 228088,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            25 => 
            array (
                'id' => 3680,
                'mawb_id' => 85,
                'parcel_id' => 228089,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            26 => 
            array (
                'id' => 3681,
                'mawb_id' => 85,
                'parcel_id' => 228090,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            27 => 
            array (
                'id' => 3682,
                'mawb_id' => 85,
                'parcel_id' => 228091,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            28 => 
            array (
                'id' => 3683,
                'mawb_id' => 85,
                'parcel_id' => 228092,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            29 => 
            array (
                'id' => 3684,
                'mawb_id' => 85,
                'parcel_id' => 228093,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            30 => 
            array (
                'id' => 3670,
                'mawb_id' => 85,
                'parcel_id' => 228079,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            31 => 
            array (
                'id' => 3671,
                'mawb_id' => 85,
                'parcel_id' => 228080,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            32 => 
            array (
                'id' => 3672,
                'mawb_id' => 85,
                'parcel_id' => 228081,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            33 => 
            array (
                'id' => 3673,
                'mawb_id' => 85,
                'parcel_id' => 228082,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            34 => 
            array (
                'id' => 3674,
                'mawb_id' => 85,
                'parcel_id' => 228083,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            35 => 
            array (
                'id' => 3675,
                'mawb_id' => 85,
                'parcel_id' => 228084,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            36 => 
            array (
                'id' => 3676,
                'mawb_id' => 85,
                'parcel_id' => 228085,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            37 => 
            array (
                'id' => 3677,
                'mawb_id' => 85,
                'parcel_id' => 228086,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            38 => 
            array (
                'id' => 3678,
                'mawb_id' => 85,
                'parcel_id' => 228087,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            39 => 
            array (
                'id' => 3679,
                'mawb_id' => 85,
                'parcel_id' => 228088,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            40 => 
            array (
                'id' => 3680,
                'mawb_id' => 85,
                'parcel_id' => 228089,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            41 => 
            array (
                'id' => 3681,
                'mawb_id' => 85,
                'parcel_id' => 228090,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            42 => 
            array (
                'id' => 3682,
                'mawb_id' => 85,
                'parcel_id' => 228091,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            43 => 
            array (
                'id' => 3683,
                'mawb_id' => 85,
                'parcel_id' => 228092,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            44 => 
            array (
                'id' => 3684,
                'mawb_id' => 85,
                'parcel_id' => 228093,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            45 => 
            array (
                'id' => 3670,
                'mawb_id' => 85,
                'parcel_id' => 228079,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            46 => 
            array (
                'id' => 3671,
                'mawb_id' => 85,
                'parcel_id' => 228080,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            47 => 
            array (
                'id' => 3672,
                'mawb_id' => 85,
                'parcel_id' => 228081,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            48 => 
            array (
                'id' => 3673,
                'mawb_id' => 85,
                'parcel_id' => 228082,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            49 => 
            array (
                'id' => 3674,
                'mawb_id' => 85,
                'parcel_id' => 228083,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            50 => 
            array (
                'id' => 3675,
                'mawb_id' => 85,
                'parcel_id' => 228084,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            51 => 
            array (
                'id' => 3676,
                'mawb_id' => 85,
                'parcel_id' => 228085,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            52 => 
            array (
                'id' => 3677,
                'mawb_id' => 85,
                'parcel_id' => 228086,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            53 => 
            array (
                'id' => 3678,
                'mawb_id' => 85,
                'parcel_id' => 228087,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            54 => 
            array (
                'id' => 3679,
                'mawb_id' => 85,
                'parcel_id' => 228088,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            55 => 
            array (
                'id' => 3680,
                'mawb_id' => 85,
                'parcel_id' => 228089,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            56 => 
            array (
                'id' => 3681,
                'mawb_id' => 85,
                'parcel_id' => 228090,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            57 => 
            array (
                'id' => 3682,
                'mawb_id' => 85,
                'parcel_id' => 228091,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            58 => 
            array (
                'id' => 3683,
                'mawb_id' => 85,
                'parcel_id' => 228092,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            59 => 
            array (
                'id' => 3684,
                'mawb_id' => 85,
                'parcel_id' => 228093,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            60 => 
            array (
                'id' => 3670,
                'mawb_id' => 85,
                'parcel_id' => 228079,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            61 => 
            array (
                'id' => 3671,
                'mawb_id' => 85,
                'parcel_id' => 228080,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            62 => 
            array (
                'id' => 3672,
                'mawb_id' => 85,
                'parcel_id' => 228081,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            63 => 
            array (
                'id' => 3673,
                'mawb_id' => 85,
                'parcel_id' => 228082,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            64 => 
            array (
                'id' => 3674,
                'mawb_id' => 85,
                'parcel_id' => 228083,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            65 => 
            array (
                'id' => 3675,
                'mawb_id' => 85,
                'parcel_id' => 228084,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            66 => 
            array (
                'id' => 3676,
                'mawb_id' => 85,
                'parcel_id' => 228085,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            67 => 
            array (
                'id' => 3677,
                'mawb_id' => 85,
                'parcel_id' => 228086,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            68 => 
            array (
                'id' => 3678,
                'mawb_id' => 85,
                'parcel_id' => 228087,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            69 => 
            array (
                'id' => 3679,
                'mawb_id' => 85,
                'parcel_id' => 228088,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            70 => 
            array (
                'id' => 3680,
                'mawb_id' => 85,
                'parcel_id' => 228089,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            71 => 
            array (
                'id' => 3681,
                'mawb_id' => 85,
                'parcel_id' => 228090,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            72 => 
            array (
                'id' => 3682,
                'mawb_id' => 85,
                'parcel_id' => 228091,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            73 => 
            array (
                'id' => 3683,
                'mawb_id' => 85,
                'parcel_id' => 228092,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
            74 => 
            array (
                'id' => 3684,
                'mawb_id' => 85,
                'parcel_id' => 228093,
                'wharehouse_id' => 9,
                'bag_id' => 10356,
                'date_added' => '2020-03-19 16:53:01',
                'added_by' => 2328,
                'date_updated' => NULL,
                'updated_by' => NULL,
            ),
        ));
        
        
    }
}