<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OpsSummariesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ops_summaries')->delete();
        
        \DB::table('ops_summaries')->insert(array (
            0 => 
            array (
                'id' => 2504,
                'account' => '',
                'services' => '',
                'country' => 'Austria',
                'quantity' => '9',
                'weight' => '1.629',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            1 => 
            array (
                'id' => 2505,
                'account' => '',
                'services' => '',
                'country' => 'Germany',
                'quantity' => '19',
                'weight' => '1.150',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            2 => 
            array (
                'id' => 2506,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '296',
                'weight' => '31.552',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            3 => 
            array (
                'id' => 2507,
                'account' => '',
                'services' => '',
                'country' => 'United Kingdom',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            4 => 
            array (
                'id' => 2508,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '12',
                'weight' => '2.427',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:37:23',
                'reference' => '04365718811',
                'mawb' => '',
            ),
            5 => 
            array (
                'id' => 2509,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '120',
                'weight' => '17.633',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:00',
                'reference' => '58945226576',
                'mawb' => '',
            ),
            6 => 
            array (
                'id' => 2510,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:35',
                'reference' => '58945286275',
                'mawb' => '',
            ),
            7 => 
            array (
                'id' => 2511,
                'account' => 'PETERJO',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '3',
                'weight' => '0.8',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 18:29:38',
                'reference' => '',
                'mawb' => '',
            ),
            8 => 
            array (
                'id' => 2513,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '1',
                'weight' => '0.129',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            9 => 
            array (
                'id' => 2514,
                'account' => '',
                'services' => '',
                'country' => 'Spain',
                'quantity' => '2',
                'weight' => '0.723',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            10 => 
            array (
                'id' => 2515,
                'account' => '',
                'services' => '',
                'country' => 'Greece',
                'quantity' => '3',
                'weight' => '2.273',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:16',
                'reference' => '',
                'mawb' => '618-36678530',
            ),
            11 => 
            array (
                'id' => 2504,
                'account' => '',
                'services' => '',
                'country' => 'Austria',
                'quantity' => '9',
                'weight' => '1.629',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            12 => 
            array (
                'id' => 2505,
                'account' => '',
                'services' => '',
                'country' => 'Germany',
                'quantity' => '19',
                'weight' => '1.150',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            13 => 
            array (
                'id' => 2506,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '296',
                'weight' => '31.552',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            14 => 
            array (
                'id' => 2507,
                'account' => '',
                'services' => '',
                'country' => 'United Kingdom',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            15 => 
            array (
                'id' => 2508,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '12',
                'weight' => '2.427',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:37:23',
                'reference' => '04365718811',
                'mawb' => '',
            ),
            16 => 
            array (
                'id' => 2509,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '120',
                'weight' => '17.633',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:00',
                'reference' => '58945226576',
                'mawb' => '',
            ),
            17 => 
            array (
                'id' => 2510,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:35',
                'reference' => '58945286275',
                'mawb' => '',
            ),
            18 => 
            array (
                'id' => 2511,
                'account' => 'PETERJO',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '3',
                'weight' => '0.8',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 18:29:38',
                'reference' => '',
                'mawb' => '',
            ),
            19 => 
            array (
                'id' => 2513,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '1',
                'weight' => '0.129',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            20 => 
            array (
                'id' => 2514,
                'account' => '',
                'services' => '',
                'country' => 'Spain',
                'quantity' => '2',
                'weight' => '0.723',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            21 => 
            array (
                'id' => 2515,
                'account' => '',
                'services' => '',
                'country' => 'Greece',
                'quantity' => '3',
                'weight' => '2.273',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:16',
                'reference' => '',
                'mawb' => '618-36678530',
            ),
            22 => 
            array (
                'id' => 2504,
                'account' => '',
                'services' => '',
                'country' => 'Austria',
                'quantity' => '9',
                'weight' => '1.629',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            23 => 
            array (
                'id' => 2505,
                'account' => '',
                'services' => '',
                'country' => 'Germany',
                'quantity' => '19',
                'weight' => '1.150',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            24 => 
            array (
                'id' => 2506,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '296',
                'weight' => '31.552',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            25 => 
            array (
                'id' => 2507,
                'account' => '',
                'services' => '',
                'country' => 'United Kingdom',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            26 => 
            array (
                'id' => 2508,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '12',
                'weight' => '2.427',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:37:23',
                'reference' => '04365718811',
                'mawb' => '',
            ),
            27 => 
            array (
                'id' => 2509,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '120',
                'weight' => '17.633',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:00',
                'reference' => '58945226576',
                'mawb' => '',
            ),
            28 => 
            array (
                'id' => 2510,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:35',
                'reference' => '58945286275',
                'mawb' => '',
            ),
            29 => 
            array (
                'id' => 2511,
                'account' => 'PETERJO',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '3',
                'weight' => '0.8',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 18:29:38',
                'reference' => '',
                'mawb' => '',
            ),
            30 => 
            array (
                'id' => 2513,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '1',
                'weight' => '0.129',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            31 => 
            array (
                'id' => 2514,
                'account' => '',
                'services' => '',
                'country' => 'Spain',
                'quantity' => '2',
                'weight' => '0.723',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            32 => 
            array (
                'id' => 2515,
                'account' => '',
                'services' => '',
                'country' => 'Greece',
                'quantity' => '3',
                'weight' => '2.273',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:16',
                'reference' => '',
                'mawb' => '618-36678530',
            ),
            33 => 
            array (
                'id' => 2504,
                'account' => '',
                'services' => '',
                'country' => 'Austria',
                'quantity' => '9',
                'weight' => '1.629',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            34 => 
            array (
                'id' => 2505,
                'account' => '',
                'services' => '',
                'country' => 'Germany',
                'quantity' => '19',
                'weight' => '1.150',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            35 => 
            array (
                'id' => 2506,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '296',
                'weight' => '31.552',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            36 => 
            array (
                'id' => 2507,
                'account' => '',
                'services' => '',
                'country' => 'United Kingdom',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            37 => 
            array (
                'id' => 2508,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '12',
                'weight' => '2.427',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:37:23',
                'reference' => '04365718811',
                'mawb' => '',
            ),
            38 => 
            array (
                'id' => 2509,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '120',
                'weight' => '17.633',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:00',
                'reference' => '58945226576',
                'mawb' => '',
            ),
            39 => 
            array (
                'id' => 2510,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:35',
                'reference' => '58945286275',
                'mawb' => '',
            ),
            40 => 
            array (
                'id' => 2511,
                'account' => 'PETERJO',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '3',
                'weight' => '0.8',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 18:29:38',
                'reference' => '',
                'mawb' => '',
            ),
            41 => 
            array (
                'id' => 2513,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '1',
                'weight' => '0.129',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            42 => 
            array (
                'id' => 2514,
                'account' => '',
                'services' => '',
                'country' => 'Spain',
                'quantity' => '2',
                'weight' => '0.723',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            43 => 
            array (
                'id' => 2515,
                'account' => '',
                'services' => '',
                'country' => 'Greece',
                'quantity' => '3',
                'weight' => '2.273',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:16',
                'reference' => '',
                'mawb' => '618-36678530',
            ),
            44 => 
            array (
                'id' => 2504,
                'account' => '',
                'services' => '',
                'country' => 'Austria',
                'quantity' => '9',
                'weight' => '1.629',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            45 => 
            array (
                'id' => 2505,
                'account' => '',
                'services' => '',
                'country' => 'Germany',
                'quantity' => '19',
                'weight' => '1.150',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            46 => 
            array (
                'id' => 2506,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '296',
                'weight' => '31.552',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            47 => 
            array (
                'id' => 2507,
                'account' => '',
                'services' => '',
                'country' => 'United Kingdom',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '',
                'date_submitted' => '2016-08-23 16:24:17',
                'reference' => '',
                'mawb' => '589-45286275',
            ),
            48 => 
            array (
                'id' => 2508,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '12',
                'weight' => '2.427',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:37:23',
                'reference' => '04365718811',
                'mawb' => '',
            ),
            49 => 
            array (
                'id' => 2509,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '120',
                'weight' => '17.633',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:00',
                'reference' => '58945226576',
                'mawb' => '',
            ),
            50 => 
            array (
                'id' => 2510,
                'account' => 'OWECH',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '102',
                'weight' => '17.368',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 16:38:35',
                'reference' => '58945286275',
                'mawb' => '',
            ),
            51 => 
            array (
                'id' => 2511,
                'account' => 'PETERJO',
                'services' => 'DBP',
                'country' => '',
                'quantity' => '3',
                'weight' => '0.8',
                'carrier' => '2nd Class Packet UK',
                'date_submitted' => '2016-08-23 18:29:38',
                'reference' => '',
                'mawb' => '',
            ),
            52 => 
            array (
                'id' => 2513,
                'account' => '',
                'services' => '',
                'country' => 'Italy',
                'quantity' => '1',
                'weight' => '0.129',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            53 => 
            array (
                'id' => 2514,
                'account' => '',
                'services' => '',
                'country' => 'Spain',
                'quantity' => '2',
                'weight' => '0.723',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:01',
                'reference' => '',
                'mawb' => '932-50003892',
            ),
            54 => 
            array (
                'id' => 2515,
                'account' => '',
                'services' => '',
                'country' => 'Greece',
                'quantity' => '3',
                'weight' => '2.273',
                'carrier' => '',
                'date_submitted' => '2016-08-24 13:41:16',
                'reference' => '',
                'mawb' => '618-36678530',
            ),
        ));
        
        
    }
}