<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PalletsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pallets')->delete();
        
        \DB::table('pallets')->insert(array (
            0 => 
            array (
                'id' => 3922,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:45',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            1 => 
            array (
                'id' => 3923,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:51',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            2 => 
            array (
                'id' => 3924,
                'palletno' => 'HOEIPMAI00003924',
                'date_created' => '2018-12-05 15:57:39',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3924.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            3 => 
            array (
                'id' => 3925,
                'palletno' => 'HOEIPMAI00003925',
                'date_created' => '2018-12-05 15:57:49',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3925.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            4 => 
            array (
                'id' => 3926,
                'palletno' => 'HOEIPMAI00003926',
                'date_created' => '2018-12-05 15:57:51',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-27 00:16:12',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3926.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            5 => 
            array (
                'id' => 3927,
                'palletno' => 'HOEIPSWE00003927',
                'date_created' => '2018-12-12 19:50:25',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 3,
                'date_dispatch' => '2018-12-27 00:07:59',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3927.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            6 => 
            array (
                'id' => 3928,
                'palletno' => 'HOEIPMAI00003928',
                'date_created' => '2018-12-21 20:45:35',
                'close' => 1,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-26 21:19:29',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3928.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            7 => 
            array (
                'id' => 3929,
                'palletno' => 'HOEIPMAI00003929',
                'date_created' => '2019-01-01 19:45:29',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3929.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            8 => 
            array (
                'id' => 3930,
                'palletno' => 'HOEIPYOD00003930',
                'date_created' => '2019-07-31 22:07:51',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            9 => 
            array (
                'id' => 3931,
                'palletno' => 'ITTEPARA00003931',
                'date_created' => '2019-08-27 16:05:49',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 2,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 4,
                'pallet_destination_warehouse_id' => NULL,
            ),
            10 => 
            array (
                'id' => 3932,
                'palletno' => 'ITTEPYOD00003932',
                'date_created' => '2019-08-27 16:10:28',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3932.pdf',
                'pallet_source_country_id' => 4,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 5,
                'pallet_destination_warehouse_id' => NULL,
            ),
            11 => 
            array (
                'id' => 3933,
                'palletno' => 'SACMPMAI00003933',
                'date_created' => '2019-08-28 18:58:25',
                'close' => 1,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2019-08-28 21:54:29',
                'dispatch_userid' => 2254,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3933.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            12 => 
            array (
                'id' => 3934,
                'palletno' => 'SACMPYOD00003934',
                'date_created' => '2019-08-28 21:34:01',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3934.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            13 => 
            array (
                'id' => 3935,
                'palletno' => 'SACMPYOD00003935',
                'date_created' => '2019-08-29 21:03:24',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 6,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '2',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            14 => 
            array (
                'id' => 3936,
                'palletno' => 'ITTEPMAI00003936',
                'date_created' => '2019-11-20 23:22:43',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3936.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => NULL,
            ),
            15 => 
            array (
                'id' => 3937,
                'palletno' => 'KLCWPYOD00003937',
                'date_created' => '2019-11-22 16:49:17',
                'close' => 0,
                'userid' => 2191,
                'pallet_carrier_id' => 7,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3937.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 6,
                'pallet_destination_warehouse_id' => NULL,
            ),
            16 => 
            array (
                'id' => 3938,
                'palletno' => 'SACMPARA00003938',
                'date_created' => '2020-01-02 20:16:06',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            17 => 
            array (
                'id' => 3939,
                'palletno' => 'ITTEPARA00003939',
                'date_created' => '2020-01-02 21:23:03',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            18 => 
            array (
                'id' => 3940,
                'palletno' => 'SACMPMAI00003940BHX',
                'date_created' => '2020-03-13 18:39:20',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            19 => 
            array (
                'id' => 3922,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:45',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            20 => 
            array (
                'id' => 3923,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:51',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            21 => 
            array (
                'id' => 3924,
                'palletno' => 'HOEIPMAI00003924',
                'date_created' => '2018-12-05 15:57:39',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3924.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            22 => 
            array (
                'id' => 3925,
                'palletno' => 'HOEIPMAI00003925',
                'date_created' => '2018-12-05 15:57:49',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3925.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            23 => 
            array (
                'id' => 3926,
                'palletno' => 'HOEIPMAI00003926',
                'date_created' => '2018-12-05 15:57:51',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-27 00:16:12',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3926.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            24 => 
            array (
                'id' => 3927,
                'palletno' => 'HOEIPSWE00003927',
                'date_created' => '2018-12-12 19:50:25',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 3,
                'date_dispatch' => '2018-12-27 00:07:59',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3927.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            25 => 
            array (
                'id' => 3928,
                'palletno' => 'HOEIPMAI00003928',
                'date_created' => '2018-12-21 20:45:35',
                'close' => 1,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-26 21:19:29',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3928.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            26 => 
            array (
                'id' => 3929,
                'palletno' => 'HOEIPMAI00003929',
                'date_created' => '2019-01-01 19:45:29',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3929.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            27 => 
            array (
                'id' => 3930,
                'palletno' => 'HOEIPYOD00003930',
                'date_created' => '2019-07-31 22:07:51',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            28 => 
            array (
                'id' => 3931,
                'palletno' => 'ITTEPARA00003931',
                'date_created' => '2019-08-27 16:05:49',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 2,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 4,
                'pallet_destination_warehouse_id' => NULL,
            ),
            29 => 
            array (
                'id' => 3932,
                'palletno' => 'ITTEPYOD00003932',
                'date_created' => '2019-08-27 16:10:28',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3932.pdf',
                'pallet_source_country_id' => 4,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 5,
                'pallet_destination_warehouse_id' => NULL,
            ),
            30 => 
            array (
                'id' => 3933,
                'palletno' => 'SACMPMAI00003933',
                'date_created' => '2019-08-28 18:58:25',
                'close' => 1,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2019-08-28 21:54:29',
                'dispatch_userid' => 2254,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3933.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            31 => 
            array (
                'id' => 3934,
                'palletno' => 'SACMPYOD00003934',
                'date_created' => '2019-08-28 21:34:01',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3934.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            32 => 
            array (
                'id' => 3935,
                'palletno' => 'SACMPYOD00003935',
                'date_created' => '2019-08-29 21:03:24',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 6,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '2',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            33 => 
            array (
                'id' => 3936,
                'palletno' => 'ITTEPMAI00003936',
                'date_created' => '2019-11-20 23:22:43',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3936.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => NULL,
            ),
            34 => 
            array (
                'id' => 3937,
                'palletno' => 'KLCWPYOD00003937',
                'date_created' => '2019-11-22 16:49:17',
                'close' => 0,
                'userid' => 2191,
                'pallet_carrier_id' => 7,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3937.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 6,
                'pallet_destination_warehouse_id' => NULL,
            ),
            35 => 
            array (
                'id' => 3938,
                'palletno' => 'SACMPARA00003938',
                'date_created' => '2020-01-02 20:16:06',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            36 => 
            array (
                'id' => 3939,
                'palletno' => 'ITTEPARA00003939',
                'date_created' => '2020-01-02 21:23:03',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            37 => 
            array (
                'id' => 3940,
                'palletno' => 'SACMPMAI00003940BHX',
                'date_created' => '2020-03-13 18:39:20',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            38 => 
            array (
                'id' => 3922,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:45',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            39 => 
            array (
                'id' => 3923,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:51',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            40 => 
            array (
                'id' => 3924,
                'palletno' => 'HOEIPMAI00003924',
                'date_created' => '2018-12-05 15:57:39',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3924.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            41 => 
            array (
                'id' => 3925,
                'palletno' => 'HOEIPMAI00003925',
                'date_created' => '2018-12-05 15:57:49',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3925.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            42 => 
            array (
                'id' => 3926,
                'palletno' => 'HOEIPMAI00003926',
                'date_created' => '2018-12-05 15:57:51',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-27 00:16:12',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3926.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            43 => 
            array (
                'id' => 3927,
                'palletno' => 'HOEIPSWE00003927',
                'date_created' => '2018-12-12 19:50:25',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 3,
                'date_dispatch' => '2018-12-27 00:07:59',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3927.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            44 => 
            array (
                'id' => 3928,
                'palletno' => 'HOEIPMAI00003928',
                'date_created' => '2018-12-21 20:45:35',
                'close' => 1,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-26 21:19:29',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3928.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            45 => 
            array (
                'id' => 3929,
                'palletno' => 'HOEIPMAI00003929',
                'date_created' => '2019-01-01 19:45:29',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3929.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            46 => 
            array (
                'id' => 3930,
                'palletno' => 'HOEIPYOD00003930',
                'date_created' => '2019-07-31 22:07:51',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            47 => 
            array (
                'id' => 3931,
                'palletno' => 'ITTEPARA00003931',
                'date_created' => '2019-08-27 16:05:49',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 2,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 4,
                'pallet_destination_warehouse_id' => NULL,
            ),
            48 => 
            array (
                'id' => 3932,
                'palletno' => 'ITTEPYOD00003932',
                'date_created' => '2019-08-27 16:10:28',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3932.pdf',
                'pallet_source_country_id' => 4,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 5,
                'pallet_destination_warehouse_id' => NULL,
            ),
            49 => 
            array (
                'id' => 3933,
                'palletno' => 'SACMPMAI00003933',
                'date_created' => '2019-08-28 18:58:25',
                'close' => 1,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2019-08-28 21:54:29',
                'dispatch_userid' => 2254,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3933.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            50 => 
            array (
                'id' => 3934,
                'palletno' => 'SACMPYOD00003934',
                'date_created' => '2019-08-28 21:34:01',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3934.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            51 => 
            array (
                'id' => 3935,
                'palletno' => 'SACMPYOD00003935',
                'date_created' => '2019-08-29 21:03:24',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 6,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '2',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            52 => 
            array (
                'id' => 3936,
                'palletno' => 'ITTEPMAI00003936',
                'date_created' => '2019-11-20 23:22:43',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3936.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => NULL,
            ),
            53 => 
            array (
                'id' => 3937,
                'palletno' => 'KLCWPYOD00003937',
                'date_created' => '2019-11-22 16:49:17',
                'close' => 0,
                'userid' => 2191,
                'pallet_carrier_id' => 7,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3937.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 6,
                'pallet_destination_warehouse_id' => NULL,
            ),
            54 => 
            array (
                'id' => 3938,
                'palletno' => 'SACMPARA00003938',
                'date_created' => '2020-01-02 20:16:06',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            55 => 
            array (
                'id' => 3939,
                'palletno' => 'ITTEPARA00003939',
                'date_created' => '2020-01-02 21:23:03',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            56 => 
            array (
                'id' => 3940,
                'palletno' => 'SACMPMAI00003940BHX',
                'date_created' => '2020-03-13 18:39:20',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            57 => 
            array (
                'id' => 3922,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:45',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            58 => 
            array (
                'id' => 3923,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:51',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            59 => 
            array (
                'id' => 3924,
                'palletno' => 'HOEIPMAI00003924',
                'date_created' => '2018-12-05 15:57:39',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3924.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            60 => 
            array (
                'id' => 3925,
                'palletno' => 'HOEIPMAI00003925',
                'date_created' => '2018-12-05 15:57:49',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3925.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            61 => 
            array (
                'id' => 3926,
                'palletno' => 'HOEIPMAI00003926',
                'date_created' => '2018-12-05 15:57:51',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-27 00:16:12',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3926.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            62 => 
            array (
                'id' => 3927,
                'palletno' => 'HOEIPSWE00003927',
                'date_created' => '2018-12-12 19:50:25',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 3,
                'date_dispatch' => '2018-12-27 00:07:59',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3927.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            63 => 
            array (
                'id' => 3928,
                'palletno' => 'HOEIPMAI00003928',
                'date_created' => '2018-12-21 20:45:35',
                'close' => 1,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-26 21:19:29',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3928.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            64 => 
            array (
                'id' => 3929,
                'palletno' => 'HOEIPMAI00003929',
                'date_created' => '2019-01-01 19:45:29',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3929.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            65 => 
            array (
                'id' => 3930,
                'palletno' => 'HOEIPYOD00003930',
                'date_created' => '2019-07-31 22:07:51',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            66 => 
            array (
                'id' => 3931,
                'palletno' => 'ITTEPARA00003931',
                'date_created' => '2019-08-27 16:05:49',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 2,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 4,
                'pallet_destination_warehouse_id' => NULL,
            ),
            67 => 
            array (
                'id' => 3932,
                'palletno' => 'ITTEPYOD00003932',
                'date_created' => '2019-08-27 16:10:28',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3932.pdf',
                'pallet_source_country_id' => 4,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 5,
                'pallet_destination_warehouse_id' => NULL,
            ),
            68 => 
            array (
                'id' => 3933,
                'palletno' => 'SACMPMAI00003933',
                'date_created' => '2019-08-28 18:58:25',
                'close' => 1,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2019-08-28 21:54:29',
                'dispatch_userid' => 2254,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3933.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            69 => 
            array (
                'id' => 3934,
                'palletno' => 'SACMPYOD00003934',
                'date_created' => '2019-08-28 21:34:01',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3934.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            70 => 
            array (
                'id' => 3935,
                'palletno' => 'SACMPYOD00003935',
                'date_created' => '2019-08-29 21:03:24',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 6,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '2',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            71 => 
            array (
                'id' => 3936,
                'palletno' => 'ITTEPMAI00003936',
                'date_created' => '2019-11-20 23:22:43',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3936.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => NULL,
            ),
            72 => 
            array (
                'id' => 3937,
                'palletno' => 'KLCWPYOD00003937',
                'date_created' => '2019-11-22 16:49:17',
                'close' => 0,
                'userid' => 2191,
                'pallet_carrier_id' => 7,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3937.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 6,
                'pallet_destination_warehouse_id' => NULL,
            ),
            73 => 
            array (
                'id' => 3938,
                'palletno' => 'SACMPARA00003938',
                'date_created' => '2020-01-02 20:16:06',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            74 => 
            array (
                'id' => 3939,
                'palletno' => 'ITTEPARA00003939',
                'date_created' => '2020-01-02 21:23:03',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            75 => 
            array (
                'id' => 3940,
                'palletno' => 'SACMPMAI00003940BHX',
                'date_created' => '2020-03-13 18:39:20',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            76 => 
            array (
                'id' => 3922,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:45',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            77 => 
            array (
                'id' => 3923,
                'palletno' => '',
                'date_created' => '2018-11-13 22:31:51',
                'close' => 0,
                'userid' => 2128,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 10,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 15,
            ),
            78 => 
            array (
                'id' => 3924,
                'palletno' => 'HOEIPMAI00003924',
                'date_created' => '2018-12-05 15:57:39',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3924.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            79 => 
            array (
                'id' => 3925,
                'palletno' => 'HOEIPMAI00003925',
                'date_created' => '2018-12-05 15:57:49',
                'close' => 0,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3925.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            80 => 
            array (
                'id' => 3926,
                'palletno' => 'HOEIPMAI00003926',
                'date_created' => '2018-12-05 15:57:51',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-27 00:16:12',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3926.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => 0,
            ),
            81 => 
            array (
                'id' => 3927,
                'palletno' => 'HOEIPSWE00003927',
                'date_created' => '2018-12-12 19:50:25',
                'close' => 1,
                'userid' => 2182,
                'pallet_carrier_id' => 3,
                'date_dispatch' => '2018-12-27 00:07:59',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3927.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            82 => 
            array (
                'id' => 3928,
                'palletno' => 'HOEIPMAI00003928',
                'date_created' => '2018-12-21 20:45:35',
                'close' => 1,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2018-12-26 21:19:29',
                'dispatch_userid' => 58,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3928.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            83 => 
            array (
                'id' => 3929,
                'palletno' => 'HOEIPMAI00003929',
                'date_created' => '2019-01-01 19:45:29',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3929.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
            84 => 
            array (
                'id' => 3930,
                'palletno' => 'HOEIPYOD00003930',
                'date_created' => '2019-07-31 22:07:51',
                'close' => 0,
                'userid' => 2198,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            85 => 
            array (
                'id' => 3931,
                'palletno' => 'ITTEPARA00003931',
                'date_created' => '2019-08-27 16:05:49',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 2,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 4,
                'pallet_destination_warehouse_id' => NULL,
            ),
            86 => 
            array (
                'id' => 3932,
                'palletno' => 'ITTEPYOD00003932',
                'date_created' => '2019-08-27 16:10:28',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3932.pdf',
                'pallet_source_country_id' => 4,
                'pallet_source_warehouse_id' => NULL,
                'pallet_destination_country_id' => 5,
                'pallet_destination_warehouse_id' => NULL,
            ),
            87 => 
            array (
                'id' => 3933,
                'palletno' => 'SACMPMAI00003933',
                'date_created' => '2019-08-28 18:58:25',
                'close' => 1,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => '2019-08-28 21:54:29',
                'dispatch_userid' => 2254,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'pdf/palletlabel_3933.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            88 => 
            array (
                'id' => 3934,
                'palletno' => 'SACMPYOD00003934',
                'date_created' => '2019-08-28 21:34:01',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 4,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3934.pdf',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 10,
            ),
            89 => 
            array (
                'id' => 3935,
                'palletno' => 'SACMPYOD00003935',
                'date_created' => '2019-08-29 21:03:24',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 6,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '2',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 13,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 13,
            ),
            90 => 
            array (
                'id' => 3936,
                'palletno' => 'ITTEPMAI00003936',
                'date_created' => '2019-11-20 23:22:43',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3936.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 3,
                'pallet_destination_warehouse_id' => NULL,
            ),
            91 => 
            array (
                'id' => 3937,
                'palletno' => 'KLCWPYOD00003937',
                'date_created' => '2019-11-22 16:49:17',
                'close' => 0,
                'userid' => 2191,
                'pallet_carrier_id' => 7,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '1',
                'is_active' => 1,
                'comments' => '',
                'label' => 'http://staging.smarttrack.co/_assets/pdf/palletlabel_3937.pdf',
                'pallet_source_country_id' => 1,
                'pallet_source_warehouse_id' => 37,
                'pallet_destination_country_id' => 6,
                'pallet_destination_warehouse_id' => NULL,
            ),
            92 => 
            array (
                'id' => 3938,
                'palletno' => 'SACMPARA00003938',
                'date_created' => '2020-01-02 20:16:06',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            93 => 
            array (
                'id' => 3939,
                'palletno' => 'ITTEPARA00003939',
                'date_created' => '2020-01-02 21:23:03',
                'close' => 0,
                'userid' => 58,
                'pallet_carrier_id' => 5,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 80,
                'pallet_destination_warehouse_id' => NULL,
            ),
            94 => 
            array (
                'id' => 3940,
                'palletno' => 'SACMPMAI00003940BHX',
                'date_created' => '2020-03-13 18:39:20',
                'close' => 0,
                'userid' => 2254,
                'pallet_carrier_id' => 2,
                'date_dispatch' => NULL,
                'dispatch_userid' => 0,
                'type' => 'P',
                'manifestid' => 0,
                'hub' => '',
                'is_active' => 1,
                'comments' => '',
                'label' => '',
                'pallet_source_country_id' => 225,
                'pallet_source_warehouse_id' => 9,
                'pallet_destination_country_id' => 225,
                'pallet_destination_warehouse_id' => 9,
            ),
        ));
        
        
    }
}