<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PickupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pickups')->delete();
        
        \DB::table('pickups')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 20:45:00',
                'delivery_note' => 'picked-up by jags',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            10 => 
            array (
                'id' => 1,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            11 => 
            array (
                'id' => 2,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 20:45:00',
                'delivery_note' => 'picked-up by jags',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            12 => 
            array (
                'id' => 3,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            13 => 
            array (
                'id' => 4,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            14 => 
            array (
                'id' => 5,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            15 => 
            array (
                'id' => 6,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            16 => 
            array (
                'id' => 7,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            17 => 
            array (
                'id' => 8,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            18 => 
            array (
                'id' => 9,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            19 => 
            array (
                'id' => 10,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            20 => 
            array (
                'id' => 1,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            21 => 
            array (
                'id' => 2,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 20:45:00',
                'delivery_note' => 'picked-up by jags',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            22 => 
            array (
                'id' => 3,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            23 => 
            array (
                'id' => 4,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            24 => 
            array (
                'id' => 5,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            25 => 
            array (
                'id' => 6,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            26 => 
            array (
                'id' => 7,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            27 => 
            array (
                'id' => 8,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            28 => 
            array (
                'id' => 9,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            29 => 
            array (
                'id' => 10,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            30 => 
            array (
                'id' => 1,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            31 => 
            array (
                'id' => 2,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 20:45:00',
                'delivery_note' => 'picked-up by jags',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            32 => 
            array (
                'id' => 3,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            33 => 
            array (
                'id' => 4,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            34 => 
            array (
                'id' => 5,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            35 => 
            array (
                'id' => 6,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            36 => 
            array (
                'id' => 7,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            37 => 
            array (
                'id' => 8,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            38 => 
            array (
                'id' => 9,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            39 => 
            array (
                'id' => 10,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            40 => 
            array (
                'id' => 1,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            41 => 
            array (
                'id' => 2,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 20:45:00',
                'delivery_note' => 'picked-up by jags',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            42 => 
            array (
                'id' => 3,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            43 => 
            array (
                'id' => 4,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            44 => 
            array (
                'id' => 5,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            45 => 
            array (
                'id' => 6,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            46 => 
            array (
                'id' => 7,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            47 => 
            array (
                'id' => 8,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            48 => 
            array (
                'id' => 9,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
            49 => 
            array (
                'id' => 10,
                'pickup_number' => '',
                'pickup_date' => '2016-08-05 19:55:00',
                'delivery_note' => 'Picked up by kazim',
                'pick_up_pdf' => NULL,
                'collection_pdf' => NULL,
                'collection_address' => NULL,
                'address_line_1' => NULL,
                'address_line_2' => NULL,
                'address_line_3' => NULL,
                'city' => NULL,
                'postcode' => NULL,
                'country' => NULL,
            ),
        ));
        
        
    }
}