<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PostItaliaRoutingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('post_italia_routings')->delete();
        
        \DB::table('post_italia_routings')->insert(array (
            0 => 
            array (
                'id' => 8823,
                'zip_code' => '89024',
                'routing_file' => '93-D52-POLISTEN-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            1 => 
            array (
                'id' => 8824,
                'zip_code' => '89025',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            2 => 
            array (
                'id' => 8825,
                'zip_code' => '89026',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            3 => 
            array (
                'id' => 8826,
                'zip_code' => '89027',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            4 => 
            array (
                'id' => 8827,
                'zip_code' => '89028',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            5 => 
            array (
                'id' => 8828,
                'zip_code' => '89029',
                'routing_file' => '93-D50-TAURIANO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            6 => 
            array (
                'id' => 8829,
                'zip_code' => '89030',
                'routing_file' => '93-MIX-89030-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            7 => 
            array (
                'id' => 8830,
                'zip_code' => '89031',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            8 => 
            array (
                'id' => 8831,
                'zip_code' => '89032',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            9 => 
            array (
                'id' => 8832,
                'zip_code' => '89033',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            10 => 
            array (
                'id' => 8833,
                'zip_code' => '89034',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            11 => 
            array (
                'id' => 8834,
                'zip_code' => '89035',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            12 => 
            array (
                'id' => 8835,
                'zip_code' => '89036',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            13 => 
            array (
                'id' => 8836,
                'zip_code' => '89037',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            14 => 
            array (
                'id' => 8837,
                'zip_code' => '89038',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            15 => 
            array (
                'id' => 8838,
                'zip_code' => '89039',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            16 => 
            array (
                'id' => 8839,
                'zip_code' => '89040',
                'routing_file' => '93-MIX-89040-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            17 => 
            array (
                'id' => 8840,
                'zip_code' => '89041',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            18 => 
            array (
                'id' => 8841,
                'zip_code' => '89042',
                'routing_file' => '93-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            19 => 
            array (
                'id' => 8842,
                'zip_code' => '89043',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            20 => 
            array (
                'id' => 8843,
                'zip_code' => '89044',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            21 => 
            array (
                'id' => 8844,
                'zip_code' => '89045',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            22 => 
            array (
                'id' => 8845,
                'zip_code' => '89046',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            23 => 
            array (
                'id' => 8846,
                'zip_code' => '89047',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            24 => 
            array (
                'id' => 8847,
                'zip_code' => '89048',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            25 => 
            array (
                'id' => 8848,
                'zip_code' => '89049',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            26 => 
            array (
                'id' => 8849,
                'zip_code' => '89050',
                'routing_file' => '93-MIX-89050-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            27 => 
            array (
                'id' => 8850,
                'zip_code' => '89052',
                'routing_file' => '084-D58-REGNORD-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            28 => 
            array (
                'id' => 8823,
                'zip_code' => '89024',
                'routing_file' => '93-D52-POLISTEN-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            29 => 
            array (
                'id' => 8824,
                'zip_code' => '89025',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            30 => 
            array (
                'id' => 8825,
                'zip_code' => '89026',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            31 => 
            array (
                'id' => 8826,
                'zip_code' => '89027',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            32 => 
            array (
                'id' => 8827,
                'zip_code' => '89028',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            33 => 
            array (
                'id' => 8828,
                'zip_code' => '89029',
                'routing_file' => '93-D50-TAURIANO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            34 => 
            array (
                'id' => 8829,
                'zip_code' => '89030',
                'routing_file' => '93-MIX-89030-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            35 => 
            array (
                'id' => 8830,
                'zip_code' => '89031',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            36 => 
            array (
                'id' => 8831,
                'zip_code' => '89032',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            37 => 
            array (
                'id' => 8832,
                'zip_code' => '89033',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            38 => 
            array (
                'id' => 8833,
                'zip_code' => '89034',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            39 => 
            array (
                'id' => 8834,
                'zip_code' => '89035',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            40 => 
            array (
                'id' => 8835,
                'zip_code' => '89036',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            41 => 
            array (
                'id' => 8836,
                'zip_code' => '89037',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            42 => 
            array (
                'id' => 8837,
                'zip_code' => '89038',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            43 => 
            array (
                'id' => 8838,
                'zip_code' => '89039',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            44 => 
            array (
                'id' => 8839,
                'zip_code' => '89040',
                'routing_file' => '93-MIX-89040-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            45 => 
            array (
                'id' => 8840,
                'zip_code' => '89041',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            46 => 
            array (
                'id' => 8841,
                'zip_code' => '89042',
                'routing_file' => '93-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            47 => 
            array (
                'id' => 8842,
                'zip_code' => '89043',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            48 => 
            array (
                'id' => 8843,
                'zip_code' => '89044',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            49 => 
            array (
                'id' => 8844,
                'zip_code' => '89045',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            50 => 
            array (
                'id' => 8845,
                'zip_code' => '89046',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            51 => 
            array (
                'id' => 8846,
                'zip_code' => '89047',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            52 => 
            array (
                'id' => 8847,
                'zip_code' => '89048',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            53 => 
            array (
                'id' => 8848,
                'zip_code' => '89049',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            54 => 
            array (
                'id' => 8849,
                'zip_code' => '89050',
                'routing_file' => '93-MIX-89050-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            55 => 
            array (
                'id' => 8850,
                'zip_code' => '89052',
                'routing_file' => '084-D58-REGNORD-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            56 => 
            array (
                'id' => 8823,
                'zip_code' => '89024',
                'routing_file' => '93-D52-POLISTEN-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            57 => 
            array (
                'id' => 8824,
                'zip_code' => '89025',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            58 => 
            array (
                'id' => 8825,
                'zip_code' => '89026',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            59 => 
            array (
                'id' => 8826,
                'zip_code' => '89027',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            60 => 
            array (
                'id' => 8827,
                'zip_code' => '89028',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            61 => 
            array (
                'id' => 8828,
                'zip_code' => '89029',
                'routing_file' => '93-D50-TAURIANO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            62 => 
            array (
                'id' => 8829,
                'zip_code' => '89030',
                'routing_file' => '93-MIX-89030-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            63 => 
            array (
                'id' => 8830,
                'zip_code' => '89031',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            64 => 
            array (
                'id' => 8831,
                'zip_code' => '89032',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            65 => 
            array (
                'id' => 8832,
                'zip_code' => '89033',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            66 => 
            array (
                'id' => 8833,
                'zip_code' => '89034',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            67 => 
            array (
                'id' => 8834,
                'zip_code' => '89035',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            68 => 
            array (
                'id' => 8835,
                'zip_code' => '89036',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            69 => 
            array (
                'id' => 8836,
                'zip_code' => '89037',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            70 => 
            array (
                'id' => 8837,
                'zip_code' => '89038',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            71 => 
            array (
                'id' => 8838,
                'zip_code' => '89039',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            72 => 
            array (
                'id' => 8839,
                'zip_code' => '89040',
                'routing_file' => '93-MIX-89040-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            73 => 
            array (
                'id' => 8840,
                'zip_code' => '89041',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            74 => 
            array (
                'id' => 8841,
                'zip_code' => '89042',
                'routing_file' => '93-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            75 => 
            array (
                'id' => 8842,
                'zip_code' => '89043',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            76 => 
            array (
                'id' => 8843,
                'zip_code' => '89044',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            77 => 
            array (
                'id' => 8844,
                'zip_code' => '89045',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            78 => 
            array (
                'id' => 8845,
                'zip_code' => '89046',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            79 => 
            array (
                'id' => 8846,
                'zip_code' => '89047',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            80 => 
            array (
                'id' => 8847,
                'zip_code' => '89048',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            81 => 
            array (
                'id' => 8848,
                'zip_code' => '89049',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            82 => 
            array (
                'id' => 8849,
                'zip_code' => '89050',
                'routing_file' => '93-MIX-89050-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            83 => 
            array (
                'id' => 8850,
                'zip_code' => '89052',
                'routing_file' => '084-D58-REGNORD-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            84 => 
            array (
                'id' => 8823,
                'zip_code' => '89024',
                'routing_file' => '93-D52-POLISTEN-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            85 => 
            array (
                'id' => 8824,
                'zip_code' => '89025',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            86 => 
            array (
                'id' => 8825,
                'zip_code' => '89026',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            87 => 
            array (
                'id' => 8826,
                'zip_code' => '89027',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            88 => 
            array (
                'id' => 8827,
                'zip_code' => '89028',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            89 => 
            array (
                'id' => 8828,
                'zip_code' => '89029',
                'routing_file' => '93-D50-TAURIANO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            90 => 
            array (
                'id' => 8829,
                'zip_code' => '89030',
                'routing_file' => '93-MIX-89030-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            91 => 
            array (
                'id' => 8830,
                'zip_code' => '89031',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            92 => 
            array (
                'id' => 8831,
                'zip_code' => '89032',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            93 => 
            array (
                'id' => 8832,
                'zip_code' => '89033',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            94 => 
            array (
                'id' => 8833,
                'zip_code' => '89034',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            95 => 
            array (
                'id' => 8834,
                'zip_code' => '89035',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            96 => 
            array (
                'id' => 8835,
                'zip_code' => '89036',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            97 => 
            array (
                'id' => 8836,
                'zip_code' => '89037',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            98 => 
            array (
                'id' => 8837,
                'zip_code' => '89038',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            99 => 
            array (
                'id' => 8838,
                'zip_code' => '89039',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            100 => 
            array (
                'id' => 8839,
                'zip_code' => '89040',
                'routing_file' => '93-MIX-89040-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            101 => 
            array (
                'id' => 8840,
                'zip_code' => '89041',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            102 => 
            array (
                'id' => 8841,
                'zip_code' => '89042',
                'routing_file' => '93-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            103 => 
            array (
                'id' => 8842,
                'zip_code' => '89043',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            104 => 
            array (
                'id' => 8843,
                'zip_code' => '89044',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            105 => 
            array (
                'id' => 8844,
                'zip_code' => '89045',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            106 => 
            array (
                'id' => 8845,
                'zip_code' => '89046',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            107 => 
            array (
                'id' => 8846,
                'zip_code' => '89047',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            108 => 
            array (
                'id' => 8847,
                'zip_code' => '89048',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            109 => 
            array (
                'id' => 8848,
                'zip_code' => '89049',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            110 => 
            array (
                'id' => 8849,
                'zip_code' => '89050',
                'routing_file' => '93-MIX-89050-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            111 => 
            array (
                'id' => 8850,
                'zip_code' => '89052',
                'routing_file' => '084-D58-REGNORD-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            112 => 
            array (
                'id' => 8823,
                'zip_code' => '89024',
                'routing_file' => '93-D52-POLISTEN-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            113 => 
            array (
                'id' => 8824,
                'zip_code' => '89025',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            114 => 
            array (
                'id' => 8825,
                'zip_code' => '89026',
                'routing_file' => '93-D54-ROSARNO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            115 => 
            array (
                'id' => 8826,
                'zip_code' => '89027',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            116 => 
            array (
                'id' => 8827,
                'zip_code' => '89028',
                'routing_file' => '93-D56-PALMI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            117 => 
            array (
                'id' => 8828,
                'zip_code' => '89029',
                'routing_file' => '93-D50-TAURIANO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            118 => 
            array (
                'id' => 8829,
                'zip_code' => '89030',
                'routing_file' => '93-MIX-89030-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            119 => 
            array (
                'id' => 8830,
                'zip_code' => '89031',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            120 => 
            array (
                'id' => 8831,
                'zip_code' => '89032',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            121 => 
            array (
                'id' => 8832,
                'zip_code' => '89033',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            122 => 
            array (
                'id' => 8833,
                'zip_code' => '89034',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            123 => 
            array (
                'id' => 8834,
                'zip_code' => '89035',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            124 => 
            array (
                'id' => 8835,
                'zip_code' => '89036',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            125 => 
            array (
                'id' => 8836,
                'zip_code' => '89037',
                'routing_file' => '93-D46-MARINAAR-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            126 => 
            array (
                'id' => 8837,
                'zip_code' => '89038',
                'routing_file' => '93-D55-MELITOPS-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            127 => 
            array (
                'id' => 8838,
                'zip_code' => '89039',
                'routing_file' => '93-D45-BOVALINO-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            128 => 
            array (
                'id' => 8839,
                'zip_code' => '89040',
                'routing_file' => '93-MIX-89040-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            129 => 
            array (
                'id' => 8840,
                'zip_code' => '89041',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            130 => 
            array (
                'id' => 8841,
                'zip_code' => '89042',
                'routing_file' => '93-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            131 => 
            array (
                'id' => 8842,
                'zip_code' => '89043',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            132 => 
            array (
                'id' => 8843,
                'zip_code' => '89044',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            133 => 
            array (
                'id' => 8844,
                'zip_code' => '89045',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            134 => 
            array (
                'id' => 8845,
                'zip_code' => '89046',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            135 => 
            array (
                'id' => 8846,
                'zip_code' => '89047',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            136 => 
            array (
                'id' => 8847,
                'zip_code' => '89048',
                'routing_file' => '086-D47-LOCRI-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            137 => 
            array (
                'id' => 8848,
                'zip_code' => '89049',
                'routing_file' => '93-D48-MARINACA-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            138 => 
            array (
                'id' => 8849,
                'zip_code' => '89050',
                'routing_file' => '93-MIX-89050-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
            139 => 
            array (
                'id' => 8850,
                'zip_code' => '89052',
                'routing_file' => '084-D58-REGNORD-x21',
                'province' => 'Reggio Calabria',
                'province_iso_code' => 'RC',
                'sortation_name' => 'Lamezia',
                'sortation_id' => '67',
                'sortation_name_on_bag' => '67-Lamezia',
            ),
        ));
        
        
    }
}