<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'country_id' => 225,
                'product_name' => 'YODEL_TEST_PRODUCT',
                'insurance' => '10.00',
                'description' => '',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 0,
                'width' => 0,
                'height' => 0,
                'vol_weight' => '0.000',
                'vol_denominator' => 0,
                'is_untrack' => 0,
                'remotearea_charges' => '0.000',
                'fuel_charges' => '0.000',
                'added_date' => '2017-11-15 19:24:45',
                'added_by' => 148,
                'transit_time' => '3',
            ),
            1 => 
            array (
                'id' => 2,
                'country_id' => 225,
                'product_name' => 'TEST_PRODUCT2',
                'insurance' => '10.00',
                'description' => 'test',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 30,
                'width' => 30,
                'height' => 30,
                'vol_weight' => '30.000',
                'vol_denominator' => 5000,
                'is_untrack' => 1,
                'remotearea_charges' => '1.000',
                'fuel_charges' => '1.000',
                'added_date' => '2018-01-09 21:54:48',
                'added_by' => 58,
                'transit_time' => '2',
            ),
            2 => 
            array (
                'id' => 1,
                'country_id' => 225,
                'product_name' => 'YODEL_TEST_PRODUCT',
                'insurance' => '10.00',
                'description' => '',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 0,
                'width' => 0,
                'height' => 0,
                'vol_weight' => '0.000',
                'vol_denominator' => 0,
                'is_untrack' => 0,
                'remotearea_charges' => '0.000',
                'fuel_charges' => '0.000',
                'added_date' => '2017-11-15 19:24:45',
                'added_by' => 148,
                'transit_time' => '3',
            ),
            3 => 
            array (
                'id' => 2,
                'country_id' => 225,
                'product_name' => 'TEST_PRODUCT2',
                'insurance' => '10.00',
                'description' => 'test',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 30,
                'width' => 30,
                'height' => 30,
                'vol_weight' => '30.000',
                'vol_denominator' => 5000,
                'is_untrack' => 1,
                'remotearea_charges' => '1.000',
                'fuel_charges' => '1.000',
                'added_date' => '2018-01-09 21:54:48',
                'added_by' => 58,
                'transit_time' => '2',
            ),
            4 => 
            array (
                'id' => 1,
                'country_id' => 225,
                'product_name' => 'YODEL_TEST_PRODUCT',
                'insurance' => '10.00',
                'description' => '',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 0,
                'width' => 0,
                'height' => 0,
                'vol_weight' => '0.000',
                'vol_denominator' => 0,
                'is_untrack' => 0,
                'remotearea_charges' => '0.000',
                'fuel_charges' => '0.000',
                'added_date' => '2017-11-15 19:24:45',
                'added_by' => 148,
                'transit_time' => '3',
            ),
            5 => 
            array (
                'id' => 2,
                'country_id' => 225,
                'product_name' => 'TEST_PRODUCT2',
                'insurance' => '10.00',
                'description' => 'test',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 30,
                'width' => 30,
                'height' => 30,
                'vol_weight' => '30.000',
                'vol_denominator' => 5000,
                'is_untrack' => 1,
                'remotearea_charges' => '1.000',
                'fuel_charges' => '1.000',
                'added_date' => '2018-01-09 21:54:48',
                'added_by' => 58,
                'transit_time' => '2',
            ),
            6 => 
            array (
                'id' => 1,
                'country_id' => 225,
                'product_name' => 'YODEL_TEST_PRODUCT',
                'insurance' => '10.00',
                'description' => '',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 0,
                'width' => 0,
                'height' => 0,
                'vol_weight' => '0.000',
                'vol_denominator' => 0,
                'is_untrack' => 0,
                'remotearea_charges' => '0.000',
                'fuel_charges' => '0.000',
                'added_date' => '2017-11-15 19:24:45',
                'added_by' => 148,
                'transit_time' => '3',
            ),
            7 => 
            array (
                'id' => 2,
                'country_id' => 225,
                'product_name' => 'TEST_PRODUCT2',
                'insurance' => '10.00',
                'description' => 'test',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 30,
                'width' => 30,
                'height' => 30,
                'vol_weight' => '30.000',
                'vol_denominator' => 5000,
                'is_untrack' => 1,
                'remotearea_charges' => '1.000',
                'fuel_charges' => '1.000',
                'added_date' => '2018-01-09 21:54:48',
                'added_by' => 58,
                'transit_time' => '2',
            ),
            8 => 
            array (
                'id' => 1,
                'country_id' => 225,
                'product_name' => 'YODEL_TEST_PRODUCT',
                'insurance' => '10.00',
                'description' => '',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 0,
                'width' => 0,
                'height' => 0,
                'vol_weight' => '0.000',
                'vol_denominator' => 0,
                'is_untrack' => 0,
                'remotearea_charges' => '0.000',
                'fuel_charges' => '0.000',
                'added_date' => '2017-11-15 19:24:45',
                'added_by' => 148,
                'transit_time' => '3',
            ),
            9 => 
            array (
                'id' => 2,
                'country_id' => 225,
                'product_name' => 'TEST_PRODUCT2',
                'insurance' => '10.00',
                'description' => 'test',
                'status' => 1,
                'from_weight' => '0.000',
                'to_weight' => '30.000',
                'logo' => '',
                'length' => 30,
                'width' => 30,
                'height' => 30,
                'vol_weight' => '30.000',
                'vol_denominator' => 5000,
                'is_untrack' => 1,
                'remotearea_charges' => '1.000',
                'fuel_charges' => '1.000',
                'added_date' => '2018-01-09 21:54:48',
                'added_by' => 58,
                'transit_time' => '2',
            ),
        ));
        
        
    }
}