<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RemoteareaChargesServicesUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('remotearea_charges_services_users')->delete();
        
        \DB::table('remotearea_charges_services_users')->insert(array (
            0 => 
            array (
                'id' => 5,
                'remotearea_group_id' => 16,
                'remotearea_charges' => '5.00',
                'service_id' => 252,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '0',
                'user_account_id' => 148,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2018-01-18 13:23:28',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            1 => 
            array (
                'id' => 94,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            2 => 
            array (
                'id' => 95,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '2.93',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            3 => 
            array (
                'id' => 96,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            4 => 
            array (
                'id' => 97,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '11.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            5 => 
            array (
                'id' => 118,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            6 => 
            array (
                'id' => 119,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            7 => 
            array (
                'id' => 120,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            8 => 
            array (
                'id' => 136,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            9 => 
            array (
                'id' => 137,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            10 => 
            array (
                'id' => 138,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '1.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            11 => 
            array (
                'id' => 139,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            12 => 
            array (
                'id' => 140,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '8.08',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            13 => 
            array (
                'id' => 141,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            14 => 
            array (
                'id' => 142,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            15 => 
            array (
                'id' => 174,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 38,
                'from_weight' => '0.00',
                'to_weight' => '10.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            16 => 
            array (
                'id' => 175,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '14.00',
                'service_id' => 38,
                'from_weight' => '10.00',
                'to_weight' => '20.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            17 => 
            array (
                'id' => 177,
                'remotearea_group_id' => 325,
                'remotearea_charges' => '2.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            18 => 
            array (
                'id' => 178,
                'remotearea_group_id' => 324,
                'remotearea_charges' => '3.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            19 => 
            array (
                'id' => 199,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '3.00',
                'service_id' => 226,
                'from_weight' => '1.00',
                'to_weight' => '2.00',
                'formulla' => '',
                'user_account_id' => 2336,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-09-09 16:20:14',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            20 => 
            array (
                'id' => 5,
                'remotearea_group_id' => 16,
                'remotearea_charges' => '5.00',
                'service_id' => 252,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '0',
                'user_account_id' => 148,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2018-01-18 13:23:28',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            21 => 
            array (
                'id' => 94,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            22 => 
            array (
                'id' => 95,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '2.93',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            23 => 
            array (
                'id' => 96,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            24 => 
            array (
                'id' => 97,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '11.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            25 => 
            array (
                'id' => 118,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            26 => 
            array (
                'id' => 119,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            27 => 
            array (
                'id' => 120,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            28 => 
            array (
                'id' => 136,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            29 => 
            array (
                'id' => 137,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            30 => 
            array (
                'id' => 138,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '1.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            31 => 
            array (
                'id' => 139,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            32 => 
            array (
                'id' => 140,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '8.08',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            33 => 
            array (
                'id' => 141,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            34 => 
            array (
                'id' => 142,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            35 => 
            array (
                'id' => 174,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 38,
                'from_weight' => '0.00',
                'to_weight' => '10.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            36 => 
            array (
                'id' => 175,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '14.00',
                'service_id' => 38,
                'from_weight' => '10.00',
                'to_weight' => '20.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            37 => 
            array (
                'id' => 177,
                'remotearea_group_id' => 325,
                'remotearea_charges' => '2.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            38 => 
            array (
                'id' => 178,
                'remotearea_group_id' => 324,
                'remotearea_charges' => '3.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            39 => 
            array (
                'id' => 199,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '3.00',
                'service_id' => 226,
                'from_weight' => '1.00',
                'to_weight' => '2.00',
                'formulla' => '',
                'user_account_id' => 2336,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-09-09 16:20:14',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            40 => 
            array (
                'id' => 5,
                'remotearea_group_id' => 16,
                'remotearea_charges' => '5.00',
                'service_id' => 252,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '0',
                'user_account_id' => 148,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2018-01-18 13:23:28',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            41 => 
            array (
                'id' => 94,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            42 => 
            array (
                'id' => 95,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '2.93',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            43 => 
            array (
                'id' => 96,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            44 => 
            array (
                'id' => 97,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '11.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            45 => 
            array (
                'id' => 118,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            46 => 
            array (
                'id' => 119,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            47 => 
            array (
                'id' => 120,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            48 => 
            array (
                'id' => 136,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            49 => 
            array (
                'id' => 137,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            50 => 
            array (
                'id' => 138,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '1.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            51 => 
            array (
                'id' => 139,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            52 => 
            array (
                'id' => 140,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '8.08',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            53 => 
            array (
                'id' => 141,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            54 => 
            array (
                'id' => 142,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            55 => 
            array (
                'id' => 174,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 38,
                'from_weight' => '0.00',
                'to_weight' => '10.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            56 => 
            array (
                'id' => 175,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '14.00',
                'service_id' => 38,
                'from_weight' => '10.00',
                'to_weight' => '20.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            57 => 
            array (
                'id' => 177,
                'remotearea_group_id' => 325,
                'remotearea_charges' => '2.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            58 => 
            array (
                'id' => 178,
                'remotearea_group_id' => 324,
                'remotearea_charges' => '3.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            59 => 
            array (
                'id' => 199,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '3.00',
                'service_id' => 226,
                'from_weight' => '1.00',
                'to_weight' => '2.00',
                'formulla' => '',
                'user_account_id' => 2336,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-09-09 16:20:14',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            60 => 
            array (
                'id' => 5,
                'remotearea_group_id' => 16,
                'remotearea_charges' => '5.00',
                'service_id' => 252,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '0',
                'user_account_id' => 148,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2018-01-18 13:23:28',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            61 => 
            array (
                'id' => 94,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            62 => 
            array (
                'id' => 95,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '2.93',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            63 => 
            array (
                'id' => 96,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            64 => 
            array (
                'id' => 97,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '11.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            65 => 
            array (
                'id' => 118,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            66 => 
            array (
                'id' => 119,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            67 => 
            array (
                'id' => 120,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            68 => 
            array (
                'id' => 136,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            69 => 
            array (
                'id' => 137,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            70 => 
            array (
                'id' => 138,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '1.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            71 => 
            array (
                'id' => 139,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            72 => 
            array (
                'id' => 140,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '8.08',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            73 => 
            array (
                'id' => 141,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            74 => 
            array (
                'id' => 142,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            75 => 
            array (
                'id' => 174,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 38,
                'from_weight' => '0.00',
                'to_weight' => '10.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            76 => 
            array (
                'id' => 175,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '14.00',
                'service_id' => 38,
                'from_weight' => '10.00',
                'to_weight' => '20.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            77 => 
            array (
                'id' => 177,
                'remotearea_group_id' => 325,
                'remotearea_charges' => '2.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            78 => 
            array (
                'id' => 178,
                'remotearea_group_id' => 324,
                'remotearea_charges' => '3.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            79 => 
            array (
                'id' => 199,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '3.00',
                'service_id' => 226,
                'from_weight' => '1.00',
                'to_weight' => '2.00',
                'formulla' => '',
                'user_account_id' => 2336,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-09-09 16:20:14',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            80 => 
            array (
                'id' => 5,
                'remotearea_group_id' => 16,
                'remotearea_charges' => '5.00',
                'service_id' => 252,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '0',
                'user_account_id' => 148,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2018-01-18 13:23:28',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            81 => 
            array (
                'id' => 94,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            82 => 
            array (
                'id' => 95,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '2.93',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            83 => 
            array (
                'id' => 96,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            84 => 
            array (
                'id' => 97,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '11.00',
                'service_id' => 277,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-01-03 18:07:32',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            85 => 
            array (
                'id' => 118,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            86 => 
            array (
                'id' => 119,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '10.87',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            87 => 
            array (
                'id' => 120,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '2.95',
                'service_id' => 263,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2294,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-03-05 17:21:47',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            88 => 
            array (
                'id' => 136,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            89 => 
            array (
                'id' => 137,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 3,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:05',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            90 => 
            array (
                'id' => 138,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '1.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            91 => 
            array (
                'id' => 139,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            92 => 
            array (
                'id' => 140,
                'remotearea_group_id' => 25,
                'remotearea_charges' => '8.08',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            93 => 
            array (
                'id' => 141,
                'remotearea_group_id' => 38,
                'remotearea_charges' => '10.10',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            94 => 
            array (
                'id' => 142,
                'remotearea_group_id' => 35,
                'remotearea_charges' => '9.09',
                'service_id' => 2,
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2313,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-04-02 12:13:43',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            95 => 
            array (
                'id' => 174,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '12.00',
                'service_id' => 38,
                'from_weight' => '0.00',
                'to_weight' => '10.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            96 => 
            array (
                'id' => 175,
                'remotearea_group_id' => 2,
                'remotearea_charges' => '14.00',
                'service_id' => 38,
                'from_weight' => '10.00',
                'to_weight' => '20.00',
                'formulla' => '',
                'user_account_id' => 2302,
                'is_deleted' => 'N',
                'added_by' => 2191,
                'added_date' => '2019-08-13 09:18:55',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            97 => 
            array (
                'id' => 177,
                'remotearea_group_id' => 325,
                'remotearea_charges' => '2.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            98 => 
            array (
                'id' => 178,
                'remotearea_group_id' => 324,
                'remotearea_charges' => '3.00',
                'service_id' => 313,
                'from_weight' => '1.00',
                'to_weight' => '30.00',
                'formulla' => '',
                'user_account_id' => 2297,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-08-16 13:21:33',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
            99 => 
            array (
                'id' => 199,
                'remotearea_group_id' => 34,
                'remotearea_charges' => '3.00',
                'service_id' => 226,
                'from_weight' => '1.00',
                'to_weight' => '2.00',
                'formulla' => '',
                'user_account_id' => 2336,
                'is_deleted' => 'N',
                'added_by' => 58,
                'added_date' => '2019-09-09 16:20:14',
                'updated_by' => 0,
                'updated_date' => NULL,
            ),
        ));
        
        
    }
}