<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RemoteareasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('remoteareas')->delete();
        
        \DB::table('remoteareas')->insert(array (
            0 => 
            array (
                'id' => 14206,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9774',
                'to_postcode' => '9774',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            1 => 
            array (
                'id' => 14207,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9775',
                'to_postcode' => '9775',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            2 => 
            array (
                'id' => 14208,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9776',
                'to_postcode' => '9776',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            3 => 
            array (
                'id' => 14209,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9777',
                'to_postcode' => '9777',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            4 => 
            array (
                'id' => 14210,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9778',
                'to_postcode' => '9778',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            5 => 
            array (
                'id' => 14211,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9779',
                'to_postcode' => '9779',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            6 => 
            array (
                'id' => 14212,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9780',
                'to_postcode' => '9780',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            7 => 
            array (
                'id' => 14213,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9782',
                'to_postcode' => '9782',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            8 => 
            array (
                'id' => 14214,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9783',
                'to_postcode' => '9783',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            9 => 
            array (
                'id' => 14215,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9784',
                'to_postcode' => '9784',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            10 => 
            array (
                'id' => 14216,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9785',
                'to_postcode' => '9785',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            11 => 
            array (
                'id' => 14217,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9786',
                'to_postcode' => '9786',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            12 => 
            array (
                'id' => 14218,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9787',
                'to_postcode' => '9787',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            13 => 
            array (
                'id' => 14219,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9788',
                'to_postcode' => '9788',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            14 => 
            array (
                'id' => 14220,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9790',
                'to_postcode' => '9790',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            15 => 
            array (
                'id' => 14206,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9774',
                'to_postcode' => '9774',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            16 => 
            array (
                'id' => 14207,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9775',
                'to_postcode' => '9775',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            17 => 
            array (
                'id' => 14208,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9776',
                'to_postcode' => '9776',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            18 => 
            array (
                'id' => 14209,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9777',
                'to_postcode' => '9777',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            19 => 
            array (
                'id' => 14210,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9778',
                'to_postcode' => '9778',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            20 => 
            array (
                'id' => 14211,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9779',
                'to_postcode' => '9779',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            21 => 
            array (
                'id' => 14212,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9780',
                'to_postcode' => '9780',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            22 => 
            array (
                'id' => 14213,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9782',
                'to_postcode' => '9782',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            23 => 
            array (
                'id' => 14214,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9783',
                'to_postcode' => '9783',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            24 => 
            array (
                'id' => 14215,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9784',
                'to_postcode' => '9784',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            25 => 
            array (
                'id' => 14216,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9785',
                'to_postcode' => '9785',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            26 => 
            array (
                'id' => 14217,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9786',
                'to_postcode' => '9786',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            27 => 
            array (
                'id' => 14218,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9787',
                'to_postcode' => '9787',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            28 => 
            array (
                'id' => 14219,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9788',
                'to_postcode' => '9788',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            29 => 
            array (
                'id' => 14220,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9790',
                'to_postcode' => '9790',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            30 => 
            array (
                'id' => 14206,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9774',
                'to_postcode' => '9774',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            31 => 
            array (
                'id' => 14207,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9775',
                'to_postcode' => '9775',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            32 => 
            array (
                'id' => 14208,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9776',
                'to_postcode' => '9776',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            33 => 
            array (
                'id' => 14209,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9777',
                'to_postcode' => '9777',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            34 => 
            array (
                'id' => 14210,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9778',
                'to_postcode' => '9778',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            35 => 
            array (
                'id' => 14211,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9779',
                'to_postcode' => '9779',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            36 => 
            array (
                'id' => 14212,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9780',
                'to_postcode' => '9780',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            37 => 
            array (
                'id' => 14213,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9782',
                'to_postcode' => '9782',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            38 => 
            array (
                'id' => 14214,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9783',
                'to_postcode' => '9783',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            39 => 
            array (
                'id' => 14215,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9784',
                'to_postcode' => '9784',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            40 => 
            array (
                'id' => 14216,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9785',
                'to_postcode' => '9785',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            41 => 
            array (
                'id' => 14217,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9786',
                'to_postcode' => '9786',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            42 => 
            array (
                'id' => 14218,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9787',
                'to_postcode' => '9787',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            43 => 
            array (
                'id' => 14219,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9788',
                'to_postcode' => '9788',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            44 => 
            array (
                'id' => 14220,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9790',
                'to_postcode' => '9790',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            45 => 
            array (
                'id' => 14206,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9774',
                'to_postcode' => '9774',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            46 => 
            array (
                'id' => 14207,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9775',
                'to_postcode' => '9775',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            47 => 
            array (
                'id' => 14208,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9776',
                'to_postcode' => '9776',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            48 => 
            array (
                'id' => 14209,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9777',
                'to_postcode' => '9777',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            49 => 
            array (
                'id' => 14210,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9778',
                'to_postcode' => '9778',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            50 => 
            array (
                'id' => 14211,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9779',
                'to_postcode' => '9779',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            51 => 
            array (
                'id' => 14212,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9780',
                'to_postcode' => '9780',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            52 => 
            array (
                'id' => 14213,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9782',
                'to_postcode' => '9782',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            53 => 
            array (
                'id' => 14214,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9783',
                'to_postcode' => '9783',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            54 => 
            array (
                'id' => 14215,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9784',
                'to_postcode' => '9784',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            55 => 
            array (
                'id' => 14216,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9785',
                'to_postcode' => '9785',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            56 => 
            array (
                'id' => 14217,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9786',
                'to_postcode' => '9786',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            57 => 
            array (
                'id' => 14218,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9787',
                'to_postcode' => '9787',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            58 => 
            array (
                'id' => 14219,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9788',
                'to_postcode' => '9788',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            59 => 
            array (
                'id' => 14220,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9790',
                'to_postcode' => '9790',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            60 => 
            array (
                'id' => 14206,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9774',
                'to_postcode' => '9774',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            61 => 
            array (
                'id' => 14207,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9775',
                'to_postcode' => '9775',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            62 => 
            array (
                'id' => 14208,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9776',
                'to_postcode' => '9776',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            63 => 
            array (
                'id' => 14209,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9777',
                'to_postcode' => '9777',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            64 => 
            array (
                'id' => 14210,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9778',
                'to_postcode' => '9778',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            65 => 
            array (
                'id' => 14211,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9779',
                'to_postcode' => '9779',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            66 => 
            array (
                'id' => 14212,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9780',
                'to_postcode' => '9780',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            67 => 
            array (
                'id' => 14213,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9782',
                'to_postcode' => '9782',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            68 => 
            array (
                'id' => 14214,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9783',
                'to_postcode' => '9783',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            69 => 
            array (
                'id' => 14215,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9784',
                'to_postcode' => '9784',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            70 => 
            array (
                'id' => 14216,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9785',
                'to_postcode' => '9785',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            71 => 
            array (
                'id' => 14217,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9786',
                'to_postcode' => '9786',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            72 => 
            array (
                'id' => 14218,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9787',
                'to_postcode' => '9787',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            73 => 
            array (
                'id' => 14219,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9788',
                'to_postcode' => '9788',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            74 => 
            array (
                'id' => 14220,
                'remoteareas_groups_id' => 325,
                'country_id' => 197,
                'from_postcode' => '9790',
                'to_postcode' => '9790',
                'city' => '',
                'is_deleted' => 'N',
                'added_by' => 2295,
                'added_date' => '2019-09-18 10:55:11',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
        ));
        
        
    }
}