<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceAgentMappingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('service_agent_mappings')->delete();
        
        \DB::table('service_agent_mappings')->insert(array (
            0 => 
            array (
                'id' => 45,
                'serviceid' => 63,
                'agentid' => 4,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => '',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '5.00',
                'email' => NULL,
            ),
            1 => 
            array (
                'id' => 263,
                'serviceid' => 68,
                'agentid' => 42,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'ftp.dpd.de',
                'ftp_username' => 'KD225393SK',
                'ftp_password' => 'y2nyp',
                'integration_type' => 'EDI',
                'class_file_name' => 'DPDDE',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '25.00',
                'email' => NULL,
            ),
            2 => 
            array (
                'id' => 264,
                'serviceid' => 105,
                'agentid' => 42,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'ftp.dpd.de',
                'ftp_username' => 'KD225393SK',
                'ftp_password' => 'y2nyp',
                'integration_type' => 'EDI',
                'class_file_name' => 'DPD',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '25.00',
                'email' => NULL,
            ),
            3 => 
            array (
                'id' => 424,
                'serviceid' => 228,
                'agentid' => 43,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'ftp.dpd.de',
                'ftp_username' => '2406018432',
                'ftp_password' => 'dpd',
                'integration_type' => 'EDI',
                'class_file_name' => 'DPD',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            4 => 
            array (
                'id' => 429,
                'serviceid' => 39,
                'agentid' => 46,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'EDI',
                'class_file_name' => 'DPDNL',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            5 => 
            array (
                'id' => 430,
                'serviceid' => 69,
                'agentid' => 46,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'API',
                'class_file_name' => 'MailMissionSolution',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            6 => 
            array (
                'id' => 1003,
                'serviceid' => 161,
                'agentid' => 3,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => 'http://local.oneworldexpress.co.uk/main/agent_details.php',
                'api_username' => 'fsdfdsf',
                'api_password' => 'sdfsdf',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'API',
                'class_file_name' => 'DPDPoland',
                'insurance_charges' => '15.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '15.00',
                'oversize_charges' => '15.00',
                'address_change_charges' => '15.00',
                'other_surcharges' => '15.00',
                'return_charges' => '15.00',
                'relabel_charges' => '15.00',
                'wrong_address_charges' => '15.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            7 => 
            array (
                'id' => 1004,
                'serviceid' => 245,
                'agentid' => 3,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'EDI',
                'class_file_name' => 'Hungary',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '2.00',
                'email' => NULL,
            ),
            8 => 
            array (
                'id' => 1005,
                'serviceid' => 250,
                'agentid' => 3,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'EDI',
                'class_file_name' => 'CzechPost',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '2.00',
                'email' => NULL,
            ),
            9 => 
            array (
                'id' => 1006,
                'serviceid' => 254,
                'agentid' => 3,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'EDI',
                'class_file_name' => 'EEuroBattery',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            10 => 
            array (
                'id' => 1109,
                'serviceid' => 226,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '10.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '10.00',
                'oversize_charges' => '10.00',
                'address_change_charges' => '10.00',
                'other_surcharges' => '10.00',
                'return_charges' => '10.00',
                'relabel_charges' => '10.00',
                'wrong_address_charges' => '10.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => 'm@oneworld.com,s@one.com',
            ),
            11 => 
            array (
                'id' => 1110,
                'serviceid' => 2,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '10.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '10.00',
                'oversize_charges' => '10.00',
                'address_change_charges' => '10.00',
                'other_surcharges' => '10.00',
                'return_charges' => '10.00',
                'relabel_charges' => '10.00',
                'wrong_address_charges' => '10.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            12 => 
            array (
                'id' => 1111,
                'serviceid' => 4,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            13 => 
            array (
                'id' => 1112,
                'serviceid' => 3,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '30.00',
                'email' => NULL,
            ),
            14 => 
            array (
                'id' => 1113,
                'serviceid' => 38,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '3.00',
                'email' => NULL,
            ),
            15 => 
            array (
                'id' => 1114,
                'serviceid' => 227,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => 'cs.yodel.co.uk',
                'ftp_username' => 'oneworld',
                'ftp_password' => 'serv1ce',
                'integration_type' => 'EDI',
                'class_file_name' => 'Yodel',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '3.00',
                'email' => NULL,
            ),
            16 => 
            array (
                'id' => 1115,
                'serviceid' => 12,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '144.87.142.139',
                'ftp_username' => 'E000451',
                'ftp_password' => 'QiU87TpK',
                'integration_type' => 'EDI',
                'class_file_name' => 'RoyalMail',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '2.00',
                'email' => NULL,
            ),
            17 => 
            array (
                'id' => 1116,
                'serviceid' => 13,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '144.87.142.139',
                'ftp_username' => 'E000451',
                'ftp_password' => 'QiU87TpK',
                'integration_type' => 'EDI',
                'class_file_name' => 'RoyalMail',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '2.00',
                'email' => NULL,
            ),
            18 => 
            array (
                'id' => 1117,
                'serviceid' => 22,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => 'http://xmlpi-ea.dhl.com/XMLShippingServlet',
                'api_username' => 'TransglobeUK',
                'api_password' => 'pKbVr8sQ3',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'API',
                'class_file_name' => 'DHL',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '1000.00',
                'email' => NULL,
            ),
            19 => 
            array (
                'id' => 1118,
                'serviceid' => 229,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => 'https://www.myparcellabel.co.uk/',
                'api_username' => 'oneworldapi',
                'api_password' => '16Sept6214',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'API',
                'class_file_name' => 'Hermes',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '15.00',
                'email' => NULL,
            ),
            20 => 
            array (
                'id' => 1119,
                'serviceid' => 14,
                'agentid' => 1,
                'linehaul_agent' => 0,
                'account_number' => '',
                'api_url' => '',
                'api_username' => '',
                'api_password' => '',
                'ftp_host' => '',
                'ftp_username' => '',
                'ftp_password' => '',
                'integration_type' => 'EDI',
                'class_file_name' => 'RoyalMail',
                'insurance_charges' => '0.00',
                'insurance_cover' => '0.00',
                'reroute_charges' => '0.00',
                'oversize_charges' => '0.00',
                'address_change_charges' => '0.00',
                'other_surcharges' => '0.00',
                'return_charges' => '0.00',
                'relabel_charges' => '0.00',
                'wrong_address_charges' => '0.00',
                'from_weight' => '0.00',
                'to_weight' => '2.00',
                'email' => NULL,
            ),
        ));
        
        
    }
}