<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TariffsDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tariffs_details')->delete();
        
        \DB::table('tariffs_details')->insert(array (
            0 => 
            array (
                'id' => 61470,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            1 => 
            array (
                'id' => 61471,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            2 => 
            array (
                'id' => 61472,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.01',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            3 => 
            array (
                'id' => 61473,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            4 => 
            array (
                'id' => 61474,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2823,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.09',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            5 => 
            array (
                'id' => 61475,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2820,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.35',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            6 => 
            array (
                'id' => 61476,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.17',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            7 => 
            array (
                'id' => 61477,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2821,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.98',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            8 => 
            array (
                'id' => 61478,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.43',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            9 => 
            array (
                'id' => 61479,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2822,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '4.80',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            10 => 
            array (
                'id' => 61480,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            11 => 
            array (
                'id' => 61481,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '6.53',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            12 => 
            array (
                'id' => 61482,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '5.66',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            13 => 
            array (
                'id' => 61483,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.14',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            14 => 
            array (
                'id' => 61470,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            15 => 
            array (
                'id' => 61471,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            16 => 
            array (
                'id' => 61472,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.01',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            17 => 
            array (
                'id' => 61473,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            18 => 
            array (
                'id' => 61474,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2823,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.09',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            19 => 
            array (
                'id' => 61475,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2820,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.35',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            20 => 
            array (
                'id' => 61476,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.17',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            21 => 
            array (
                'id' => 61477,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2821,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.98',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            22 => 
            array (
                'id' => 61478,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.43',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            23 => 
            array (
                'id' => 61479,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2822,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '4.80',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            24 => 
            array (
                'id' => 61480,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            25 => 
            array (
                'id' => 61481,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '6.53',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            26 => 
            array (
                'id' => 61482,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '5.66',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            27 => 
            array (
                'id' => 61483,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.14',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            28 => 
            array (
                'id' => 61470,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            29 => 
            array (
                'id' => 61471,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            30 => 
            array (
                'id' => 61472,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.01',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            31 => 
            array (
                'id' => 61473,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            32 => 
            array (
                'id' => 61474,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2823,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.09',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            33 => 
            array (
                'id' => 61475,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2820,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.35',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            34 => 
            array (
                'id' => 61476,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.17',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            35 => 
            array (
                'id' => 61477,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2821,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.98',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            36 => 
            array (
                'id' => 61478,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.43',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            37 => 
            array (
                'id' => 61479,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2822,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '4.80',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            38 => 
            array (
                'id' => 61480,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            39 => 
            array (
                'id' => 61481,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '6.53',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            40 => 
            array (
                'id' => 61482,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '5.66',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            41 => 
            array (
                'id' => 61483,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.14',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            42 => 
            array (
                'id' => 61470,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            43 => 
            array (
                'id' => 61471,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            44 => 
            array (
                'id' => 61472,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.01',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            45 => 
            array (
                'id' => 61473,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            46 => 
            array (
                'id' => 61474,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2823,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.09',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            47 => 
            array (
                'id' => 61475,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2820,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.35',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            48 => 
            array (
                'id' => 61476,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.17',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            49 => 
            array (
                'id' => 61477,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2821,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.98',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            50 => 
            array (
                'id' => 61478,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.43',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            51 => 
            array (
                'id' => 61479,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2822,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '4.80',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            52 => 
            array (
                'id' => 61480,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            53 => 
            array (
                'id' => 61481,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '6.53',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            54 => 
            array (
                'id' => 61482,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '5.66',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            55 => 
            array (
                'id' => 61483,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.14',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            56 => 
            array (
                'id' => 61470,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            57 => 
            array (
                'id' => 61471,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            58 => 
            array (
                'id' => 61472,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '5.01',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            59 => 
            array (
                'id' => 61473,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.82',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            60 => 
            array (
                'id' => 61474,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2823,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.09',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            61 => 
            array (
                'id' => 61475,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2820,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.35',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            62 => 
            array (
                'id' => 61476,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.17',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            63 => 
            array (
                'id' => 61477,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2821,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '2.98',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            64 => 
            array (
                'id' => 61478,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '3.43',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            65 => 
            array (
                'id' => 61479,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 2822,
                'weight_from' => '0.50',
                'weight_to' => '0.75',
                'weight_cost' => '4.80',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            66 => 
            array (
                'id' => 61480,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.51',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            67 => 
            array (
                'id' => 61481,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '6.53',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            68 => 
            array (
                'id' => 61482,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '5.66',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
            69 => 
            array (
                'id' => 61483,
                'tariffs_id' => 240676,
                'from_zone_id' => 2819,
                'to_zone_id' => 0,
                'weight_from' => '0.75',
                'weight_to' => '1.00',
                'weight_cost' => '3.14',
                'piece_cost' => '0.00',
                'formula' => '',
            ),
        ));
        
        
    }
}