<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TariffsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tariffs')->delete();
        
        \DB::table('tariffs')->insert(array (
            0 => 
            array (
                'id' => 240577,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-06 17:48:53',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 12:48:53',
                'updated_by' => 2282,
            ),
            1 => 
            array (
                'id' => 240578,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 21,
                'date_added' => '2019-09-06 23:01:34',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 18:01:34',
                'updated_by' => 2282,
            ),
            2 => 
            array (
                'id' => 240579,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 3,
                'name' => 'DEMO_TARIFF_YODEL1HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:06',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:06',
                'updated_by' => 58,
            ),
            3 => 
            array (
                'id' => 240580,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 4,
                'name' => 'DEMO_TARIFF_YODEL3HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:51',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:51',
                'updated_by' => 58,
            ),
            4 => 
            array (
                'id' => 240581,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'DEMO_TARIFF_YODEL1CN',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:19:23',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:19:23',
                'updated_by' => 58,
            ),
            5 => 
            array (
                'id' => 240582,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 14,
                'name' => 'DEMO_TARIFF_ROYALMAIL1L',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:20:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:20:05',
                'updated_by' => 58,
            ),
            6 => 
            array (
                'id' => 240583,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 12,
                'name' => 'DEMO_TARIFF_ROYALMAILTP2',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:21:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:21:05',
                'updated_by' => 58,
            ),
            7 => 
            array (
                'id' => 240584,
                'user_account_id' => 148,
                'carrier_id' => 66,
                'service_id' => 223,
                'name' => 'DEMO_TARIFF_DPDUK',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:22:43',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:22:43',
                'updated_by' => 58,
            ),
            8 => 
            array (
                'id' => 240585,
                'user_account_id' => 148,
                'carrier_id' => 199,
                'service_id' => 275,
                'name' => 'DEMO_TARIFF_VIVA',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2020-01-01',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:23:35',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:23:35',
                'updated_by' => 58,
            ),
            9 => 
            array (
                'id' => 240586,
                'user_account_id' => 148,
                'carrier_id' => 198,
                'service_id' => 274,
                'name' => 'DEMO_TARIFF_WNDIRECT',
                'status' => 0,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:24:08',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:24:08',
                'updated_by' => 58,
            ),
            10 => 
            array (
                'id' => 240587,
                'user_account_id' => 148,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'DEMO_TARIFF_BNTITALY',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:18',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:18',
                'updated_by' => 58,
            ),
            11 => 
            array (
                'id' => 240588,
                'user_account_id' => 148,
                'carrier_id' => 186,
                'service_id' => 244,
                'name' => 'DEMO_TARIFF_SWEDENPOST',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:52',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:52',
                'updated_by' => 58,
            ),
            12 => 
            array (
                'id' => 240589,
                'user_account_id' => 2336,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'KY_Supplier_Yodel_mini_24',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 21:35:53',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 16:35:53',
                'updated_by' => 2295,
            ),
            13 => 
            array (
                'id' => 240590,
                'user_account_id' => 2336,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'KY_BRT_Customer',
                'status' => 1,
                'currency_id' => 1,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 20:59:06',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 15:59:06',
                'updated_by' => 2295,
            ),
            14 => 
            array (
                'id' => 240577,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-06 17:48:53',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 12:48:53',
                'updated_by' => 2282,
            ),
            15 => 
            array (
                'id' => 240578,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 21,
                'date_added' => '2019-09-06 23:01:34',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 18:01:34',
                'updated_by' => 2282,
            ),
            16 => 
            array (
                'id' => 240579,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 3,
                'name' => 'DEMO_TARIFF_YODEL1HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:06',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:06',
                'updated_by' => 58,
            ),
            17 => 
            array (
                'id' => 240580,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 4,
                'name' => 'DEMO_TARIFF_YODEL3HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:51',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:51',
                'updated_by' => 58,
            ),
            18 => 
            array (
                'id' => 240581,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'DEMO_TARIFF_YODEL1CN',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:19:23',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:19:23',
                'updated_by' => 58,
            ),
            19 => 
            array (
                'id' => 240582,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 14,
                'name' => 'DEMO_TARIFF_ROYALMAIL1L',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:20:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:20:05',
                'updated_by' => 58,
            ),
            20 => 
            array (
                'id' => 240583,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 12,
                'name' => 'DEMO_TARIFF_ROYALMAILTP2',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:21:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:21:05',
                'updated_by' => 58,
            ),
            21 => 
            array (
                'id' => 240584,
                'user_account_id' => 148,
                'carrier_id' => 66,
                'service_id' => 223,
                'name' => 'DEMO_TARIFF_DPDUK',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:22:43',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:22:43',
                'updated_by' => 58,
            ),
            22 => 
            array (
                'id' => 240585,
                'user_account_id' => 148,
                'carrier_id' => 199,
                'service_id' => 275,
                'name' => 'DEMO_TARIFF_VIVA',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2020-01-01',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:23:35',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:23:35',
                'updated_by' => 58,
            ),
            23 => 
            array (
                'id' => 240586,
                'user_account_id' => 148,
                'carrier_id' => 198,
                'service_id' => 274,
                'name' => 'DEMO_TARIFF_WNDIRECT',
                'status' => 0,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:24:08',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:24:08',
                'updated_by' => 58,
            ),
            24 => 
            array (
                'id' => 240587,
                'user_account_id' => 148,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'DEMO_TARIFF_BNTITALY',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:18',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:18',
                'updated_by' => 58,
            ),
            25 => 
            array (
                'id' => 240588,
                'user_account_id' => 148,
                'carrier_id' => 186,
                'service_id' => 244,
                'name' => 'DEMO_TARIFF_SWEDENPOST',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:52',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:52',
                'updated_by' => 58,
            ),
            26 => 
            array (
                'id' => 240589,
                'user_account_id' => 2336,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'KY_Supplier_Yodel_mini_24',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 21:35:53',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 16:35:53',
                'updated_by' => 2295,
            ),
            27 => 
            array (
                'id' => 240590,
                'user_account_id' => 2336,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'KY_BRT_Customer',
                'status' => 1,
                'currency_id' => 1,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 20:59:06',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 15:59:06',
                'updated_by' => 2295,
            ),
            28 => 
            array (
                'id' => 240577,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-06 17:48:53',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 12:48:53',
                'updated_by' => 2282,
            ),
            29 => 
            array (
                'id' => 240578,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 21,
                'date_added' => '2019-09-06 23:01:34',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 18:01:34',
                'updated_by' => 2282,
            ),
            30 => 
            array (
                'id' => 240579,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 3,
                'name' => 'DEMO_TARIFF_YODEL1HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:06',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:06',
                'updated_by' => 58,
            ),
            31 => 
            array (
                'id' => 240580,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 4,
                'name' => 'DEMO_TARIFF_YODEL3HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:51',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:51',
                'updated_by' => 58,
            ),
            32 => 
            array (
                'id' => 240581,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'DEMO_TARIFF_YODEL1CN',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:19:23',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:19:23',
                'updated_by' => 58,
            ),
            33 => 
            array (
                'id' => 240582,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 14,
                'name' => 'DEMO_TARIFF_ROYALMAIL1L',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:20:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:20:05',
                'updated_by' => 58,
            ),
            34 => 
            array (
                'id' => 240583,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 12,
                'name' => 'DEMO_TARIFF_ROYALMAILTP2',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:21:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:21:05',
                'updated_by' => 58,
            ),
            35 => 
            array (
                'id' => 240584,
                'user_account_id' => 148,
                'carrier_id' => 66,
                'service_id' => 223,
                'name' => 'DEMO_TARIFF_DPDUK',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:22:43',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:22:43',
                'updated_by' => 58,
            ),
            36 => 
            array (
                'id' => 240585,
                'user_account_id' => 148,
                'carrier_id' => 199,
                'service_id' => 275,
                'name' => 'DEMO_TARIFF_VIVA',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2020-01-01',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:23:35',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:23:35',
                'updated_by' => 58,
            ),
            37 => 
            array (
                'id' => 240586,
                'user_account_id' => 148,
                'carrier_id' => 198,
                'service_id' => 274,
                'name' => 'DEMO_TARIFF_WNDIRECT',
                'status' => 0,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:24:08',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:24:08',
                'updated_by' => 58,
            ),
            38 => 
            array (
                'id' => 240587,
                'user_account_id' => 148,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'DEMO_TARIFF_BNTITALY',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:18',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:18',
                'updated_by' => 58,
            ),
            39 => 
            array (
                'id' => 240588,
                'user_account_id' => 148,
                'carrier_id' => 186,
                'service_id' => 244,
                'name' => 'DEMO_TARIFF_SWEDENPOST',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:52',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:52',
                'updated_by' => 58,
            ),
            40 => 
            array (
                'id' => 240589,
                'user_account_id' => 2336,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'KY_Supplier_Yodel_mini_24',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 21:35:53',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 16:35:53',
                'updated_by' => 2295,
            ),
            41 => 
            array (
                'id' => 240590,
                'user_account_id' => 2336,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'KY_BRT_Customer',
                'status' => 1,
                'currency_id' => 1,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 20:59:06',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 15:59:06',
                'updated_by' => 2295,
            ),
            42 => 
            array (
                'id' => 240577,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-06 17:48:53',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 12:48:53',
                'updated_by' => 2282,
            ),
            43 => 
            array (
                'id' => 240578,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 21,
                'date_added' => '2019-09-06 23:01:34',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 18:01:34',
                'updated_by' => 2282,
            ),
            44 => 
            array (
                'id' => 240579,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 3,
                'name' => 'DEMO_TARIFF_YODEL1HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:06',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:06',
                'updated_by' => 58,
            ),
            45 => 
            array (
                'id' => 240580,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 4,
                'name' => 'DEMO_TARIFF_YODEL3HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:51',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:51',
                'updated_by' => 58,
            ),
            46 => 
            array (
                'id' => 240581,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'DEMO_TARIFF_YODEL1CN',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:19:23',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:19:23',
                'updated_by' => 58,
            ),
            47 => 
            array (
                'id' => 240582,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 14,
                'name' => 'DEMO_TARIFF_ROYALMAIL1L',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:20:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:20:05',
                'updated_by' => 58,
            ),
            48 => 
            array (
                'id' => 240583,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 12,
                'name' => 'DEMO_TARIFF_ROYALMAILTP2',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:21:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:21:05',
                'updated_by' => 58,
            ),
            49 => 
            array (
                'id' => 240584,
                'user_account_id' => 148,
                'carrier_id' => 66,
                'service_id' => 223,
                'name' => 'DEMO_TARIFF_DPDUK',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:22:43',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:22:43',
                'updated_by' => 58,
            ),
            50 => 
            array (
                'id' => 240585,
                'user_account_id' => 148,
                'carrier_id' => 199,
                'service_id' => 275,
                'name' => 'DEMO_TARIFF_VIVA',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2020-01-01',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:23:35',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:23:35',
                'updated_by' => 58,
            ),
            51 => 
            array (
                'id' => 240586,
                'user_account_id' => 148,
                'carrier_id' => 198,
                'service_id' => 274,
                'name' => 'DEMO_TARIFF_WNDIRECT',
                'status' => 0,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:24:08',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:24:08',
                'updated_by' => 58,
            ),
            52 => 
            array (
                'id' => 240587,
                'user_account_id' => 148,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'DEMO_TARIFF_BNTITALY',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:18',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:18',
                'updated_by' => 58,
            ),
            53 => 
            array (
                'id' => 240588,
                'user_account_id' => 148,
                'carrier_id' => 186,
                'service_id' => 244,
                'name' => 'DEMO_TARIFF_SWEDENPOST',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:52',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:52',
                'updated_by' => 58,
            ),
            54 => 
            array (
                'id' => 240589,
                'user_account_id' => 2336,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'KY_Supplier_Yodel_mini_24',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 21:35:53',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 16:35:53',
                'updated_by' => 2295,
            ),
            55 => 
            array (
                'id' => 240590,
                'user_account_id' => 2336,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'KY_BRT_Customer',
                'status' => 1,
                'currency_id' => 1,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 20:59:06',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 15:59:06',
                'updated_by' => 2295,
            ),
            56 => 
            array (
                'id' => 240577,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-06 17:48:53',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 12:48:53',
                'updated_by' => 2282,
            ),
            57 => 
            array (
                'id' => 240578,
                'user_account_id' => 2331,
                'carrier_id' => 16,
                'service_id' => 38,
                'name' => 'EURACC Tariff 1 Sup',
                'status' => 1,
                'currency_id' => 3,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-06',
                'end_date' => '2020-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 21,
                'date_added' => '2019-09-06 23:01:34',
                'added_by' => 2282,
                'date_updated' => '2019-09-06 18:01:34',
                'updated_by' => 2282,
            ),
            58 => 
            array (
                'id' => 240579,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 3,
                'name' => 'DEMO_TARIFF_YODEL1HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:06',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:06',
                'updated_by' => 58,
            ),
            59 => 
            array (
                'id' => 240580,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 4,
                'name' => 'DEMO_TARIFF_YODEL3HS',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:18:51',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:18:51',
                'updated_by' => 58,
            ),
            60 => 
            array (
                'id' => 240581,
                'user_account_id' => 148,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'DEMO_TARIFF_YODEL1CN',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:19:23',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:19:23',
                'updated_by' => 58,
            ),
            61 => 
            array (
                'id' => 240582,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 14,
                'name' => 'DEMO_TARIFF_ROYALMAIL1L',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:20:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:20:05',
                'updated_by' => 58,
            ),
            62 => 
            array (
                'id' => 240583,
                'user_account_id' => 148,
                'carrier_id' => 15,
                'service_id' => 12,
                'name' => 'DEMO_TARIFF_ROYALMAILTP2',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:21:05',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:21:05',
                'updated_by' => 58,
            ),
            63 => 
            array (
                'id' => 240584,
                'user_account_id' => 148,
                'carrier_id' => 66,
                'service_id' => 223,
                'name' => 'DEMO_TARIFF_DPDUK',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:22:43',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:22:43',
                'updated_by' => 58,
            ),
            64 => 
            array (
                'id' => 240585,
                'user_account_id' => 148,
                'carrier_id' => 199,
                'service_id' => 275,
                'name' => 'DEMO_TARIFF_VIVA',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2020-01-01',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:23:35',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:23:35',
                'updated_by' => 58,
            ),
            65 => 
            array (
                'id' => 240586,
                'user_account_id' => 148,
                'carrier_id' => 198,
                'service_id' => 274,
                'name' => 'DEMO_TARIFF_WNDIRECT',
                'status' => 0,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:24:08',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:24:08',
                'updated_by' => 58,
            ),
            66 => 
            array (
                'id' => 240587,
                'user_account_id' => 148,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'DEMO_TARIFF_BNTITALY',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:18',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:18',
                'updated_by' => 58,
            ),
            67 => 
            array (
                'id' => 240588,
                'user_account_id' => 148,
                'carrier_id' => 186,
                'service_id' => 244,
                'name' => 'DEMO_TARIFF_SWEDENPOST',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-09',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-09 17:25:52',
                'added_by' => 58,
                'date_updated' => '2019-09-09 12:25:52',
                'updated_by' => 58,
            ),
            68 => 
            array (
                'id' => 240589,
                'user_account_id' => 2336,
                'carrier_id' => 16,
                'service_id' => 262,
                'name' => 'KY_Supplier_Yodel_mini_24',
                'status' => 1,
                'currency_id' => 2,
                'tariff_type' => 'supplier',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 21:35:53',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 16:35:53',
                'updated_by' => 2295,
            ),
            69 => 
            array (
                'id' => 240590,
                'user_account_id' => 2336,
                'carrier_id' => 187,
                'service_id' => 246,
                'name' => 'KY_BRT_Customer',
                'status' => 1,
                'currency_id' => 1,
                'tariff_type' => 'customer',
                'start_date' => '2019-09-01',
                'end_date' => '2019-12-31',
                'description' => '',
                'tariffs_pricing_rule_id' => 0,
                'date_added' => '2019-09-10 20:59:06',
                'added_by' => 2295,
                'date_updated' => '2019-09-10 15:59:06',
                'updated_by' => 2295,
            ),
        ));
        
        
    }
}