<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TourlineRoutinesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tourline_routines')->delete();
        
        \DB::table('tourline_routines')->insert(array (
            0 => 
            array (
                'id' => 130497,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3511 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            1 => 
            array (
                'id' => 130498,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3514 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            2 => 
            array (
                'id' => 130499,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3515 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            3 => 
            array (
                'id' => 130500,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3516 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            4 => 
            array (
                'id' => 130501,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3519 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            5 => 
            array (
                'id' => 130502,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DAS DONAS                                                    ',
                'kilometer' => '0000.0',
            ),
            6 => 
            array (
                'id' => 130503,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DOS PIAES                                                    ',
                'kilometer' => '0000.0',
            ),
            7 => 
            array (
                'id' => 130504,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4815 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            8 => 
            array (
                'id' => 130505,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4816 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            9 => 
            array (
                'id' => 130506,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4819 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            10 => 
            array (
                'id' => 130507,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4610 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
            'town_name' => 'VIZELA (SAO JORGE)                                                    ',
                'kilometer' => '0000.0',
            ),
            11 => 
            array (
                'id' => 130508,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3670 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            12 => 
            array (
                'id' => 130509,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3671 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            13 => 
            array (
                'id' => 130510,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3674 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            14 => 
            array (
                'id' => 130511,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE BORNES                                                       ',
                'kilometer' => '0000.0',
            ),
            15 => 
            array (
                'id' => 130512,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE JALES                                                        ',
                'kilometer' => '0000.0',
            ),
            16 => 
            array (
                'id' => 130513,
                'agency_name' => 'COIMBRA P03                                         ',
                'postal_code' => '3150 ',
                'agency_code' => '004030',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'ZAMBUJAL                                                              ',
                'kilometer' => '0000.0',
            ),
            17 => 
            array (
                'id' => 130514,
                'agency_name' => 'CASTELO BRANCO P01                                  ',
                'postal_code' => '6060 ',
                'agency_code' => '001060',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 01  ',
                'km' => 'S',
                'town_name' => 'ZEBREIRA                                                              ',
                'kilometer' => '0000.0',
            ),
            18 => 
            array (
                'id' => 130515,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5140 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZEDES                                                                 ',
                'kilometer' => '0000.0',
            ),
            19 => 
            array (
                'id' => 130516,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5300 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZOIO                                                                  ',
                'kilometer' => '0000.0',
            ),
            20 => 
            array (
                'id' => 130497,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3511 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            21 => 
            array (
                'id' => 130498,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3514 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            22 => 
            array (
                'id' => 130499,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3515 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            23 => 
            array (
                'id' => 130500,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3516 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            24 => 
            array (
                'id' => 130501,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3519 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            25 => 
            array (
                'id' => 130502,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DAS DONAS                                                    ',
                'kilometer' => '0000.0',
            ),
            26 => 
            array (
                'id' => 130503,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DOS PIAES                                                    ',
                'kilometer' => '0000.0',
            ),
            27 => 
            array (
                'id' => 130504,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4815 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            28 => 
            array (
                'id' => 130505,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4816 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            29 => 
            array (
                'id' => 130506,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4819 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            30 => 
            array (
                'id' => 130507,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4610 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
            'town_name' => 'VIZELA (SAO JORGE)                                                    ',
                'kilometer' => '0000.0',
            ),
            31 => 
            array (
                'id' => 130508,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3670 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            32 => 
            array (
                'id' => 130509,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3671 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            33 => 
            array (
                'id' => 130510,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3674 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            34 => 
            array (
                'id' => 130511,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE BORNES                                                       ',
                'kilometer' => '0000.0',
            ),
            35 => 
            array (
                'id' => 130512,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE JALES                                                        ',
                'kilometer' => '0000.0',
            ),
            36 => 
            array (
                'id' => 130513,
                'agency_name' => 'COIMBRA P03                                         ',
                'postal_code' => '3150 ',
                'agency_code' => '004030',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'ZAMBUJAL                                                              ',
                'kilometer' => '0000.0',
            ),
            37 => 
            array (
                'id' => 130514,
                'agency_name' => 'CASTELO BRANCO P01                                  ',
                'postal_code' => '6060 ',
                'agency_code' => '001060',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 01  ',
                'km' => 'S',
                'town_name' => 'ZEBREIRA                                                              ',
                'kilometer' => '0000.0',
            ),
            38 => 
            array (
                'id' => 130515,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5140 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZEDES                                                                 ',
                'kilometer' => '0000.0',
            ),
            39 => 
            array (
                'id' => 130516,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5300 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZOIO                                                                  ',
                'kilometer' => '0000.0',
            ),
            40 => 
            array (
                'id' => 130497,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3511 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            41 => 
            array (
                'id' => 130498,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3514 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            42 => 
            array (
                'id' => 130499,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3515 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            43 => 
            array (
                'id' => 130500,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3516 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            44 => 
            array (
                'id' => 130501,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3519 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            45 => 
            array (
                'id' => 130502,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DAS DONAS                                                    ',
                'kilometer' => '0000.0',
            ),
            46 => 
            array (
                'id' => 130503,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DOS PIAES                                                    ',
                'kilometer' => '0000.0',
            ),
            47 => 
            array (
                'id' => 130504,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4815 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            48 => 
            array (
                'id' => 130505,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4816 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            49 => 
            array (
                'id' => 130506,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4819 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            50 => 
            array (
                'id' => 130507,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4610 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
            'town_name' => 'VIZELA (SAO JORGE)                                                    ',
                'kilometer' => '0000.0',
            ),
            51 => 
            array (
                'id' => 130508,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3670 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            52 => 
            array (
                'id' => 130509,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3671 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            53 => 
            array (
                'id' => 130510,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3674 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            54 => 
            array (
                'id' => 130511,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE BORNES                                                       ',
                'kilometer' => '0000.0',
            ),
            55 => 
            array (
                'id' => 130512,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE JALES                                                        ',
                'kilometer' => '0000.0',
            ),
            56 => 
            array (
                'id' => 130513,
                'agency_name' => 'COIMBRA P03                                         ',
                'postal_code' => '3150 ',
                'agency_code' => '004030',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'ZAMBUJAL                                                              ',
                'kilometer' => '0000.0',
            ),
            57 => 
            array (
                'id' => 130514,
                'agency_name' => 'CASTELO BRANCO P01                                  ',
                'postal_code' => '6060 ',
                'agency_code' => '001060',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 01  ',
                'km' => 'S',
                'town_name' => 'ZEBREIRA                                                              ',
                'kilometer' => '0000.0',
            ),
            58 => 
            array (
                'id' => 130515,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5140 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZEDES                                                                 ',
                'kilometer' => '0000.0',
            ),
            59 => 
            array (
                'id' => 130516,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5300 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZOIO                                                                  ',
                'kilometer' => '0000.0',
            ),
            60 => 
            array (
                'id' => 130497,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3511 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            61 => 
            array (
                'id' => 130498,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3514 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            62 => 
            array (
                'id' => 130499,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3515 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            63 => 
            array (
                'id' => 130500,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3516 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            64 => 
            array (
                'id' => 130501,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3519 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            65 => 
            array (
                'id' => 130502,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DAS DONAS                                                    ',
                'kilometer' => '0000.0',
            ),
            66 => 
            array (
                'id' => 130503,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DOS PIAES                                                    ',
                'kilometer' => '0000.0',
            ),
            67 => 
            array (
                'id' => 130504,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4815 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            68 => 
            array (
                'id' => 130505,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4816 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            69 => 
            array (
                'id' => 130506,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4819 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            70 => 
            array (
                'id' => 130507,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4610 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
            'town_name' => 'VIZELA (SAO JORGE)                                                    ',
                'kilometer' => '0000.0',
            ),
            71 => 
            array (
                'id' => 130508,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3670 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            72 => 
            array (
                'id' => 130509,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3671 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            73 => 
            array (
                'id' => 130510,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3674 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            74 => 
            array (
                'id' => 130511,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE BORNES                                                       ',
                'kilometer' => '0000.0',
            ),
            75 => 
            array (
                'id' => 130512,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE JALES                                                        ',
                'kilometer' => '0000.0',
            ),
            76 => 
            array (
                'id' => 130513,
                'agency_name' => 'COIMBRA P03                                         ',
                'postal_code' => '3150 ',
                'agency_code' => '004030',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'ZAMBUJAL                                                              ',
                'kilometer' => '0000.0',
            ),
            77 => 
            array (
                'id' => 130514,
                'agency_name' => 'CASTELO BRANCO P01                                  ',
                'postal_code' => '6060 ',
                'agency_code' => '001060',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 01  ',
                'km' => 'S',
                'town_name' => 'ZEBREIRA                                                              ',
                'kilometer' => '0000.0',
            ),
            78 => 
            array (
                'id' => 130515,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5140 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZEDES                                                                 ',
                'kilometer' => '0000.0',
            ),
            79 => 
            array (
                'id' => 130516,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5300 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZOIO                                                                  ',
                'kilometer' => '0000.0',
            ),
            80 => 
            array (
                'id' => 130497,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3511 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            81 => 
            array (
                'id' => 130498,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3514 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            82 => 
            array (
                'id' => 130499,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3515 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            83 => 
            array (
                'id' => 130500,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3516 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            84 => 
            array (
                'id' => 130501,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3519 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VISEU                                                                 ',
                'kilometer' => '0000.0',
            ),
            85 => 
            array (
                'id' => 130502,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DAS DONAS                                                    ',
                'kilometer' => '0000.0',
            ),
            86 => 
            array (
                'id' => 130503,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4990 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VITORINO DOS PIAES                                                    ',
                'kilometer' => '0000.0',
            ),
            87 => 
            array (
                'id' => 130504,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4815 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            88 => 
            array (
                'id' => 130505,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4816 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            89 => 
            array (
                'id' => 130506,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4819 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VIZELA                                                                ',
                'kilometer' => '0000.0',
            ),
            90 => 
            array (
                'id' => 130507,
                'agency_name' => 'BRAGA P02                                           ',
                'postal_code' => '4610 ',
                'agency_code' => '004047',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
            'town_name' => 'VIZELA (SAO JORGE)                                                    ',
                'kilometer' => '0000.0',
            ),
            91 => 
            array (
                'id' => 130508,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3670 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            92 => 
            array (
                'id' => 130509,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3671 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            93 => 
            array (
                'id' => 130510,
                'agency_name' => 'VISEU P03                                           ',
                'postal_code' => '3674 ',
                'agency_code' => '004034',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'VOUZELA                                                               ',
                'kilometer' => '0000.0',
            ),
            94 => 
            array (
                'id' => 130511,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE BORNES                                                       ',
                'kilometer' => '0000.0',
            ),
            95 => 
            array (
                'id' => 130512,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5450 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'VREIA DE JALES                                                        ',
                'kilometer' => '0000.0',
            ),
            96 => 
            array (
                'id' => 130513,
                'agency_name' => 'COIMBRA P03                                         ',
                'postal_code' => '3150 ',
                'agency_code' => '004030',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 03  ',
                'km' => 'S',
                'town_name' => 'ZAMBUJAL                                                              ',
                'kilometer' => '0000.0',
            ),
            97 => 
            array (
                'id' => 130514,
                'agency_name' => 'CASTELO BRANCO P01                                  ',
                'postal_code' => '6060 ',
                'agency_code' => '001060',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 01  ',
                'km' => 'S',
                'town_name' => 'ZEBREIRA                                                              ',
                'kilometer' => '0000.0',
            ),
            98 => 
            array (
                'id' => 130515,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5140 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZEDES                                                                 ',
                'kilometer' => '0000.0',
            ),
            99 => 
            array (
                'id' => 130516,
                'agency_name' => 'VILA REAL P02                                       ',
                'postal_code' => '5300 ',
                'agency_code' => '004050',
                'zone' => 'PTI',
                'province' => '94',
                'route_code' => ' P 02  ',
                'km' => 'S',
                'town_name' => 'ZOIO                                                                  ',
                'kilometer' => '0000.0',
            ),
        ));
        
        
    }
}