<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserServicesRoutingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_services_routings')->delete();
        
        \DB::table('user_services_routings')->insert(array (
            0 => 
            array (
                'id' => 148474,
                'user_account_id' => 148,
                'country_id' => 97,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            1 => 
            array (
                'id' => 148475,
                'user_account_id' => 148,
                'country_id' => 98,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            2 => 
            array (
                'id' => 148476,
                'user_account_id' => 148,
                'country_id' => 99,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            3 => 
            array (
                'id' => 148477,
                'user_account_id' => 148,
                'country_id' => 100,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            4 => 
            array (
                'id' => 148478,
                'user_account_id' => 148,
                'country_id' => 101,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            5 => 
            array (
                'id' => 148479,
                'user_account_id' => 148,
                'country_id' => 102,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            6 => 
            array (
                'id' => 148480,
                'user_account_id' => 148,
                'country_id' => 103,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            7 => 
            array (
                'id' => 148481,
                'user_account_id' => 148,
                'country_id' => 245,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            8 => 
            array (
                'id' => 148482,
                'user_account_id' => 148,
                'country_id' => 104,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            9 => 
            array (
                'id' => 148483,
                'user_account_id' => 148,
                'country_id' => 105,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            10 => 
            array (
                'id' => 148484,
                'user_account_id' => 148,
                'country_id' => 106,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            11 => 
            array (
                'id' => 148485,
                'user_account_id' => 148,
                'country_id' => 107,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            12 => 
            array (
                'id' => 148486,
                'user_account_id' => 148,
                'country_id' => 265,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            13 => 
            array (
                'id' => 148487,
                'user_account_id' => 148,
                'country_id' => 108,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            14 => 
            array (
                'id' => 148488,
                'user_account_id' => 148,
                'country_id' => 109,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            15 => 
            array (
                'id' => 148489,
                'user_account_id' => 148,
                'country_id' => 110,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            16 => 
            array (
                'id' => 148490,
                'user_account_id' => 148,
                'country_id' => 111,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            17 => 
            array (
                'id' => 148491,
                'user_account_id' => 148,
                'country_id' => 260,
                'from_weight' => '0.00',
                'to_weight' => '300.00',
                'status' => 1,
                'service_id' => 333,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 1,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
            18 => 
            array (
                'id' => 148492,
                'user_account_id' => 999,
                'country_id' => 0,
                'from_weight' => '0.00',
                'to_weight' => '9999.00',
                'status' => 1,
                'service_id' => 226,
                'is_remotearea' => 0,
                'is_over_label' => 0,
                'added_by' => 58,
                'is_agreed' => 0,
                'label_charges' => '0.00',
                'is_dead_weight' => 0,
                'is_over_size' => 0,
            ),
        ));
        
        
    }
}