<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserAccountServiceChargesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_account_service_charges')->delete();
        
        \DB::table('user_account_service_charges')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 2,
                'charge' => '15.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:23:49',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 3,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:24:59',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_account_id' => 2295,
                'service_id' => 246,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2181,
                'added_date' => '2018-12-17 15:59:14',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 15:59:14',
            ),
            3 => 
            array (
                'id' => 4,
                'user_account_id' => 2290,
                'service_id' => 261,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2175,
                'added_date' => '2018-12-17 16:19:41',
                'updated_by' => 2175,
                'updated_date' => '2018-12-17 16:19:41',
            ),
            4 => 
            array (
                'id' => 6,
                'user_account_id' => 2295,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '4.00',
                'charge_type' => 'percentage',
                'added_by' => 2181,
                'added_date' => '2018-12-17 16:40:20',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 16:40:20',
            ),
            5 => 
            array (
                'id' => 7,
                'user_account_id' => 2296,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '3.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-17 16:41:30',
                'updated_by' => 2185,
                'updated_date' => '2018-12-17 16:41:30',
            ),
            6 => 
            array (
                'id' => 8,
                'user_account_id' => 2296,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '7.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-18 10:09:34',
                'updated_by' => 2185,
                'updated_date' => '2018-12-18 10:09:34',
            ),
            7 => 
            array (
                'id' => 9,
                'user_account_id' => 2294,
                'service_id' => 3,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:22:42',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:22:42',
            ),
            8 => 
            array (
                'id' => 11,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:32:51',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:32:51',
            ),
            9 => 
            array (
                'id' => 12,
                'user_account_id' => 2294,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:23:50',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:23:50',
            ),
            10 => 
            array (
                'id' => 13,
                'user_account_id' => 2285,
                'service_id' => 263,
                'consignment_charges_types_id' => 26,
                'charge' => '1.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-18 14:00:48',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 14:00:48',
            ),
            11 => 
            array (
                'id' => 14,
                'user_account_id' => 2285,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:09:58',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:09:58',
            ),
            12 => 
            array (
                'id' => 15,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:13',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:13',
            ),
            13 => 
            array (
                'id' => 16,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:33',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:33',
            ),
            14 => 
            array (
                'id' => 17,
                'user_account_id' => 2285,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:15:23',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:15:23',
            ),
            15 => 
            array (
                'id' => 18,
                'user_account_id' => 2300,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:11',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:11',
            ),
            16 => 
            array (
                'id' => 19,
                'user_account_id' => 2300,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:34',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:34',
            ),
            17 => 
            array (
                'id' => 20,
                'user_account_id' => 2294,
                'service_id' => 2,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-21 11:31:53',
                'updated_by' => 58,
                'updated_date' => '2018-12-21 11:31:53',
            ),
            18 => 
            array (
                'id' => 21,
                'user_account_id' => 2294,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-31 16:36:44',
                'updated_by' => 58,
                'updated_date' => '2018-12-31 16:36:44',
            ),
            19 => 
            array (
                'id' => 24,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 2,
                'charge' => '25.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:33:31',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:33:31',
            ),
            20 => 
            array (
                'id' => 25,
                'user_account_id' => 2297,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '10.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-01 11:30:19',
                'updated_by' => 58,
                'updated_date' => '2019-09-01 11:30:19',
            ),
            21 => 
            array (
                'id' => 26,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '6.50',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 13:01:56',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 13:01:56',
            ),
            22 => 
            array (
                'id' => 27,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 9,
                'charge' => '7.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 14:36:11',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 14:36:11',
            ),
            23 => 
            array (
                'id' => 28,
                'user_account_id' => 2337,
                'service_id' => 4,
                'consignment_charges_types_id' => 2,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 2295,
                'added_date' => '2019-09-10 13:10:17',
                'updated_by' => 2295,
                'updated_date' => '2019-09-10 13:10:17',
            ),
            24 => 
            array (
                'id' => 29,
                'user_account_id' => 2228,
                'service_id' => 246,
                'consignment_charges_types_id' => 2,
                'charge' => '0.23',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-11-11 16:35:29',
                'updated_by' => 58,
                'updated_date' => '2019-11-11 16:35:29',
            ),
            25 => 
            array (
                'id' => 1,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 2,
                'charge' => '15.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:23:49',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            26 => 
            array (
                'id' => 2,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 3,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:24:59',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            27 => 
            array (
                'id' => 3,
                'user_account_id' => 2295,
                'service_id' => 246,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2181,
                'added_date' => '2018-12-17 15:59:14',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 15:59:14',
            ),
            28 => 
            array (
                'id' => 4,
                'user_account_id' => 2290,
                'service_id' => 261,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2175,
                'added_date' => '2018-12-17 16:19:41',
                'updated_by' => 2175,
                'updated_date' => '2018-12-17 16:19:41',
            ),
            29 => 
            array (
                'id' => 6,
                'user_account_id' => 2295,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '4.00',
                'charge_type' => 'percentage',
                'added_by' => 2181,
                'added_date' => '2018-12-17 16:40:20',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 16:40:20',
            ),
            30 => 
            array (
                'id' => 7,
                'user_account_id' => 2296,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '3.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-17 16:41:30',
                'updated_by' => 2185,
                'updated_date' => '2018-12-17 16:41:30',
            ),
            31 => 
            array (
                'id' => 8,
                'user_account_id' => 2296,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '7.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-18 10:09:34',
                'updated_by' => 2185,
                'updated_date' => '2018-12-18 10:09:34',
            ),
            32 => 
            array (
                'id' => 9,
                'user_account_id' => 2294,
                'service_id' => 3,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:22:42',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:22:42',
            ),
            33 => 
            array (
                'id' => 11,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:32:51',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:32:51',
            ),
            34 => 
            array (
                'id' => 12,
                'user_account_id' => 2294,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:23:50',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:23:50',
            ),
            35 => 
            array (
                'id' => 13,
                'user_account_id' => 2285,
                'service_id' => 263,
                'consignment_charges_types_id' => 26,
                'charge' => '1.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-18 14:00:48',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 14:00:48',
            ),
            36 => 
            array (
                'id' => 14,
                'user_account_id' => 2285,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:09:58',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:09:58',
            ),
            37 => 
            array (
                'id' => 15,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:13',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:13',
            ),
            38 => 
            array (
                'id' => 16,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:33',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:33',
            ),
            39 => 
            array (
                'id' => 17,
                'user_account_id' => 2285,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:15:23',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:15:23',
            ),
            40 => 
            array (
                'id' => 18,
                'user_account_id' => 2300,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:11',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:11',
            ),
            41 => 
            array (
                'id' => 19,
                'user_account_id' => 2300,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:34',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:34',
            ),
            42 => 
            array (
                'id' => 20,
                'user_account_id' => 2294,
                'service_id' => 2,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-21 11:31:53',
                'updated_by' => 58,
                'updated_date' => '2018-12-21 11:31:53',
            ),
            43 => 
            array (
                'id' => 21,
                'user_account_id' => 2294,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-31 16:36:44',
                'updated_by' => 58,
                'updated_date' => '2018-12-31 16:36:44',
            ),
            44 => 
            array (
                'id' => 24,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 2,
                'charge' => '25.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:33:31',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:33:31',
            ),
            45 => 
            array (
                'id' => 25,
                'user_account_id' => 2297,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '10.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-01 11:30:19',
                'updated_by' => 58,
                'updated_date' => '2019-09-01 11:30:19',
            ),
            46 => 
            array (
                'id' => 26,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '6.50',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 13:01:56',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 13:01:56',
            ),
            47 => 
            array (
                'id' => 27,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 9,
                'charge' => '7.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 14:36:11',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 14:36:11',
            ),
            48 => 
            array (
                'id' => 28,
                'user_account_id' => 2337,
                'service_id' => 4,
                'consignment_charges_types_id' => 2,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 2295,
                'added_date' => '2019-09-10 13:10:17',
                'updated_by' => 2295,
                'updated_date' => '2019-09-10 13:10:17',
            ),
            49 => 
            array (
                'id' => 29,
                'user_account_id' => 2228,
                'service_id' => 246,
                'consignment_charges_types_id' => 2,
                'charge' => '0.23',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-11-11 16:35:29',
                'updated_by' => 58,
                'updated_date' => '2019-11-11 16:35:29',
            ),
            50 => 
            array (
                'id' => 1,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 2,
                'charge' => '15.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:23:49',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            51 => 
            array (
                'id' => 2,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 3,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:24:59',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            52 => 
            array (
                'id' => 3,
                'user_account_id' => 2295,
                'service_id' => 246,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2181,
                'added_date' => '2018-12-17 15:59:14',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 15:59:14',
            ),
            53 => 
            array (
                'id' => 4,
                'user_account_id' => 2290,
                'service_id' => 261,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2175,
                'added_date' => '2018-12-17 16:19:41',
                'updated_by' => 2175,
                'updated_date' => '2018-12-17 16:19:41',
            ),
            54 => 
            array (
                'id' => 6,
                'user_account_id' => 2295,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '4.00',
                'charge_type' => 'percentage',
                'added_by' => 2181,
                'added_date' => '2018-12-17 16:40:20',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 16:40:20',
            ),
            55 => 
            array (
                'id' => 7,
                'user_account_id' => 2296,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '3.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-17 16:41:30',
                'updated_by' => 2185,
                'updated_date' => '2018-12-17 16:41:30',
            ),
            56 => 
            array (
                'id' => 8,
                'user_account_id' => 2296,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '7.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-18 10:09:34',
                'updated_by' => 2185,
                'updated_date' => '2018-12-18 10:09:34',
            ),
            57 => 
            array (
                'id' => 9,
                'user_account_id' => 2294,
                'service_id' => 3,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:22:42',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:22:42',
            ),
            58 => 
            array (
                'id' => 11,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:32:51',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:32:51',
            ),
            59 => 
            array (
                'id' => 12,
                'user_account_id' => 2294,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:23:50',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:23:50',
            ),
            60 => 
            array (
                'id' => 13,
                'user_account_id' => 2285,
                'service_id' => 263,
                'consignment_charges_types_id' => 26,
                'charge' => '1.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-18 14:00:48',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 14:00:48',
            ),
            61 => 
            array (
                'id' => 14,
                'user_account_id' => 2285,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:09:58',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:09:58',
            ),
            62 => 
            array (
                'id' => 15,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:13',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:13',
            ),
            63 => 
            array (
                'id' => 16,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:33',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:33',
            ),
            64 => 
            array (
                'id' => 17,
                'user_account_id' => 2285,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:15:23',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:15:23',
            ),
            65 => 
            array (
                'id' => 18,
                'user_account_id' => 2300,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:11',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:11',
            ),
            66 => 
            array (
                'id' => 19,
                'user_account_id' => 2300,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:34',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:34',
            ),
            67 => 
            array (
                'id' => 20,
                'user_account_id' => 2294,
                'service_id' => 2,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-21 11:31:53',
                'updated_by' => 58,
                'updated_date' => '2018-12-21 11:31:53',
            ),
            68 => 
            array (
                'id' => 21,
                'user_account_id' => 2294,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-31 16:36:44',
                'updated_by' => 58,
                'updated_date' => '2018-12-31 16:36:44',
            ),
            69 => 
            array (
                'id' => 24,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 2,
                'charge' => '25.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:33:31',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:33:31',
            ),
            70 => 
            array (
                'id' => 25,
                'user_account_id' => 2297,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '10.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-01 11:30:19',
                'updated_by' => 58,
                'updated_date' => '2019-09-01 11:30:19',
            ),
            71 => 
            array (
                'id' => 26,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '6.50',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 13:01:56',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 13:01:56',
            ),
            72 => 
            array (
                'id' => 27,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 9,
                'charge' => '7.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 14:36:11',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 14:36:11',
            ),
            73 => 
            array (
                'id' => 28,
                'user_account_id' => 2337,
                'service_id' => 4,
                'consignment_charges_types_id' => 2,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 2295,
                'added_date' => '2019-09-10 13:10:17',
                'updated_by' => 2295,
                'updated_date' => '2019-09-10 13:10:17',
            ),
            74 => 
            array (
                'id' => 29,
                'user_account_id' => 2228,
                'service_id' => 246,
                'consignment_charges_types_id' => 2,
                'charge' => '0.23',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-11-11 16:35:29',
                'updated_by' => 58,
                'updated_date' => '2019-11-11 16:35:29',
            ),
            75 => 
            array (
                'id' => 1,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 2,
                'charge' => '15.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:23:49',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            76 => 
            array (
                'id' => 2,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 3,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:24:59',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            77 => 
            array (
                'id' => 3,
                'user_account_id' => 2295,
                'service_id' => 246,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2181,
                'added_date' => '2018-12-17 15:59:14',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 15:59:14',
            ),
            78 => 
            array (
                'id' => 4,
                'user_account_id' => 2290,
                'service_id' => 261,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2175,
                'added_date' => '2018-12-17 16:19:41',
                'updated_by' => 2175,
                'updated_date' => '2018-12-17 16:19:41',
            ),
            79 => 
            array (
                'id' => 6,
                'user_account_id' => 2295,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '4.00',
                'charge_type' => 'percentage',
                'added_by' => 2181,
                'added_date' => '2018-12-17 16:40:20',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 16:40:20',
            ),
            80 => 
            array (
                'id' => 7,
                'user_account_id' => 2296,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '3.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-17 16:41:30',
                'updated_by' => 2185,
                'updated_date' => '2018-12-17 16:41:30',
            ),
            81 => 
            array (
                'id' => 8,
                'user_account_id' => 2296,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '7.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-18 10:09:34',
                'updated_by' => 2185,
                'updated_date' => '2018-12-18 10:09:34',
            ),
            82 => 
            array (
                'id' => 9,
                'user_account_id' => 2294,
                'service_id' => 3,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:22:42',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:22:42',
            ),
            83 => 
            array (
                'id' => 11,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:32:51',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:32:51',
            ),
            84 => 
            array (
                'id' => 12,
                'user_account_id' => 2294,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:23:50',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:23:50',
            ),
            85 => 
            array (
                'id' => 13,
                'user_account_id' => 2285,
                'service_id' => 263,
                'consignment_charges_types_id' => 26,
                'charge' => '1.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-18 14:00:48',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 14:00:48',
            ),
            86 => 
            array (
                'id' => 14,
                'user_account_id' => 2285,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:09:58',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:09:58',
            ),
            87 => 
            array (
                'id' => 15,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:13',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:13',
            ),
            88 => 
            array (
                'id' => 16,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:33',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:33',
            ),
            89 => 
            array (
                'id' => 17,
                'user_account_id' => 2285,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:15:23',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:15:23',
            ),
            90 => 
            array (
                'id' => 18,
                'user_account_id' => 2300,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:11',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:11',
            ),
            91 => 
            array (
                'id' => 19,
                'user_account_id' => 2300,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:34',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:34',
            ),
            92 => 
            array (
                'id' => 20,
                'user_account_id' => 2294,
                'service_id' => 2,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-21 11:31:53',
                'updated_by' => 58,
                'updated_date' => '2018-12-21 11:31:53',
            ),
            93 => 
            array (
                'id' => 21,
                'user_account_id' => 2294,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-31 16:36:44',
                'updated_by' => 58,
                'updated_date' => '2018-12-31 16:36:44',
            ),
            94 => 
            array (
                'id' => 24,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 2,
                'charge' => '25.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:33:31',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:33:31',
            ),
            95 => 
            array (
                'id' => 25,
                'user_account_id' => 2297,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '10.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-01 11:30:19',
                'updated_by' => 58,
                'updated_date' => '2019-09-01 11:30:19',
            ),
            96 => 
            array (
                'id' => 26,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '6.50',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 13:01:56',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 13:01:56',
            ),
            97 => 
            array (
                'id' => 27,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 9,
                'charge' => '7.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 14:36:11',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 14:36:11',
            ),
            98 => 
            array (
                'id' => 28,
                'user_account_id' => 2337,
                'service_id' => 4,
                'consignment_charges_types_id' => 2,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 2295,
                'added_date' => '2019-09-10 13:10:17',
                'updated_by' => 2295,
                'updated_date' => '2019-09-10 13:10:17',
            ),
            99 => 
            array (
                'id' => 29,
                'user_account_id' => 2228,
                'service_id' => 246,
                'consignment_charges_types_id' => 2,
                'charge' => '0.23',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-11-11 16:35:29',
                'updated_by' => 58,
                'updated_date' => '2019-11-11 16:35:29',
            ),
            100 => 
            array (
                'id' => 1,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 2,
                'charge' => '15.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:23:49',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            101 => 
            array (
                'id' => 2,
                'user_account_id' => 2285,
                'service_id' => 244,
                'consignment_charges_types_id' => 3,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-11-30 03:24:59',
                'updated_by' => NULL,
                'updated_date' => NULL,
            ),
            102 => 
            array (
                'id' => 3,
                'user_account_id' => 2295,
                'service_id' => 246,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2181,
                'added_date' => '2018-12-17 15:59:14',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 15:59:14',
            ),
            103 => 
            array (
                'id' => 4,
                'user_account_id' => 2290,
                'service_id' => 261,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 2175,
                'added_date' => '2018-12-17 16:19:41',
                'updated_by' => 2175,
                'updated_date' => '2018-12-17 16:19:41',
            ),
            104 => 
            array (
                'id' => 6,
                'user_account_id' => 2295,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '4.00',
                'charge_type' => 'percentage',
                'added_by' => 2181,
                'added_date' => '2018-12-17 16:40:20',
                'updated_by' => 2181,
                'updated_date' => '2018-12-17 16:40:20',
            ),
            105 => 
            array (
                'id' => 7,
                'user_account_id' => 2296,
                'service_id' => 244,
                'consignment_charges_types_id' => 23,
                'charge' => '3.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-17 16:41:30',
                'updated_by' => 2185,
                'updated_date' => '2018-12-17 16:41:30',
            ),
            106 => 
            array (
                'id' => 8,
                'user_account_id' => 2296,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '7.00',
                'charge_type' => 'fixed',
                'added_by' => 2185,
                'added_date' => '2018-12-18 10:09:34',
                'updated_by' => 2185,
                'updated_date' => '2018-12-18 10:09:34',
            ),
            107 => 
            array (
                'id' => 9,
                'user_account_id' => 2294,
                'service_id' => 3,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:22:42',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:22:42',
            ),
            108 => 
            array (
                'id' => 11,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:32:51',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:32:51',
            ),
            109 => 
            array (
                'id' => 12,
                'user_account_id' => 2294,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-18 13:23:50',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 13:23:50',
            ),
            110 => 
            array (
                'id' => 13,
                'user_account_id' => 2285,
                'service_id' => 263,
                'consignment_charges_types_id' => 26,
                'charge' => '1.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-18 14:00:48',
                'updated_by' => 58,
                'updated_date' => '2018-12-18 14:00:48',
            ),
            111 => 
            array (
                'id' => 14,
                'user_account_id' => 2285,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:09:58',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:09:58',
            ),
            112 => 
            array (
                'id' => 15,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:13',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:13',
            ),
            113 => 
            array (
                'id' => 16,
                'user_account_id' => 2285,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:10:33',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:10:33',
            ),
            114 => 
            array (
                'id' => 17,
                'user_account_id' => 2285,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 11:15:23',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 11:15:23',
            ),
            115 => 
            array (
                'id' => 18,
                'user_account_id' => 2300,
                'service_id' => 226,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:11',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:11',
            ),
            116 => 
            array (
                'id' => 19,
                'user_account_id' => 2300,
                'service_id' => 38,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-19 16:55:34',
                'updated_by' => 58,
                'updated_date' => '2018-12-19 16:55:34',
            ),
            117 => 
            array (
                'id' => 20,
                'user_account_id' => 2294,
                'service_id' => 2,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-21 11:31:53',
                'updated_by' => 58,
                'updated_date' => '2018-12-21 11:31:53',
            ),
            118 => 
            array (
                'id' => 21,
                'user_account_id' => 2294,
                'service_id' => 277,
                'consignment_charges_types_id' => 23,
                'charge' => '5.00',
                'charge_type' => 'fixed',
                'added_by' => 58,
                'added_date' => '2018-12-31 16:36:44',
                'updated_by' => 58,
                'updated_date' => '2018-12-31 16:36:44',
            ),
            119 => 
            array (
                'id' => 24,
                'user_account_id' => 2294,
                'service_id' => 38,
                'consignment_charges_types_id' => 2,
                'charge' => '25.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-03-05 11:33:31',
                'updated_by' => 58,
                'updated_date' => '2019-03-05 11:33:31',
            ),
            120 => 
            array (
                'id' => 25,
                'user_account_id' => 2297,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '10.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-01 11:30:19',
                'updated_by' => 58,
                'updated_date' => '2019-09-01 11:30:19',
            ),
            121 => 
            array (
                'id' => 26,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 2,
                'charge' => '6.50',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 13:01:56',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 13:01:56',
            ),
            122 => 
            array (
                'id' => 27,
                'user_account_id' => 2332,
                'service_id' => 226,
                'consignment_charges_types_id' => 9,
                'charge' => '7.00',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-09-04 14:36:11',
                'updated_by' => 58,
                'updated_date' => '2019-09-04 14:36:11',
            ),
            123 => 
            array (
                'id' => 28,
                'user_account_id' => 2337,
                'service_id' => 4,
                'consignment_charges_types_id' => 2,
                'charge' => '5.00',
                'charge_type' => 'percentage',
                'added_by' => 2295,
                'added_date' => '2019-09-10 13:10:17',
                'updated_by' => 2295,
                'updated_date' => '2019-09-10 13:10:17',
            ),
            124 => 
            array (
                'id' => 29,
                'user_account_id' => 2228,
                'service_id' => 246,
                'consignment_charges_types_id' => 2,
                'charge' => '0.23',
                'charge_type' => 'percentage',
                'added_by' => 58,
                'added_date' => '2019-11-11 16:35:29',
                'updated_by' => 58,
                'updated_date' => '2019-11-11 16:35:29',
            ),
        ));
        
        
    }
}