<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class VehiclesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('vehicles')->delete();
        
        \DB::table('vehicles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'vehicle_type' => 'Vehicle Type',
                'vehicle_make' => 'Honda',
                'model_year' => 2018,
                'vehicle_model' => 'Vehicle Model',
                'registration_number' => '1212REG321',
                'vehicle_color' => 'black',
                'vehicle_capacity' => '2',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 10:40:23',
                'added_by' => 2183,
                'vehicle_number' => '1248',
                'updated_date' => '2019-05-10 10:47:23',
                'updated_by' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'Honda',
                'model_year' => 2013,
                'vehicle_model' => 'Civic',
                'registration_number' => '111REG2013',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 11:31:04',
                'added_by' => 2183,
                'vehicle_number' => '3412',
                'updated_date' => '2019-05-10 11:31:04',
                'updated_by' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Mercedes',
                'model_year' => 2019,
                'vehicle_model' => 'SALOON',
                'registration_number' => 'ABC XYZ',
                'vehicle_color' => 'WHITE',
                'vehicle_capacity' => '100',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 14:51:41',
                'added_by' => 58,
                'vehicle_number' => '1',
                'updated_date' => '2019-05-10 14:51:41',
                'updated_by' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Toyota',
                'model_year' => 2015,
                'vehicle_model' => 'XLI',
                'registration_number' => 'LEZ-15-2011',
                'vehicle_color' => 'Silver',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:00:10',
                'added_by' => 58,
                'vehicle_number' => '2011',
                'updated_date' => '2019-07-10 17:00:10',
                'updated_by' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'vehicle_type' => 'test',
                'vehicle_make' => 'test',
                'model_year' => 2014,
                'vehicle_model' => 'test',
                'registration_number' => 'test',
                'vehicle_color' => 'test',
                'vehicle_capacity' => 'test',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:28:49',
                'added_by' => 58,
                'vehicle_number' => 'test',
                'updated_date' => '2019-07-10 17:28:49',
                'updated_by' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'BML',
                'model_year' => 2014,
                'vehicle_model' => 'Suzuki',
                'registration_number' => 'LEZ-14-458',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-15 10:45:19',
                'added_by' => 2201,
                'vehicle_number' => '458',
                'updated_date' => '2019-07-15 10:45:19',
                'updated_by' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'vehicle_type' => 'Mazda',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2018,
                'vehicle_model' => 'BMC',
                'registration_number' => 'LEY-18-2354 A',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '40',
                'is_deleted' => 0,
                'added_date' => '2019-07-23 16:15:14',
                'added_by' => 58,
                'vehicle_number' => '2354 A',
                'updated_date' => '2019-07-23 16:15:14',
                'updated_by' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'vehicle_type' => 'mazda',
                'vehicle_make' => 'suzuki',
                'model_year' => 2013,
                'vehicle_model' => 'WagonR',
                'registration_number' => 'oasdj3424',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '20',
                'is_deleted' => 0,
                'added_date' => '2019-07-30 09:37:41',
                'added_by' => 58,
                'vehicle_number' => '3asda',
                'updated_date' => '2019-07-30 09:37:41',
                'updated_by' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Honda',
                'model_year' => 2017,
                'vehicle_model' => 'Civic',
                'registration_number' => 'LEZ-17-418',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:30:50',
                'added_by' => 2252,
                'vehicle_number' => '418',
                'updated_date' => '2019-08-30 12:30:50',
                'updated_by' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'vehicle_type' => 'Carry',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2014,
                'vehicle_model' => 'Bolan',
                'registration_number' => 'PKK-14-2987',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '8',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:33:12',
                'added_by' => 2269,
                'vehicle_number' => '2987',
                'updated_date' => '2019-08-30 12:33:12',
                'updated_by' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2010,
                'vehicle_model' => 'Alto',
                'registration_number' => 'ICT-10-4321',
                'vehicle_color' => 'White',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:58:01',
                'added_by' => 2252,
                'vehicle_number' => '4321',
                'updated_date' => '2019-08-30 12:58:01',
                'updated_by' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'vehicle_type' => 'Test',
                'vehicle_make' => 'Test',
                'model_year' => 2018,
                'vehicle_model' => 'Test',
                'registration_number' => '4543535435',
                'vehicle_color' => 'Test',
                'vehicle_capacity' => '34',
                'is_deleted' => 0,
                'added_date' => '2019-11-07 18:47:12',
                'added_by' => 58,
                'vehicle_number' => '435345',
                'updated_date' => '2019-11-07 18:47:12',
                'updated_by' => 0,
            ),
            12 => 
            array (
                'id' => 1,
                'vehicle_type' => 'Vehicle Type',
                'vehicle_make' => 'Honda',
                'model_year' => 2018,
                'vehicle_model' => 'Vehicle Model',
                'registration_number' => '1212REG321',
                'vehicle_color' => 'black',
                'vehicle_capacity' => '2',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 10:40:23',
                'added_by' => 2183,
                'vehicle_number' => '1248',
                'updated_date' => '2019-05-10 10:47:23',
                'updated_by' => 0,
            ),
            13 => 
            array (
                'id' => 2,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'Honda',
                'model_year' => 2013,
                'vehicle_model' => 'Civic',
                'registration_number' => '111REG2013',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 11:31:04',
                'added_by' => 2183,
                'vehicle_number' => '3412',
                'updated_date' => '2019-05-10 11:31:04',
                'updated_by' => 0,
            ),
            14 => 
            array (
                'id' => 3,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Mercedes',
                'model_year' => 2019,
                'vehicle_model' => 'SALOON',
                'registration_number' => 'ABC XYZ',
                'vehicle_color' => 'WHITE',
                'vehicle_capacity' => '100',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 14:51:41',
                'added_by' => 58,
                'vehicle_number' => '1',
                'updated_date' => '2019-05-10 14:51:41',
                'updated_by' => 0,
            ),
            15 => 
            array (
                'id' => 4,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Toyota',
                'model_year' => 2015,
                'vehicle_model' => 'XLI',
                'registration_number' => 'LEZ-15-2011',
                'vehicle_color' => 'Silver',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:00:10',
                'added_by' => 58,
                'vehicle_number' => '2011',
                'updated_date' => '2019-07-10 17:00:10',
                'updated_by' => 0,
            ),
            16 => 
            array (
                'id' => 5,
                'vehicle_type' => 'test',
                'vehicle_make' => 'test',
                'model_year' => 2014,
                'vehicle_model' => 'test',
                'registration_number' => 'test',
                'vehicle_color' => 'test',
                'vehicle_capacity' => 'test',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:28:49',
                'added_by' => 58,
                'vehicle_number' => 'test',
                'updated_date' => '2019-07-10 17:28:49',
                'updated_by' => 0,
            ),
            17 => 
            array (
                'id' => 6,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'BML',
                'model_year' => 2014,
                'vehicle_model' => 'Suzuki',
                'registration_number' => 'LEZ-14-458',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-15 10:45:19',
                'added_by' => 2201,
                'vehicle_number' => '458',
                'updated_date' => '2019-07-15 10:45:19',
                'updated_by' => 0,
            ),
            18 => 
            array (
                'id' => 7,
                'vehicle_type' => 'Mazda',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2018,
                'vehicle_model' => 'BMC',
                'registration_number' => 'LEY-18-2354 A',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '40',
                'is_deleted' => 0,
                'added_date' => '2019-07-23 16:15:14',
                'added_by' => 58,
                'vehicle_number' => '2354 A',
                'updated_date' => '2019-07-23 16:15:14',
                'updated_by' => 0,
            ),
            19 => 
            array (
                'id' => 8,
                'vehicle_type' => 'mazda',
                'vehicle_make' => 'suzuki',
                'model_year' => 2013,
                'vehicle_model' => 'WagonR',
                'registration_number' => 'oasdj3424',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '20',
                'is_deleted' => 0,
                'added_date' => '2019-07-30 09:37:41',
                'added_by' => 58,
                'vehicle_number' => '3asda',
                'updated_date' => '2019-07-30 09:37:41',
                'updated_by' => 0,
            ),
            20 => 
            array (
                'id' => 9,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Honda',
                'model_year' => 2017,
                'vehicle_model' => 'Civic',
                'registration_number' => 'LEZ-17-418',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:30:50',
                'added_by' => 2252,
                'vehicle_number' => '418',
                'updated_date' => '2019-08-30 12:30:50',
                'updated_by' => 0,
            ),
            21 => 
            array (
                'id' => 10,
                'vehicle_type' => 'Carry',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2014,
                'vehicle_model' => 'Bolan',
                'registration_number' => 'PKK-14-2987',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '8',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:33:12',
                'added_by' => 2269,
                'vehicle_number' => '2987',
                'updated_date' => '2019-08-30 12:33:12',
                'updated_by' => 0,
            ),
            22 => 
            array (
                'id' => 11,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2010,
                'vehicle_model' => 'Alto',
                'registration_number' => 'ICT-10-4321',
                'vehicle_color' => 'White',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:58:01',
                'added_by' => 2252,
                'vehicle_number' => '4321',
                'updated_date' => '2019-08-30 12:58:01',
                'updated_by' => 0,
            ),
            23 => 
            array (
                'id' => 12,
                'vehicle_type' => 'Test',
                'vehicle_make' => 'Test',
                'model_year' => 2018,
                'vehicle_model' => 'Test',
                'registration_number' => '4543535435',
                'vehicle_color' => 'Test',
                'vehicle_capacity' => '34',
                'is_deleted' => 0,
                'added_date' => '2019-11-07 18:47:12',
                'added_by' => 58,
                'vehicle_number' => '435345',
                'updated_date' => '2019-11-07 18:47:12',
                'updated_by' => 0,
            ),
            24 => 
            array (
                'id' => 1,
                'vehicle_type' => 'Vehicle Type',
                'vehicle_make' => 'Honda',
                'model_year' => 2018,
                'vehicle_model' => 'Vehicle Model',
                'registration_number' => '1212REG321',
                'vehicle_color' => 'black',
                'vehicle_capacity' => '2',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 10:40:23',
                'added_by' => 2183,
                'vehicle_number' => '1248',
                'updated_date' => '2019-05-10 10:47:23',
                'updated_by' => 0,
            ),
            25 => 
            array (
                'id' => 2,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'Honda',
                'model_year' => 2013,
                'vehicle_model' => 'Civic',
                'registration_number' => '111REG2013',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 11:31:04',
                'added_by' => 2183,
                'vehicle_number' => '3412',
                'updated_date' => '2019-05-10 11:31:04',
                'updated_by' => 0,
            ),
            26 => 
            array (
                'id' => 3,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Mercedes',
                'model_year' => 2019,
                'vehicle_model' => 'SALOON',
                'registration_number' => 'ABC XYZ',
                'vehicle_color' => 'WHITE',
                'vehicle_capacity' => '100',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 14:51:41',
                'added_by' => 58,
                'vehicle_number' => '1',
                'updated_date' => '2019-05-10 14:51:41',
                'updated_by' => 0,
            ),
            27 => 
            array (
                'id' => 4,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Toyota',
                'model_year' => 2015,
                'vehicle_model' => 'XLI',
                'registration_number' => 'LEZ-15-2011',
                'vehicle_color' => 'Silver',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:00:10',
                'added_by' => 58,
                'vehicle_number' => '2011',
                'updated_date' => '2019-07-10 17:00:10',
                'updated_by' => 0,
            ),
            28 => 
            array (
                'id' => 5,
                'vehicle_type' => 'test',
                'vehicle_make' => 'test',
                'model_year' => 2014,
                'vehicle_model' => 'test',
                'registration_number' => 'test',
                'vehicle_color' => 'test',
                'vehicle_capacity' => 'test',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:28:49',
                'added_by' => 58,
                'vehicle_number' => 'test',
                'updated_date' => '2019-07-10 17:28:49',
                'updated_by' => 0,
            ),
            29 => 
            array (
                'id' => 6,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'BML',
                'model_year' => 2014,
                'vehicle_model' => 'Suzuki',
                'registration_number' => 'LEZ-14-458',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-15 10:45:19',
                'added_by' => 2201,
                'vehicle_number' => '458',
                'updated_date' => '2019-07-15 10:45:19',
                'updated_by' => 0,
            ),
            30 => 
            array (
                'id' => 7,
                'vehicle_type' => 'Mazda',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2018,
                'vehicle_model' => 'BMC',
                'registration_number' => 'LEY-18-2354 A',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '40',
                'is_deleted' => 0,
                'added_date' => '2019-07-23 16:15:14',
                'added_by' => 58,
                'vehicle_number' => '2354 A',
                'updated_date' => '2019-07-23 16:15:14',
                'updated_by' => 0,
            ),
            31 => 
            array (
                'id' => 8,
                'vehicle_type' => 'mazda',
                'vehicle_make' => 'suzuki',
                'model_year' => 2013,
                'vehicle_model' => 'WagonR',
                'registration_number' => 'oasdj3424',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '20',
                'is_deleted' => 0,
                'added_date' => '2019-07-30 09:37:41',
                'added_by' => 58,
                'vehicle_number' => '3asda',
                'updated_date' => '2019-07-30 09:37:41',
                'updated_by' => 0,
            ),
            32 => 
            array (
                'id' => 9,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Honda',
                'model_year' => 2017,
                'vehicle_model' => 'Civic',
                'registration_number' => 'LEZ-17-418',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:30:50',
                'added_by' => 2252,
                'vehicle_number' => '418',
                'updated_date' => '2019-08-30 12:30:50',
                'updated_by' => 0,
            ),
            33 => 
            array (
                'id' => 10,
                'vehicle_type' => 'Carry',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2014,
                'vehicle_model' => 'Bolan',
                'registration_number' => 'PKK-14-2987',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '8',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:33:12',
                'added_by' => 2269,
                'vehicle_number' => '2987',
                'updated_date' => '2019-08-30 12:33:12',
                'updated_by' => 0,
            ),
            34 => 
            array (
                'id' => 11,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2010,
                'vehicle_model' => 'Alto',
                'registration_number' => 'ICT-10-4321',
                'vehicle_color' => 'White',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:58:01',
                'added_by' => 2252,
                'vehicle_number' => '4321',
                'updated_date' => '2019-08-30 12:58:01',
                'updated_by' => 0,
            ),
            35 => 
            array (
                'id' => 12,
                'vehicle_type' => 'Test',
                'vehicle_make' => 'Test',
                'model_year' => 2018,
                'vehicle_model' => 'Test',
                'registration_number' => '4543535435',
                'vehicle_color' => 'Test',
                'vehicle_capacity' => '34',
                'is_deleted' => 0,
                'added_date' => '2019-11-07 18:47:12',
                'added_by' => 58,
                'vehicle_number' => '435345',
                'updated_date' => '2019-11-07 18:47:12',
                'updated_by' => 0,
            ),
            36 => 
            array (
                'id' => 1,
                'vehicle_type' => 'Vehicle Type',
                'vehicle_make' => 'Honda',
                'model_year' => 2018,
                'vehicle_model' => 'Vehicle Model',
                'registration_number' => '1212REG321',
                'vehicle_color' => 'black',
                'vehicle_capacity' => '2',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 10:40:23',
                'added_by' => 2183,
                'vehicle_number' => '1248',
                'updated_date' => '2019-05-10 10:47:23',
                'updated_by' => 0,
            ),
            37 => 
            array (
                'id' => 2,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'Honda',
                'model_year' => 2013,
                'vehicle_model' => 'Civic',
                'registration_number' => '111REG2013',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 11:31:04',
                'added_by' => 2183,
                'vehicle_number' => '3412',
                'updated_date' => '2019-05-10 11:31:04',
                'updated_by' => 0,
            ),
            38 => 
            array (
                'id' => 3,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Mercedes',
                'model_year' => 2019,
                'vehicle_model' => 'SALOON',
                'registration_number' => 'ABC XYZ',
                'vehicle_color' => 'WHITE',
                'vehicle_capacity' => '100',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 14:51:41',
                'added_by' => 58,
                'vehicle_number' => '1',
                'updated_date' => '2019-05-10 14:51:41',
                'updated_by' => 0,
            ),
            39 => 
            array (
                'id' => 4,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Toyota',
                'model_year' => 2015,
                'vehicle_model' => 'XLI',
                'registration_number' => 'LEZ-15-2011',
                'vehicle_color' => 'Silver',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:00:10',
                'added_by' => 58,
                'vehicle_number' => '2011',
                'updated_date' => '2019-07-10 17:00:10',
                'updated_by' => 0,
            ),
            40 => 
            array (
                'id' => 5,
                'vehicle_type' => 'test',
                'vehicle_make' => 'test',
                'model_year' => 2014,
                'vehicle_model' => 'test',
                'registration_number' => 'test',
                'vehicle_color' => 'test',
                'vehicle_capacity' => 'test',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:28:49',
                'added_by' => 58,
                'vehicle_number' => 'test',
                'updated_date' => '2019-07-10 17:28:49',
                'updated_by' => 0,
            ),
            41 => 
            array (
                'id' => 6,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'BML',
                'model_year' => 2014,
                'vehicle_model' => 'Suzuki',
                'registration_number' => 'LEZ-14-458',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-15 10:45:19',
                'added_by' => 2201,
                'vehicle_number' => '458',
                'updated_date' => '2019-07-15 10:45:19',
                'updated_by' => 0,
            ),
            42 => 
            array (
                'id' => 7,
                'vehicle_type' => 'Mazda',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2018,
                'vehicle_model' => 'BMC',
                'registration_number' => 'LEY-18-2354 A',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '40',
                'is_deleted' => 0,
                'added_date' => '2019-07-23 16:15:14',
                'added_by' => 58,
                'vehicle_number' => '2354 A',
                'updated_date' => '2019-07-23 16:15:14',
                'updated_by' => 0,
            ),
            43 => 
            array (
                'id' => 8,
                'vehicle_type' => 'mazda',
                'vehicle_make' => 'suzuki',
                'model_year' => 2013,
                'vehicle_model' => 'WagonR',
                'registration_number' => 'oasdj3424',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '20',
                'is_deleted' => 0,
                'added_date' => '2019-07-30 09:37:41',
                'added_by' => 58,
                'vehicle_number' => '3asda',
                'updated_date' => '2019-07-30 09:37:41',
                'updated_by' => 0,
            ),
            44 => 
            array (
                'id' => 9,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Honda',
                'model_year' => 2017,
                'vehicle_model' => 'Civic',
                'registration_number' => 'LEZ-17-418',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:30:50',
                'added_by' => 2252,
                'vehicle_number' => '418',
                'updated_date' => '2019-08-30 12:30:50',
                'updated_by' => 0,
            ),
            45 => 
            array (
                'id' => 10,
                'vehicle_type' => 'Carry',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2014,
                'vehicle_model' => 'Bolan',
                'registration_number' => 'PKK-14-2987',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '8',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:33:12',
                'added_by' => 2269,
                'vehicle_number' => '2987',
                'updated_date' => '2019-08-30 12:33:12',
                'updated_by' => 0,
            ),
            46 => 
            array (
                'id' => 11,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2010,
                'vehicle_model' => 'Alto',
                'registration_number' => 'ICT-10-4321',
                'vehicle_color' => 'White',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:58:01',
                'added_by' => 2252,
                'vehicle_number' => '4321',
                'updated_date' => '2019-08-30 12:58:01',
                'updated_by' => 0,
            ),
            47 => 
            array (
                'id' => 12,
                'vehicle_type' => 'Test',
                'vehicle_make' => 'Test',
                'model_year' => 2018,
                'vehicle_model' => 'Test',
                'registration_number' => '4543535435',
                'vehicle_color' => 'Test',
                'vehicle_capacity' => '34',
                'is_deleted' => 0,
                'added_date' => '2019-11-07 18:47:12',
                'added_by' => 58,
                'vehicle_number' => '435345',
                'updated_date' => '2019-11-07 18:47:12',
                'updated_by' => 0,
            ),
            48 => 
            array (
                'id' => 1,
                'vehicle_type' => 'Vehicle Type',
                'vehicle_make' => 'Honda',
                'model_year' => 2018,
                'vehicle_model' => 'Vehicle Model',
                'registration_number' => '1212REG321',
                'vehicle_color' => 'black',
                'vehicle_capacity' => '2',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 10:40:23',
                'added_by' => 2183,
                'vehicle_number' => '1248',
                'updated_date' => '2019-05-10 10:47:23',
                'updated_by' => 0,
            ),
            49 => 
            array (
                'id' => 2,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'Honda',
                'model_year' => 2013,
                'vehicle_model' => 'Civic',
                'registration_number' => '111REG2013',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 11:31:04',
                'added_by' => 2183,
                'vehicle_number' => '3412',
                'updated_date' => '2019-05-10 11:31:04',
                'updated_by' => 0,
            ),
            50 => 
            array (
                'id' => 3,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Mercedes',
                'model_year' => 2019,
                'vehicle_model' => 'SALOON',
                'registration_number' => 'ABC XYZ',
                'vehicle_color' => 'WHITE',
                'vehicle_capacity' => '100',
                'is_deleted' => 0,
                'added_date' => '2019-05-10 14:51:41',
                'added_by' => 58,
                'vehicle_number' => '1',
                'updated_date' => '2019-05-10 14:51:41',
                'updated_by' => 0,
            ),
            51 => 
            array (
                'id' => 4,
                'vehicle_type' => 'VAN',
                'vehicle_make' => 'Toyota',
                'model_year' => 2015,
                'vehicle_model' => 'XLI',
                'registration_number' => 'LEZ-15-2011',
                'vehicle_color' => 'Silver',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:00:10',
                'added_by' => 58,
                'vehicle_number' => '2011',
                'updated_date' => '2019-07-10 17:00:10',
                'updated_by' => 0,
            ),
            52 => 
            array (
                'id' => 5,
                'vehicle_type' => 'test',
                'vehicle_make' => 'test',
                'model_year' => 2014,
                'vehicle_model' => 'test',
                'registration_number' => 'test',
                'vehicle_color' => 'test',
                'vehicle_capacity' => 'test',
                'is_deleted' => 0,
                'added_date' => '2019-07-10 17:28:49',
                'added_by' => 58,
                'vehicle_number' => 'test',
                'updated_date' => '2019-07-10 17:28:49',
                'updated_by' => 0,
            ),
            53 => 
            array (
                'id' => 6,
                'vehicle_type' => 'Car',
                'vehicle_make' => 'BML',
                'model_year' => 2014,
                'vehicle_model' => 'Suzuki',
                'registration_number' => 'LEZ-14-458',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '4',
                'is_deleted' => 0,
                'added_date' => '2019-07-15 10:45:19',
                'added_by' => 2201,
                'vehicle_number' => '458',
                'updated_date' => '2019-07-15 10:45:19',
                'updated_by' => 0,
            ),
            54 => 
            array (
                'id' => 7,
                'vehicle_type' => 'Mazda',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2018,
                'vehicle_model' => 'BMC',
                'registration_number' => 'LEY-18-2354 A',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '40',
                'is_deleted' => 0,
                'added_date' => '2019-07-23 16:15:14',
                'added_by' => 58,
                'vehicle_number' => '2354 A',
                'updated_date' => '2019-07-23 16:15:14',
                'updated_by' => 0,
            ),
            55 => 
            array (
                'id' => 8,
                'vehicle_type' => 'mazda',
                'vehicle_make' => 'suzuki',
                'model_year' => 2013,
                'vehicle_model' => 'WagonR',
                'registration_number' => 'oasdj3424',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '20',
                'is_deleted' => 0,
                'added_date' => '2019-07-30 09:37:41',
                'added_by' => 58,
                'vehicle_number' => '3asda',
                'updated_date' => '2019-07-30 09:37:41',
                'updated_by' => 0,
            ),
            56 => 
            array (
                'id' => 9,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Honda',
                'model_year' => 2017,
                'vehicle_model' => 'Civic',
                'registration_number' => 'LEZ-17-418',
                'vehicle_color' => 'Red',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:30:50',
                'added_by' => 2252,
                'vehicle_number' => '418',
                'updated_date' => '2019-08-30 12:30:50',
                'updated_by' => 0,
            ),
            57 => 
            array (
                'id' => 10,
                'vehicle_type' => 'Carry',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2014,
                'vehicle_model' => 'Bolan',
                'registration_number' => 'PKK-14-2987',
                'vehicle_color' => 'Grey',
                'vehicle_capacity' => '8',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:33:12',
                'added_by' => 2269,
                'vehicle_number' => '2987',
                'updated_date' => '2019-08-30 12:33:12',
                'updated_by' => 0,
            ),
            58 => 
            array (
                'id' => 11,
                'vehicle_type' => 'CAR',
                'vehicle_make' => 'Suzuki',
                'model_year' => 2010,
                'vehicle_model' => 'Alto',
                'registration_number' => 'ICT-10-4321',
                'vehicle_color' => 'White',
                'vehicle_capacity' => '5',
                'is_deleted' => 0,
                'added_date' => '2019-08-30 12:58:01',
                'added_by' => 2252,
                'vehicle_number' => '4321',
                'updated_date' => '2019-08-30 12:58:01',
                'updated_by' => 0,
            ),
            59 => 
            array (
                'id' => 12,
                'vehicle_type' => 'Test',
                'vehicle_make' => 'Test',
                'model_year' => 2018,
                'vehicle_model' => 'Test',
                'registration_number' => '4543535435',
                'vehicle_color' => 'Test',
                'vehicle_capacity' => '34',
                'is_deleted' => 0,
                'added_date' => '2019-11-07 18:47:12',
                'added_by' => 58,
                'vehicle_number' => '435345',
                'updated_date' => '2019-11-07 18:47:12',
                'updated_by' => 0,
            ),
        ));
        
        
    }
}