<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class WarehousesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('warehouses')->delete();
        
        \DB::table('warehouses')->insert(array (
            0 => 
            array (
                'id' => 9,
                'warehouse_name' => 'Birmingham3',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Bartley Green',
                'citytown' => 'Birmingham',
                'postzipcode' => 'B32 3BZ',
                'countryid' => 225,
                'phone' => '01214217330',
                'description' => 'BHX',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:13',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:13',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'BHX',
            ),
            1 => 
            array (
                'id' => 10,
                'warehouse_name' => 'Hayes',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Hayes',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAY',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAY',
            ),
            2 => 
            array (
                'id' => 11,
                'warehouse_name' => 'Ealing',
                'addressline1' => 'Mail Options',
                'addressline2' => 'Mail Options',
                'stateregion' => 'Ealing',
                'citytown' => 'London',
                'postzipcode' => '',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'EAL',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2016-08-07 16:30:00',
                'added_by' => 4,
                'updated_date' => '2016-08-07 16:30:00',
                'updated_by' => 4,
                'hub' => 'Ealing Sorting Centre',
                'email' => 'jhunjan@mailoptions.co.uk',
                'warehouse_code' => NULL,
            ),
            3 => 
            array (
                'id' => 12,
                'warehouse_name' => 'Dublin',
                'addressline1' => 'Dublin',
                'addressline2' => '',
                'stateregion' => 'Dublin',
                'citytown' => 'Dublin',
                'postzipcode' => '94568',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'DUB',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:46:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:46:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'DUB',
            ),
            4 => 
            array (
                'id' => 13,
                'warehouse_name' => 'Hamburg',
                'addressline1' => 'Hamburg',
                'addressline2' => '',
                'stateregion' => 'Hamburg',
                'citytown' => 'Hamburg',
                'postzipcode' => '22049',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAM',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:16',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:16',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAM',
            ),
            5 => 
            array (
                'id' => 15,
                'warehouse_name' => 'Orange',
                'addressline1' => 'Orange',
                'addressline2' => '',
                'stateregion' => 'Orange',
                'citytown' => 'Orange',
                'postzipcode' => '92782',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'NYS',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:45',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:45',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'NYS',
            ),
            6 => 
            array (
                'id' => 36,
                'warehouse_name' => 'UK Mail Sorting Hub',
                'addressline1' => 'Waterside Trading Centre',
                'addressline2' => '',
                'stateregion' => 'Trumpers Way',
                'citytown' => 'London',
                'postzipcode' => 'W7 2QD	',
                'countryid' => 225,
            'phone' => '+44 (0)20 8571 ',
                'description' => '',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:52',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:52',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'UKM',
            ),
            7 => 
            array (
                'id' => 37,
                'warehouse_name' => 'AFG Warehouse',
                'addressline1' => 'Test Address 2',
                'addressline2' => '',
                'stateregion' => 'Test Region',
                'citytown' => 'Test City',
                'postzipcode' => 'UB3 5DZ',
                'countryid' => 1,
                'phone' => '23154894651231',
                'description' => 'This is to test warehouse in country other than UK',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:55',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:55',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'AFG',
            ),
            8 => 
            array (
                'id' => 38,
                'warehouse_name' => 'xx defence, xx defence',
                'addressline1' => 'xx defence, xx defence',
                'addressline2' => '',
                'stateregion' => 'Cheshire',
                'citytown' => 'Boston',
                'postzipcode' => '01004',
                'countryid' => 225,
                'phone' => '3214518055',
                'description' => 'this is description ',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:00',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:00',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '000',
            ),
            9 => 
            array (
                'id' => 39,
                'warehouse_name' => 'Test Warehouse',
                'addressline1' => 'Address Line 1',
                'addressline2' => '',
                'stateregion' => 'London',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '4545454545',
                'description' => 'Test Warehouse',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:03',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:03',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '456',
            ),
            10 => 
            array (
                'id' => 40,
                'warehouse_name' => 'testing',
                'addressline1' => 'address 1',
                'addressline2' => '',
                'stateregion' => 'testing',
                'citytown' => 'testing',
                'postzipcode' => '234',
                'countryid' => 19,
                'phone' => '2423432423',
                'description' => '324324',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:06',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:06',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '233',
            ),
            11 => 
            array (
                'id' => 9,
                'warehouse_name' => 'Birmingham3',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Bartley Green',
                'citytown' => 'Birmingham',
                'postzipcode' => 'B32 3BZ',
                'countryid' => 225,
                'phone' => '01214217330',
                'description' => 'BHX',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:13',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:13',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'BHX',
            ),
            12 => 
            array (
                'id' => 10,
                'warehouse_name' => 'Hayes',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Hayes',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAY',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAY',
            ),
            13 => 
            array (
                'id' => 11,
                'warehouse_name' => 'Ealing',
                'addressline1' => 'Mail Options',
                'addressline2' => 'Mail Options',
                'stateregion' => 'Ealing',
                'citytown' => 'London',
                'postzipcode' => '',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'EAL',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2016-08-07 16:30:00',
                'added_by' => 4,
                'updated_date' => '2016-08-07 16:30:00',
                'updated_by' => 4,
                'hub' => 'Ealing Sorting Centre',
                'email' => 'jhunjan@mailoptions.co.uk',
                'warehouse_code' => NULL,
            ),
            14 => 
            array (
                'id' => 12,
                'warehouse_name' => 'Dublin',
                'addressline1' => 'Dublin',
                'addressline2' => '',
                'stateregion' => 'Dublin',
                'citytown' => 'Dublin',
                'postzipcode' => '94568',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'DUB',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:46:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:46:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'DUB',
            ),
            15 => 
            array (
                'id' => 13,
                'warehouse_name' => 'Hamburg',
                'addressline1' => 'Hamburg',
                'addressline2' => '',
                'stateregion' => 'Hamburg',
                'citytown' => 'Hamburg',
                'postzipcode' => '22049',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAM',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:16',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:16',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAM',
            ),
            16 => 
            array (
                'id' => 15,
                'warehouse_name' => 'Orange',
                'addressline1' => 'Orange',
                'addressline2' => '',
                'stateregion' => 'Orange',
                'citytown' => 'Orange',
                'postzipcode' => '92782',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'NYS',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:45',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:45',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'NYS',
            ),
            17 => 
            array (
                'id' => 36,
                'warehouse_name' => 'UK Mail Sorting Hub',
                'addressline1' => 'Waterside Trading Centre',
                'addressline2' => '',
                'stateregion' => 'Trumpers Way',
                'citytown' => 'London',
                'postzipcode' => 'W7 2QD	',
                'countryid' => 225,
            'phone' => '+44 (0)20 8571 ',
                'description' => '',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:52',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:52',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'UKM',
            ),
            18 => 
            array (
                'id' => 37,
                'warehouse_name' => 'AFG Warehouse',
                'addressline1' => 'Test Address 2',
                'addressline2' => '',
                'stateregion' => 'Test Region',
                'citytown' => 'Test City',
                'postzipcode' => 'UB3 5DZ',
                'countryid' => 1,
                'phone' => '23154894651231',
                'description' => 'This is to test warehouse in country other than UK',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:55',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:55',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'AFG',
            ),
            19 => 
            array (
                'id' => 38,
                'warehouse_name' => 'xx defence, xx defence',
                'addressline1' => 'xx defence, xx defence',
                'addressline2' => '',
                'stateregion' => 'Cheshire',
                'citytown' => 'Boston',
                'postzipcode' => '01004',
                'countryid' => 225,
                'phone' => '3214518055',
                'description' => 'this is description ',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:00',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:00',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '000',
            ),
            20 => 
            array (
                'id' => 39,
                'warehouse_name' => 'Test Warehouse',
                'addressline1' => 'Address Line 1',
                'addressline2' => '',
                'stateregion' => 'London',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '4545454545',
                'description' => 'Test Warehouse',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:03',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:03',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '456',
            ),
            21 => 
            array (
                'id' => 40,
                'warehouse_name' => 'testing',
                'addressline1' => 'address 1',
                'addressline2' => '',
                'stateregion' => 'testing',
                'citytown' => 'testing',
                'postzipcode' => '234',
                'countryid' => 19,
                'phone' => '2423432423',
                'description' => '324324',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:06',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:06',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '233',
            ),
            22 => 
            array (
                'id' => 9,
                'warehouse_name' => 'Birmingham3',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Bartley Green',
                'citytown' => 'Birmingham',
                'postzipcode' => 'B32 3BZ',
                'countryid' => 225,
                'phone' => '01214217330',
                'description' => 'BHX',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:13',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:13',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'BHX',
            ),
            23 => 
            array (
                'id' => 10,
                'warehouse_name' => 'Hayes',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Hayes',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAY',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAY',
            ),
            24 => 
            array (
                'id' => 11,
                'warehouse_name' => 'Ealing',
                'addressline1' => 'Mail Options',
                'addressline2' => 'Mail Options',
                'stateregion' => 'Ealing',
                'citytown' => 'London',
                'postzipcode' => '',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'EAL',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2016-08-07 16:30:00',
                'added_by' => 4,
                'updated_date' => '2016-08-07 16:30:00',
                'updated_by' => 4,
                'hub' => 'Ealing Sorting Centre',
                'email' => 'jhunjan@mailoptions.co.uk',
                'warehouse_code' => NULL,
            ),
            25 => 
            array (
                'id' => 12,
                'warehouse_name' => 'Dublin',
                'addressline1' => 'Dublin',
                'addressline2' => '',
                'stateregion' => 'Dublin',
                'citytown' => 'Dublin',
                'postzipcode' => '94568',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'DUB',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:46:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:46:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'DUB',
            ),
            26 => 
            array (
                'id' => 13,
                'warehouse_name' => 'Hamburg',
                'addressline1' => 'Hamburg',
                'addressline2' => '',
                'stateregion' => 'Hamburg',
                'citytown' => 'Hamburg',
                'postzipcode' => '22049',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAM',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:16',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:16',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAM',
            ),
            27 => 
            array (
                'id' => 15,
                'warehouse_name' => 'Orange',
                'addressline1' => 'Orange',
                'addressline2' => '',
                'stateregion' => 'Orange',
                'citytown' => 'Orange',
                'postzipcode' => '92782',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'NYS',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:45',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:45',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'NYS',
            ),
            28 => 
            array (
                'id' => 36,
                'warehouse_name' => 'UK Mail Sorting Hub',
                'addressline1' => 'Waterside Trading Centre',
                'addressline2' => '',
                'stateregion' => 'Trumpers Way',
                'citytown' => 'London',
                'postzipcode' => 'W7 2QD	',
                'countryid' => 225,
            'phone' => '+44 (0)20 8571 ',
                'description' => '',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:52',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:52',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'UKM',
            ),
            29 => 
            array (
                'id' => 37,
                'warehouse_name' => 'AFG Warehouse',
                'addressline1' => 'Test Address 2',
                'addressline2' => '',
                'stateregion' => 'Test Region',
                'citytown' => 'Test City',
                'postzipcode' => 'UB3 5DZ',
                'countryid' => 1,
                'phone' => '23154894651231',
                'description' => 'This is to test warehouse in country other than UK',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:55',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:55',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'AFG',
            ),
            30 => 
            array (
                'id' => 38,
                'warehouse_name' => 'xx defence, xx defence',
                'addressline1' => 'xx defence, xx defence',
                'addressline2' => '',
                'stateregion' => 'Cheshire',
                'citytown' => 'Boston',
                'postzipcode' => '01004',
                'countryid' => 225,
                'phone' => '3214518055',
                'description' => 'this is description ',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:00',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:00',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '000',
            ),
            31 => 
            array (
                'id' => 39,
                'warehouse_name' => 'Test Warehouse',
                'addressline1' => 'Address Line 1',
                'addressline2' => '',
                'stateregion' => 'London',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '4545454545',
                'description' => 'Test Warehouse',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:03',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:03',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '456',
            ),
            32 => 
            array (
                'id' => 40,
                'warehouse_name' => 'testing',
                'addressline1' => 'address 1',
                'addressline2' => '',
                'stateregion' => 'testing',
                'citytown' => 'testing',
                'postzipcode' => '234',
                'countryid' => 19,
                'phone' => '2423432423',
                'description' => '324324',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:06',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:06',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '233',
            ),
            33 => 
            array (
                'id' => 9,
                'warehouse_name' => 'Birmingham3',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Bartley Green',
                'citytown' => 'Birmingham',
                'postzipcode' => 'B32 3BZ',
                'countryid' => 225,
                'phone' => '01214217330',
                'description' => 'BHX',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:13',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:13',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'BHX',
            ),
            34 => 
            array (
                'id' => 10,
                'warehouse_name' => 'Hayes',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Hayes',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAY',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAY',
            ),
            35 => 
            array (
                'id' => 11,
                'warehouse_name' => 'Ealing',
                'addressline1' => 'Mail Options',
                'addressline2' => 'Mail Options',
                'stateregion' => 'Ealing',
                'citytown' => 'London',
                'postzipcode' => '',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'EAL',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2016-08-07 16:30:00',
                'added_by' => 4,
                'updated_date' => '2016-08-07 16:30:00',
                'updated_by' => 4,
                'hub' => 'Ealing Sorting Centre',
                'email' => 'jhunjan@mailoptions.co.uk',
                'warehouse_code' => NULL,
            ),
            36 => 
            array (
                'id' => 12,
                'warehouse_name' => 'Dublin',
                'addressline1' => 'Dublin',
                'addressline2' => '',
                'stateregion' => 'Dublin',
                'citytown' => 'Dublin',
                'postzipcode' => '94568',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'DUB',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:46:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:46:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'DUB',
            ),
            37 => 
            array (
                'id' => 13,
                'warehouse_name' => 'Hamburg',
                'addressline1' => 'Hamburg',
                'addressline2' => '',
                'stateregion' => 'Hamburg',
                'citytown' => 'Hamburg',
                'postzipcode' => '22049',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAM',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:16',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:16',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAM',
            ),
            38 => 
            array (
                'id' => 15,
                'warehouse_name' => 'Orange',
                'addressline1' => 'Orange',
                'addressline2' => '',
                'stateregion' => 'Orange',
                'citytown' => 'Orange',
                'postzipcode' => '92782',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'NYS',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:45',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:45',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'NYS',
            ),
            39 => 
            array (
                'id' => 36,
                'warehouse_name' => 'UK Mail Sorting Hub',
                'addressline1' => 'Waterside Trading Centre',
                'addressline2' => '',
                'stateregion' => 'Trumpers Way',
                'citytown' => 'London',
                'postzipcode' => 'W7 2QD	',
                'countryid' => 225,
            'phone' => '+44 (0)20 8571 ',
                'description' => '',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:52',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:52',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'UKM',
            ),
            40 => 
            array (
                'id' => 37,
                'warehouse_name' => 'AFG Warehouse',
                'addressline1' => 'Test Address 2',
                'addressline2' => '',
                'stateregion' => 'Test Region',
                'citytown' => 'Test City',
                'postzipcode' => 'UB3 5DZ',
                'countryid' => 1,
                'phone' => '23154894651231',
                'description' => 'This is to test warehouse in country other than UK',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:55',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:55',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'AFG',
            ),
            41 => 
            array (
                'id' => 38,
                'warehouse_name' => 'xx defence, xx defence',
                'addressline1' => 'xx defence, xx defence',
                'addressline2' => '',
                'stateregion' => 'Cheshire',
                'citytown' => 'Boston',
                'postzipcode' => '01004',
                'countryid' => 225,
                'phone' => '3214518055',
                'description' => 'this is description ',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:00',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:00',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '000',
            ),
            42 => 
            array (
                'id' => 39,
                'warehouse_name' => 'Test Warehouse',
                'addressline1' => 'Address Line 1',
                'addressline2' => '',
                'stateregion' => 'London',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '4545454545',
                'description' => 'Test Warehouse',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:03',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:03',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '456',
            ),
            43 => 
            array (
                'id' => 40,
                'warehouse_name' => 'testing',
                'addressline1' => 'address 1',
                'addressline2' => '',
                'stateregion' => 'testing',
                'citytown' => 'testing',
                'postzipcode' => '234',
                'countryid' => 19,
                'phone' => '2423432423',
                'description' => '324324',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:06',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:06',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '233',
            ),
            44 => 
            array (
                'id' => 9,
                'warehouse_name' => 'Birmingham3',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Bartley Green',
                'citytown' => 'Birmingham',
                'postzipcode' => 'B32 3BZ',
                'countryid' => 225,
                'phone' => '01214217330',
                'description' => 'BHX',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:13',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:13',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'BHX',
            ),
            45 => 
            array (
                'id' => 10,
                'warehouse_name' => 'Hayes',
                'addressline1' => 'One World House',
                'addressline2' => '',
                'stateregion' => 'Hayes',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAY',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:44:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:44:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAY',
            ),
            46 => 
            array (
                'id' => 11,
                'warehouse_name' => 'Ealing',
                'addressline1' => 'Mail Options',
                'addressline2' => 'Mail Options',
                'stateregion' => 'Ealing',
                'citytown' => 'London',
                'postzipcode' => '',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'EAL',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2016-08-07 16:30:00',
                'added_by' => 4,
                'updated_date' => '2016-08-07 16:30:00',
                'updated_by' => 4,
                'hub' => 'Ealing Sorting Centre',
                'email' => 'jhunjan@mailoptions.co.uk',
                'warehouse_code' => NULL,
            ),
            47 => 
            array (
                'id' => 12,
                'warehouse_name' => 'Dublin',
                'addressline1' => 'Dublin',
                'addressline2' => '',
                'stateregion' => 'Dublin',
                'citytown' => 'Dublin',
                'postzipcode' => '94568',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'DUB',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:46:24',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:46:24',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'DUB',
            ),
            48 => 
            array (
                'id' => 13,
                'warehouse_name' => 'Hamburg',
                'addressline1' => 'Hamburg',
                'addressline2' => '',
                'stateregion' => 'Hamburg',
                'citytown' => 'Hamburg',
                'postzipcode' => '22049',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'HAM',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:16',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:16',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'HAM',
            ),
            49 => 
            array (
                'id' => 15,
                'warehouse_name' => 'Orange',
                'addressline1' => 'Orange',
                'addressline2' => '',
                'stateregion' => 'Orange',
                'citytown' => 'Orange',
                'postzipcode' => '92782',
                'countryid' => 225,
                'phone' => '02088676060',
                'description' => 'NYS',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:45',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:45',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'NYS',
            ),
            50 => 
            array (
                'id' => 36,
                'warehouse_name' => 'UK Mail Sorting Hub',
                'addressline1' => 'Waterside Trading Centre',
                'addressline2' => '',
                'stateregion' => 'Trumpers Way',
                'citytown' => 'London',
                'postzipcode' => 'W7 2QD	',
                'countryid' => 225,
            'phone' => '+44 (0)20 8571 ',
                'description' => '',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:52',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:52',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'UKM',
            ),
            51 => 
            array (
                'id' => 37,
                'warehouse_name' => 'AFG Warehouse',
                'addressline1' => 'Test Address 2',
                'addressline2' => '',
                'stateregion' => 'Test Region',
                'citytown' => 'Test City',
                'postzipcode' => 'UB3 5DZ',
                'countryid' => 1,
                'phone' => '23154894651231',
                'description' => 'This is to test warehouse in country other than UK',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:47:55',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:47:55',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => 'AFG',
            ),
            52 => 
            array (
                'id' => 38,
                'warehouse_name' => 'xx defence, xx defence',
                'addressline1' => 'xx defence, xx defence',
                'addressline2' => '',
                'stateregion' => 'Cheshire',
                'citytown' => 'Boston',
                'postzipcode' => '01004',
                'countryid' => 225,
                'phone' => '3214518055',
                'description' => 'this is description ',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:00',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:00',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '000',
            ),
            53 => 
            array (
                'id' => 39,
                'warehouse_name' => 'Test Warehouse',
                'addressline1' => 'Address Line 1',
                'addressline2' => '',
                'stateregion' => 'London',
                'citytown' => 'London',
                'postzipcode' => 'UB3 3NB',
                'countryid' => 225,
                'phone' => '4545454545',
                'description' => 'Test Warehouse',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:03',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:03',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '456',
            ),
            54 => 
            array (
                'id' => 40,
                'warehouse_name' => 'testing',
                'addressline1' => 'address 1',
                'addressline2' => '',
                'stateregion' => 'testing',
                'citytown' => 'testing',
                'postzipcode' => '234',
                'countryid' => 19,
                'phone' => '2423432423',
                'description' => '324324',
                'is_active' => 1,
                'is_deleted' => 0,
                'added_date' => '2020-03-04 13:48:06',
                'added_by' => 58,
                'updated_date' => '2020-03-04 14:48:06',
                'updated_by' => 58,
                'hub' => '',
                'email' => '',
                'warehouse_code' => '233',
            ),
        ));
        
        
    }
}