<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class YodelHubsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('yodel_hubs')->delete();
        
        \DB::table('yodel_hubs')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pre_sort_carrier_id' => 38,
                'hub' => '52_INVERNESS',
                'routing_code' => '52',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '12-14 Carsegate Road',
                'address_line_2' => 'North Inverness',
                'address_line_3' => 'NULL',
                'city' => 'North Inverness',
                'postcode' => 'IV3 8EA',
                'country_iso_code' => 'GB',
            ),
            1 => 
            array (
                'id' => 2,
                'pre_sort_carrier_id' => 38,
                'hub' => '08_LEEDS',
                'routing_code' => '08',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit F Gildersome',
                'address_line_2' => 'Spur Industrial Estate',
                'address_line_3' => 'Morley',
                'city' => 'Leeds',
                'postcode' => 'LS27 7JZ',
                'country_iso_code' => 'NUL',
            ),
            2 => 
            array (
                'id' => 3,
                'pre_sort_carrier_id' => 38,
                'hub' => '23_GATWICK',
                'routing_code' => '23',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'County Oak Industrial Estate',
                'address_line_2' => 'County Oak Way',
                'address_line_3' => 'Crawley',
                'city' => 'West Sussex',
                'postcode' => 'RH11 7ST',
                'country_iso_code' => 'GB',
            ),
            3 => 
            array (
                'id' => 4,
                'pre_sort_carrier_id' => 38,
                'hub' => '43_LLANDUDNO',
                'routing_code' => '43',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 20, Tre Marl Industrial Estate',
                'address_line_2' => 'Ffordd Maelgwyn',
                'address_line_3' => 'Llandudno Junction',
                'city' => 'Conwy',
                'postcode' => 'LL31 9PW',
                'country_iso_code' => 'GB',
            ),
            4 => 
            array (
                'id' => 5,
                'pre_sort_carrier_id' => 38,
                'hub' => '10_LLANELLI',
                'routing_code' => '10',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 10, Heol Cropin',
                'address_line_2' => 'Dafen Industrial Park ',
                'address_line_3' => 'Llanelli',
                'city' => 'Dyfed',
                'postcode' => 'SA14 8QW',
                'country_iso_code' => 'GB',
            ),
            5 => 
            array (
                'id' => 6,
                'pre_sort_carrier_id' => 38,
                'hub' => '16_ORKNEY',
                'routing_code' => '16',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            6 => 
            array (
                'id' => 7,
                'pre_sort_carrier_id' => 38,
                'hub' => '22_NEWTON_ABB',
                'routing_code' => '22',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '20 Battle Road',
                'address_line_2' => 'Heathfield',
                'address_line_3' => 'Newton Abbot',
                'city' => 'Devon',
                'postcode' => 'TQ12 6TN',
                'country_iso_code' => 'GB',
            ),
            7 => 
            array (
                'id' => 8,
                'pre_sort_carrier_id' => 38,
                'hub' => '95_SHETLAND',
                'routing_code' => '95',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            8 => 
            array (
                'id' => 1,
                'pre_sort_carrier_id' => 38,
                'hub' => '52_INVERNESS',
                'routing_code' => '52',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '12-14 Carsegate Road',
                'address_line_2' => 'North Inverness',
                'address_line_3' => 'NULL',
                'city' => 'North Inverness',
                'postcode' => 'IV3 8EA',
                'country_iso_code' => 'GB',
            ),
            9 => 
            array (
                'id' => 2,
                'pre_sort_carrier_id' => 38,
                'hub' => '08_LEEDS',
                'routing_code' => '08',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit F Gildersome',
                'address_line_2' => 'Spur Industrial Estate',
                'address_line_3' => 'Morley',
                'city' => 'Leeds',
                'postcode' => 'LS27 7JZ',
                'country_iso_code' => 'NUL',
            ),
            10 => 
            array (
                'id' => 3,
                'pre_sort_carrier_id' => 38,
                'hub' => '23_GATWICK',
                'routing_code' => '23',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'County Oak Industrial Estate',
                'address_line_2' => 'County Oak Way',
                'address_line_3' => 'Crawley',
                'city' => 'West Sussex',
                'postcode' => 'RH11 7ST',
                'country_iso_code' => 'GB',
            ),
            11 => 
            array (
                'id' => 4,
                'pre_sort_carrier_id' => 38,
                'hub' => '43_LLANDUDNO',
                'routing_code' => '43',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 20, Tre Marl Industrial Estate',
                'address_line_2' => 'Ffordd Maelgwyn',
                'address_line_3' => 'Llandudno Junction',
                'city' => 'Conwy',
                'postcode' => 'LL31 9PW',
                'country_iso_code' => 'GB',
            ),
            12 => 
            array (
                'id' => 5,
                'pre_sort_carrier_id' => 38,
                'hub' => '10_LLANELLI',
                'routing_code' => '10',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 10, Heol Cropin',
                'address_line_2' => 'Dafen Industrial Park ',
                'address_line_3' => 'Llanelli',
                'city' => 'Dyfed',
                'postcode' => 'SA14 8QW',
                'country_iso_code' => 'GB',
            ),
            13 => 
            array (
                'id' => 6,
                'pre_sort_carrier_id' => 38,
                'hub' => '16_ORKNEY',
                'routing_code' => '16',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            14 => 
            array (
                'id' => 7,
                'pre_sort_carrier_id' => 38,
                'hub' => '22_NEWTON_ABB',
                'routing_code' => '22',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '20 Battle Road',
                'address_line_2' => 'Heathfield',
                'address_line_3' => 'Newton Abbot',
                'city' => 'Devon',
                'postcode' => 'TQ12 6TN',
                'country_iso_code' => 'GB',
            ),
            15 => 
            array (
                'id' => 8,
                'pre_sort_carrier_id' => 38,
                'hub' => '95_SHETLAND',
                'routing_code' => '95',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            16 => 
            array (
                'id' => 1,
                'pre_sort_carrier_id' => 38,
                'hub' => '52_INVERNESS',
                'routing_code' => '52',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '12-14 Carsegate Road',
                'address_line_2' => 'North Inverness',
                'address_line_3' => 'NULL',
                'city' => 'North Inverness',
                'postcode' => 'IV3 8EA',
                'country_iso_code' => 'GB',
            ),
            17 => 
            array (
                'id' => 2,
                'pre_sort_carrier_id' => 38,
                'hub' => '08_LEEDS',
                'routing_code' => '08',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit F Gildersome',
                'address_line_2' => 'Spur Industrial Estate',
                'address_line_3' => 'Morley',
                'city' => 'Leeds',
                'postcode' => 'LS27 7JZ',
                'country_iso_code' => 'NUL',
            ),
            18 => 
            array (
                'id' => 3,
                'pre_sort_carrier_id' => 38,
                'hub' => '23_GATWICK',
                'routing_code' => '23',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'County Oak Industrial Estate',
                'address_line_2' => 'County Oak Way',
                'address_line_3' => 'Crawley',
                'city' => 'West Sussex',
                'postcode' => 'RH11 7ST',
                'country_iso_code' => 'GB',
            ),
            19 => 
            array (
                'id' => 4,
                'pre_sort_carrier_id' => 38,
                'hub' => '43_LLANDUDNO',
                'routing_code' => '43',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 20, Tre Marl Industrial Estate',
                'address_line_2' => 'Ffordd Maelgwyn',
                'address_line_3' => 'Llandudno Junction',
                'city' => 'Conwy',
                'postcode' => 'LL31 9PW',
                'country_iso_code' => 'GB',
            ),
            20 => 
            array (
                'id' => 5,
                'pre_sort_carrier_id' => 38,
                'hub' => '10_LLANELLI',
                'routing_code' => '10',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 10, Heol Cropin',
                'address_line_2' => 'Dafen Industrial Park ',
                'address_line_3' => 'Llanelli',
                'city' => 'Dyfed',
                'postcode' => 'SA14 8QW',
                'country_iso_code' => 'GB',
            ),
            21 => 
            array (
                'id' => 6,
                'pre_sort_carrier_id' => 38,
                'hub' => '16_ORKNEY',
                'routing_code' => '16',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            22 => 
            array (
                'id' => 7,
                'pre_sort_carrier_id' => 38,
                'hub' => '22_NEWTON_ABB',
                'routing_code' => '22',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '20 Battle Road',
                'address_line_2' => 'Heathfield',
                'address_line_3' => 'Newton Abbot',
                'city' => 'Devon',
                'postcode' => 'TQ12 6TN',
                'country_iso_code' => 'GB',
            ),
            23 => 
            array (
                'id' => 8,
                'pre_sort_carrier_id' => 38,
                'hub' => '95_SHETLAND',
                'routing_code' => '95',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            24 => 
            array (
                'id' => 1,
                'pre_sort_carrier_id' => 38,
                'hub' => '52_INVERNESS',
                'routing_code' => '52',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '12-14 Carsegate Road',
                'address_line_2' => 'North Inverness',
                'address_line_3' => 'NULL',
                'city' => 'North Inverness',
                'postcode' => 'IV3 8EA',
                'country_iso_code' => 'GB',
            ),
            25 => 
            array (
                'id' => 2,
                'pre_sort_carrier_id' => 38,
                'hub' => '08_LEEDS',
                'routing_code' => '08',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit F Gildersome',
                'address_line_2' => 'Spur Industrial Estate',
                'address_line_3' => 'Morley',
                'city' => 'Leeds',
                'postcode' => 'LS27 7JZ',
                'country_iso_code' => 'NUL',
            ),
            26 => 
            array (
                'id' => 3,
                'pre_sort_carrier_id' => 38,
                'hub' => '23_GATWICK',
                'routing_code' => '23',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'County Oak Industrial Estate',
                'address_line_2' => 'County Oak Way',
                'address_line_3' => 'Crawley',
                'city' => 'West Sussex',
                'postcode' => 'RH11 7ST',
                'country_iso_code' => 'GB',
            ),
            27 => 
            array (
                'id' => 4,
                'pre_sort_carrier_id' => 38,
                'hub' => '43_LLANDUDNO',
                'routing_code' => '43',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 20, Tre Marl Industrial Estate',
                'address_line_2' => 'Ffordd Maelgwyn',
                'address_line_3' => 'Llandudno Junction',
                'city' => 'Conwy',
                'postcode' => 'LL31 9PW',
                'country_iso_code' => 'GB',
            ),
            28 => 
            array (
                'id' => 5,
                'pre_sort_carrier_id' => 38,
                'hub' => '10_LLANELLI',
                'routing_code' => '10',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 10, Heol Cropin',
                'address_line_2' => 'Dafen Industrial Park ',
                'address_line_3' => 'Llanelli',
                'city' => 'Dyfed',
                'postcode' => 'SA14 8QW',
                'country_iso_code' => 'GB',
            ),
            29 => 
            array (
                'id' => 6,
                'pre_sort_carrier_id' => 38,
                'hub' => '16_ORKNEY',
                'routing_code' => '16',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            30 => 
            array (
                'id' => 7,
                'pre_sort_carrier_id' => 38,
                'hub' => '22_NEWTON_ABB',
                'routing_code' => '22',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '20 Battle Road',
                'address_line_2' => 'Heathfield',
                'address_line_3' => 'Newton Abbot',
                'city' => 'Devon',
                'postcode' => 'TQ12 6TN',
                'country_iso_code' => 'GB',
            ),
            31 => 
            array (
                'id' => 8,
                'pre_sort_carrier_id' => 38,
                'hub' => '95_SHETLAND',
                'routing_code' => '95',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            32 => 
            array (
                'id' => 1,
                'pre_sort_carrier_id' => 38,
                'hub' => '52_INVERNESS',
                'routing_code' => '52',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '12-14 Carsegate Road',
                'address_line_2' => 'North Inverness',
                'address_line_3' => 'NULL',
                'city' => 'North Inverness',
                'postcode' => 'IV3 8EA',
                'country_iso_code' => 'GB',
            ),
            33 => 
            array (
                'id' => 2,
                'pre_sort_carrier_id' => 38,
                'hub' => '08_LEEDS',
                'routing_code' => '08',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit F Gildersome',
                'address_line_2' => 'Spur Industrial Estate',
                'address_line_3' => 'Morley',
                'city' => 'Leeds',
                'postcode' => 'LS27 7JZ',
                'country_iso_code' => 'NUL',
            ),
            34 => 
            array (
                'id' => 3,
                'pre_sort_carrier_id' => 38,
                'hub' => '23_GATWICK',
                'routing_code' => '23',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'County Oak Industrial Estate',
                'address_line_2' => 'County Oak Way',
                'address_line_3' => 'Crawley',
                'city' => 'West Sussex',
                'postcode' => 'RH11 7ST',
                'country_iso_code' => 'GB',
            ),
            35 => 
            array (
                'id' => 4,
                'pre_sort_carrier_id' => 38,
                'hub' => '43_LLANDUDNO',
                'routing_code' => '43',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 20, Tre Marl Industrial Estate',
                'address_line_2' => 'Ffordd Maelgwyn',
                'address_line_3' => 'Llandudno Junction',
                'city' => 'Conwy',
                'postcode' => 'LL31 9PW',
                'country_iso_code' => 'GB',
            ),
            36 => 
            array (
                'id' => 5,
                'pre_sort_carrier_id' => 38,
                'hub' => '10_LLANELLI',
                'routing_code' => '10',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'Unit 10, Heol Cropin',
                'address_line_2' => 'Dafen Industrial Park ',
                'address_line_3' => 'Llanelli',
                'city' => 'Dyfed',
                'postcode' => 'SA14 8QW',
                'country_iso_code' => 'GB',
            ),
            37 => 
            array (
                'id' => 6,
                'pre_sort_carrier_id' => 38,
                'hub' => '16_ORKNEY',
                'routing_code' => '16',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
            38 => 
            array (
                'id' => 7,
                'pre_sort_carrier_id' => 38,
                'hub' => '22_NEWTON_ABB',
                'routing_code' => '22',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => '20 Battle Road',
                'address_line_2' => 'Heathfield',
                'address_line_3' => 'Newton Abbot',
                'city' => 'Devon',
                'postcode' => 'TQ12 6TN',
                'country_iso_code' => 'GB',
            ),
            39 => 
            array (
                'id' => 8,
                'pre_sort_carrier_id' => 38,
                'hub' => '95_SHETLAND',
                'routing_code' => '95',
                'company' => 'YODEL',
                'contact' => 'YODEL',
                'address_line_1' => 'NULL',
                'address_line_2' => 'NULL',
                'address_line_3' => 'NULL',
                'city' => 'NULL',
                'postcode' => 'NULL',
                'country_iso_code' => 'NUL',
            ),
        ));
        
        
    }
}